### ISSUE TITLE
Request for custom timing time parameter

### ISSUE THREAD

**Issue by nathanmarks** [DataDog/browser-sdk#1005]
We have some things that we collect timings for early on while loading pages, and don't track / submit them until we've got most of our client application loaded and running. We also dont sync load RUM, it's loaded async with the rest of our app.

We would like to use the custom timing API to submit them to RUM, but we would need a parameter like the one that was removed at some point during the original PR in order to do this:

https://github.com/DataDog/browser-sdk/pull/668/commits/5067d43525a5ba5ddf1c2f788e7ceb561103abef

**Comment by BenoitZugmeyer** [comment]
Your usecase seems legitimate. We'll discuss about restauring this argument, and we'll come back to you.

**Comment by nathanmarks** [comment]
@BenoitZugmeyer any update on this?

**Comment by bcaudan** [comment]
Hi @nathanmarks,

It is available in [v3.6.4](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#v364).
