### ISSUE TITLE
Datadoghq is blocked

### ISSUE THREAD

**Issue by Steven4294** [DataDog/browser-sdk#1014]
Hi all, have a pretty unusual use case for datadog. 

I am trying to send log data to DD, however many of our website visitors run ad blockers which blocks the datadoghq.com url. So when I make a POST request to `https://browser-http-intake.logs.datadoghq.com/v1/input/aca771460b2768e865553bee59089d36?ddsource=browser&ddtags=sdk_version%3A2.18.0`, the request is blocked by the browser. Is there a way to proxy these requests to a different URL so they aren't blocked by the ad blocker?

I'm using the `@datadog/browser-logs` node module, like follows:
```
import { datadogLogs } from '@datadog/browser-logs'

datadogLogs.init({
  clientToken: '<DATADOG_CLIENT_TOKEN>',
  site: '<DATADOG_SITE>',
  forwardErrorsToLogs: true,
  sampleRate: 100,
})
```
I thought perhaps that's what the site param in the initializer could be used for. Thanks in advance!

**Comment by bcaudan** [comment]
Hi @Steven4294,

Our recommandation for this case is documented [here](https://docs.datadoghq.com/real_user_monitoring/browser/troubleshooting/#missing-data).
