### ISSUE TITLE
Datadog logs sends many request when using it together with the RUM SDK.

### ISSUE THREAD

**Issue by radualex** [DataDog/browser-sdk#1022]
I have the following issue:

**Trigger**

An uncaught exception is being thrown and datadog logs SDK sends request to log the incident.

**Expected outcome**

One request is sent per incident and the incident is logged only once in Datadog UI.

**Actual outcome**

Datadog logs SDK sends many requests per incident (between 1k-2.5k) and the incident is logged many times in Datadog UI.

**Additional Information**

When disabling the Datadog RUM SDK, then the Datadog logs SDK behaves as expected (logs the incident once). However, I want to run them both, so this is not an option at the moment.

I am using version `3.1.3` for both `@datadog/browser-logs` and `@datadog/browser-rum` packages.

Here's a screenshot to illustrate the issue: (1 error thrown, many requests sent => the error is logged many times in Datadog UI)

[Many requests being sent for one uncaught exception example][1]

This is the code I am using to initialise both logs and RUM SDKs:

        import { datadogLogs } from '@datadog/browser-logs';
        import { datadogRum } from '@datadog/browser-rum';
    
        if (process.env.NODE_ENV === 'production' && process.env.DATADOG_CLIENT_TOKEN) {
                const environment = getEnvironment();
                const config = {
                    site: 'datadoghq.eu',
                    clientToken: process.env.DATADOG_CLIENT_TOKEN,
                    service: typeof DATADOG_SERVICE !== 'undefined' ? DATADOG_SERVICE : undefined,
                    env: environment ? `${environment}` : undefined,
                    proxyHost: process.env.PROXY_HOST
                };
            
                datadogLogs.init(config);
            
                
                    if (process.env.DATADOG_APPLICATION_ID) {
                        datadogRum.init({
                            ...config,
                            trackInteractions: true,
                            applicationId: process.env.DATADOG_APPLICATION_ID
                        });
            
                        datadogRum.setUser({
                            name: service.getName(),
                            email: service.getEmail()
                        });
                    }
        }

  [1]: https://i.stack.imgur.com/8xX8L.png

Is this a know issue?

**Comment by abereghici** [comment]
I encountered the same issue. `Reached max number of errors by minute: 3000`

**Comment by bcaudan** [comment]
Hi,

Thanks for the report, we will look into it shortly.

**Comment by bcaudan** [comment]
We have been able to identify the issue, it happens:

- for npm setup only
- with both logs and RUM installed
- since v2.18.0
- only for `console.error`

We are working on a fix, using v2.17.0 should avoid the issue in the mean time.

**Comment by radualex** [comment]
@bcaudan Nice. Thanks! 👍

**Comment by bcaudan** [comment]
Available in `browser-sdk@3.3.0`
