### ISSUE TITLE
Session Replay Beta privacy by default and new intake URLs

### ISSUE THREAD

**Issue by BenoitZugmeyer** [DataDog/browser-sdk#1047]
In a few days, a Browser SDK version will be released with changes that could impact the setup of beta users of Session Replay.

# Privacy by default

We introduce a new option to allow masking any text in the replay to make sure any private value is ignored. This option will be enabled by default on form inputs only (text input, checkbox, select, ...). To revert to the previous behavior where nothing is masked, use the `initialPrivacyLevel` option:

```js
DD_RUM.init({
  ...,
  defaultPrivacyLevel: 'allow'
})
```

More documentation will come in the future.

# New intake URLs

We have also updated our systems for the handling of our intake endpoints before GA from `https://session-replay.browser-intake-datadoghq.com/v1/input/…` to `https://session-replay.browser-intake-datadoghq.com/api/v2/…`. With that change, it may be an issue IF:

* Your environment [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) specifies a URL path. In this case, please use [recommended CSP entries](https://docs.datadoghq.com/real_user_monitoring/faq/content_security_policy/?tab=us).

* Your environment is using [the RUM init `proxyHost` configuration option](https://docs.datadoghq.com/real_user_monitoring/faq/proxy_rum_data/?tab=npm) and your proxy is only catching the `/v1/input/...` requests. In this case, please use [the new `proxyUrl` configuration option](https://docs.datadoghq.com/real_user_monitoring/faq/proxy_rum_data/?tab=npm) instead.

**Comment by codemouse** [comment]
This is great news. I realize these features are new, but as you update to accommodate privacy concerns please make sure to create/update appropriate documentation regarding use-cases concerned common use-cases including GDPR such as here: https://www.dynatrace.com/support/help/how-to-use-dynatrace/data-privacy-and-security/data-privacy/dynatrace-compliance-with-gdpr-for-eu-citizens/

**Comment by BenoitZugmeyer** [comment]
Thanks for your concerns. Some technical documentation has been added [here](https://docs.datadoghq.com/real_user_monitoring/guide/session-replay-getting-started/#sensitive--personal-data-obfuscation). A more general document about GDPR is in the works. We will provide more use-cases and improved APIs to handle end-user consent in the future.
