### ISSUE TITLE
Expand set of maskable fields in RUM

### ISSUE THREAD

**Issue by OmarJaroudi** [DataDog/browser-sdk#1067]
Is there any chance we could add more fields to the list mentioned in the [docs](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm), which we can mask or redact in `beforeSend`?
Also is there any chance we can expose the fields that we can't edit even if as `readonly`? 
Last question: is there any way in which we can mask or hide data related to the location/device of the user?

**Comment by bcaudan** [comment]
Hello @OmarJaroudi,

 > Is there any chance we could add more fields to the list mentioned in the docs, which we can mask or redact in beforeSend?

We have allowed to edit fields that could contain sensitive data. Do you have other fields in mind?

> is there any chance we can expose the fields that we can't edit even if as readonly?

I am not sure to understand what you mean. What are you trying to achieve?

> is there any way in which we can mask or hide data related to the location/device of the user?

This data is not collected directly by the SDK but processed by our backend from the IP and the user agent attached to the requests.
For now, it is possible to hide the IP, cf  https://github.com/DataDog/browser-sdk/issues/322#issuecomment-736644994
Happy to have more details on your use case and see if we can do something about it.

**Comment by OmarJaroudi** [comment]
> > is there any chance we can expose the fields that we can't edit even if as readonly?

So for example id like to hide `view.url` which I can already do, but I'd still like to have access to `view.url_path_group`

**Comment by bcaudan** [comment]
For this example, `view.url_path_group` is processed on the backend side so you need to send a `view.url` and for now there is no option to hide `view.url` afterwards.

However, you could parse `view.url` yourself in `beforeSend` and sanitize all the parts that you don't want to expose and keep the path in order to let the backend process the path group.

Something like:
```
url: https://my.domain.com/product/1234?foo=bar

      v  beforeSend sanitization

url: https://xxx.xxx/product/1234

      v  backend processing

path group: /product/?
```

Would it work for you?

**Comment by OmarJaroudi** [comment]
Fair enough! Thank you ❤️

**Comment by OmarJaroudi** [comment]
> This data is not collected directly by the SDK but processed by our backend from the IP and the user agent attached to the requests.
> For now, it is possible to hide the IP, cf [#322 (comment)](https://github.com/DataDog/browser-sdk/issues/322#issuecomment-736644994)
> Happy to have more details on your use case and see if we can do something about it.

It would have been optimal if I could have some control over the geolocation info showing at all or not, but according to your explanation it seems that it can't be managed like the other fields

**Comment by bcaudan** [comment]
For now, there is no way to easily configure that through the SDK or the Datadog application but it is an interesting use case.
You could maybe use a [proxy setup](https://docs.datadoghq.com/real_user_monitoring/faq/proxy_rum_data/?tab=npm#pagetitle) to control if the original ip should be forwarded or not.
