### ISSUE TITLE
Logs requests without the logs SDK

### ISSUE THREAD

**Issue by agrobbin** [DataDog/browser-sdk#1137]
While testing out RUM in our staging environment, we have been seeing requests to the DataDog logs intake server (`rum-http-intake.logs.datadoghq.com`) which seems surprising, since we have not included the logs SDK, just RUM.

Is that expected behavior?

**Comment by bcaudan** [comment]
Hello @agrobbin,

`rum-http-intake.logs.datadoghq.com` is the Datadog rum intake server, so no worries :sli

**Comment by agrobbin** [comment]
Super-helpful guidance, thanks @bcaudan! I just opened DataDog/documentation#12051.
