### ISSUE TITLE
configure handler for RUM during development

### ISSUE THREAD

**Issue by remkoboschker** [DataDog/browser-sdk#1150]
I would be useful if I can use RUM actions and errors everywhere to monitor my application and view them in the console during local development. I saw that an option exists for the logger, but not for rum. 

Is that on your roadmap, is there a workaround or would you accept an pr for that?

**Comment by bcaudan** [comment]
Hello @remkoboschker,

We indeed don't have an option to do that., you could achieve it however with the [beforeSend](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#enrich-and-control-rum-data) method. 
We also have an [internal extension](https://github.com/DataDog/browser-sdk/tree/main/developer-extension) in this repository that can be used to log events, feel free to have a look at it.

**Comment by remkoboschker** [comment]
Alright, thank you, I did not consider cancelling the events in the beforeSend handler. That would work just fine.
