### ISSUE TITLE
tslib updates?

### ISSUE THREAD

**Issue by liorosh** [DataDog/browser-sdk#1183]
Is there a special reason not to update `tslib`?
at the moment it is set to very old versions, and npm will not update to any version greater than 1.x.x
This causes a lot of duplications if a consumer already uses newer versions of `tslib` (e.g 2.x.x) and forces the consumer to bring both versions.

**Comment by bcaudan** [comment]
Hello @liorosh,

We have this on our radar, we'll probably try to remove the dependency. 
We'll ping here when we'll make progress on this topic.

**Comment by BenoitZugmeyer** [comment]
As of v4.6.0, tslib is no longer a Browser SDK dependency.
