### ISSUE TITLE
Error while running angular tests with ^3.6.0

### ISSUE THREAD

**Issue by calvinmuller** [DataDog/browser-sdk#1185]
I am getting the following when running my local tests after upgrading datadog for sessionReplay.

```
Error: node_modules/@datadog/browser-rum-core/src/domain/contextHistory.ts:18:5 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

18     this.clearOldContextsInterval = setInterval(() => this.clearOldContexts(), CLEAR_OLD_CONTEXTS_INTERVAL)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@datadog/browser-rum-core/src/domain/waitIdlePage.ts:80:7 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

80       idleTimeoutId = setTimeout(
         ~~~~~~~~~~~~~
```

Any ideas?

**Comment by BenoitZugmeyer** [comment]
Hello,

First, it seems strange that you get this error. When importing `@datadog/browser-rum` in your project, it should import `.js` files and validate types using `.d.ts`. You should not have errors coming from the source `.ts` files as they should not be used at all. Could you give more context on how do you get those error messages?

The error probably comes from your setup, where `@types/node` is automatically imported by TypeScript. One solution could be to use the [`compilerOptions.types` setting](https://www.typescriptlang.org/tsconfig#types) to list types to use explicitely, but a better solution would probably be to exclude your node_modules folder from the typechecking.

**Comment by calvinmuller** [comment]
@BenoitZugmeyer thanks I removed the types: ["node"] from my .spec.json in the angular project and problem solved. Thanks for your help.
