### ISSUE TITLE
Issues with automatic user interactions

### ISSUE THREAD

**Issue by MaheshGit233** [DataDog/browser-sdk#1190]
When we are using datadog-rum for tracking the user interactions automatically, we are seeing some issues when user opens any of the popover content and clicks outside before closing the popover/popup. 
In this scenario all the content inside the root node of clicked container is being logged in datadog logs which may have user related information. This behavior is even after using the custom action names for the elements that may have user information. 
After analyzing the code we identified that in this scenario it is picking all the innerText from the elements without checking for custom action names attributes. 
Please let us know if you need more information

**Comment by bcaudan** [comment]
Hello @MaheshGit233,

From my understanding, you have an issue with the automatic naming of click user actions where in a specific situation it uses the inner text of an element even if a custom action name is set.
If that is it, I am not sure to see how it relates to datadog logs 🤔

Anyway, could you share a simple example that could allow us to reproduce this behavior?

**Comment by MaheshGit233** [comment]
This is the sample repo. 
https://github.com/MaheshGit233/DatadogPOC.git

If you run this example and click on button (Popover on Bottom)
![image](https://user-images.githubusercontent.com/32537764/144205634-7be3a192-8fe9-4527-8564-9e190977b389.png)

Then if you click outside (exactly in between) the (This is not clickable) - inside element <p> and (Example of popover Dropdown in Angular in the page highlighted below) - inside element <h1>

![image](https://user-images.githubusercontent.com/32537764/144206401-7ee5c4af-8ff5-4cf1-93fa-c90de1e0efc9.png)

You will be seeing an alert with event details being sent to to datadog.  In the alert box see the action target name being sent

![image](https://user-images.githubusercontent.com/32537764/144206638-7b85e671-5c9d-4acb-be80-f08a54e333e9.png)

It is appending all the text inside the div node even after adding the custom action attribute data-dd-action-name = 'header' to the <h1> element

Let me know if you need any other details.

**Comment by MaheshGit233** [comment]
I have raised a PR to fix the above issue
https://github.com/DataDog/browser-sdk/pull/1200

Please review and let me know if any comments.

**Comment by BenoitZugmeyer** [comment]
The related PR #1200 has been merged and should be released in January.
