### ISSUE TITLE
[Logs] allowed to use beforeSend to change the log level?

### ISSUE THREAD

**Issue by kotarella1110** [DataDog/browser-sdk#1195]
In the following I want to set the log level to `warn` in case of a network error.
This seems to work correctly, but since I am using TS, I get a type error.

```ts
datadogLogs.init({
    ...,
    beforeSend: (log) => {
      if (log.error?.origin === "network") {
        log.status = "warn"; // error TS2540: Cannot assign to 'status' because it is a constant or a read-only property.
      }
    },
    ...
});
```

Is the `status` readonly because you don't allow the `status` to be changed?

**Comment by bcaudan** [comment]
Hello @kotarella1110,

For Logs, we allow users to change everything so it is indeed a typing issue.
Feel free to submit a PR for it, otherwise we'll tackle it at some point.

**Comment by kotarella1110** [comment]
@bcaudan I will create a PR to fix this!
Thanks 👋
