### ISSUE TITLE
[Logs] configure which errors to forward

### ISSUE THREAD

**Issue by kotarella1110** [DataDog/browser-sdk#1202]
The logs forwarded in case of `forwardErrorsToLogs: true` is as follows:

- `console.error` logs
- exceptions
- network errors

Currently, I use `beforeSend` to avoid forwarding the `console.error` logs as follows:

```ts
datadogLogs.init({
    ...,
    forwardErrorsToLogs: true,
    beforeSend: (log) => {
      if (log.error?.origin === "console") {
        return false;
      }
    },
    ...
});
```

I think it would be more useful to achieve this without using `beforeSend`.
I request `forwardErrorsToLogs` to accept both `booleans` and `error.origins`, and the ability to forward only specific error logs.

```ts
datadogLogs.init({
    ...,
    forwardErrorsToLogs: ["source", "network"], // (property) LogsInitConfiguration.forwardErrorsToLogs?: boolean | ("console" | "source" | "network")[] | undefined
    ...
});
```

If you guys like this feature, I will create a PR for it.

**Comment by bcaudan** [comment]
Hello @kotarella1110 ,

We are planning to add more collection options in the next quarter, so we will probably review our configuration options at this time.
We will keep your suggestion in mind but we will not integrate it for now to avoid to deprecate it soon.

**Comment by amortemousque** [comment]
Hello,

The Logs browser SDK now alllow to forward logs from console.* to Datadog using the `forwardConsoleLogs` init param. Use "all" to forward everything or an array of console API names to forward only a subset. `forwardConsoleLogs: ['info', 'debug', 'warn', 'info', 'error']`
