### ISSUE TITLE
Huge RUM errors slow down application, sends many network requests

### ISSUE THREAD

**Issue by sahilda** [DataDog/browser-sdk#1234]
On our application, we allow users to drag and drop and when doing so, our application is throwing many errors. In one such case the application throws 28 errors though the drag is successful. With RUM disabled, the application performance is fine. With RUM enabled, the performance drops and the site feels sluggish.

What I'm seeing is that for each error, it looks like RUM making a network request with the error details, causing the app to hangup until they're complete. I would've assumed RUM would batch the requests rather than making many individual ones.

Can we batch the error requests?

Image and video for additional context:

![image](https://user-images.githubusercontent.com/3886640/147128795-96cd4d8d-546b-4a6f-a9b5-7318f20bc674.png)

video: https://www.loom.com/share/ee1269a0a0484d97b5d6d980d704d67a

**Comment by bcaudan** [comment]
Hello @sahilda,

All collected events are batched but if each collected event is bigger than our maximum batch size, the SDK can end up sending one request by event.
Since the type of the requests in your video is xhr, it seems that it could be the case here (the type should be ping or beacon in normal cases).
Our maximum batch size is 16kb, could you check the sent errors to see if they are not too heavy?

**Comment by sahilda** [comment]
Yep, confirmed that the errors are often exceeding that limit unfortunately. I'm trying to get the dev team to fix the errors obviously, but is there anything else we can do in the mean time to keep RUM on but not take a such a performance toll?

**Comment by bcaudan** [comment]
If you can update the RUM init configuration, you could add a [beforeSend](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#discard-a-rum-event) method to identify and reject those errors.

**Comment by sahilda** [comment]
Great, thanks for your help. Going to close this issue as the 16kb seems like a batch limit and errors with larger stacks is likely unreasonable.

I suppose if there's a possible improvement on your side, it would be to allow the batch size to be configurable but then that might have an impact on your rum servers as well.
