### ISSUE TITLE
How to report 400 Bad requests as errors listed in "Error tracking"/"Ongoing issues"

### ISSUE THREAD

**Issue by ffissore** [DataDog/browser-sdk#1236]
We would like to track bad requests as bugs, since they mean the frontend was unable to guide users appropriately.

Is there a way to turn a fetch/xhr error into a "custom" error?

**Comment by bcaudan** [comment]
Hello @ffissore,

You could use `beforeSend` and `addError` to generate errors from resources, you have a similar example [here](https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#rum-errors).

**Comment by ffissore** [comment]
That looks exactly like what I was looking for. thx a lot!
