### ISSUE TITLE
Different custom errors are reported with the same `issueId`

### ISSUE THREAD

**Issue by ffissore** [DataDog/browser-sdk#1237]
Apologies in advance if this turns out to be a support request rather than a bug

We are using `browser-rum-slim` version `3.10.1` (latest at the time of writing) and we set up rum this way

```javascript
  function beforeSend(event, context) {
    // turn a "resource" error into an "ongoing issue" if backend returned a 400
    // because it means that frontend failed at guiding a user
    if (event.type === "resource" && event.resource.status_code === 400) {
      datadogRum.addError(new Error(`Bad request: ${event.resource.method} ${event.resource.url} ${event.resource.status_code}`), context);
    }
  }

  datadogRum.init({
    beforeSend,
    ...
```

When looking at the datadog rum application, I see the same error message, say, `Bad request: POST /url1 400` reported multiple times, but then I click `See in error tracking` and the message is different: the actual URL is a completely different one, sometimes even the host is different.

How come two different failed API calls result are grouped under the same issue id? Is it a bug, are we setting up rum badly?

**Comment by bcaudan** [comment]
Hello @ffissore,

The grouping of similar errors into issues for [error tracking](https://docs.datadoghq.com/real_user_monitoring/error_tracking/#what-is-error-tracking) is not done inside this repository.
You should get more help by reaching out to our [support](https://www.datadoghq.com/support/).

**Comment by ffissore** [comment]
Thx @bcaudan I'll reach out to support
