### ISSUE TITLE
datadog  context interface should be readOnly

### ISSUE THREAD

**Issue by azuruce** [DataDog/browser-sdk#1250]
```
export interface Context {
  [x: string]: ContextValue
}

export type ContextValue = string | number | boolean | Context | ContextArray | undefined | null

export interface ContextArray extends Array<ContextValue> {}
```

should change to
```
export interface Context {
  readonly [x: string]: ContextValue
}

export type ContextValue = string | number | boolean | Context | ContextArray | undefined | null

export interface ContextArray extends ReadonlyArray<ContextValue> {}
```

The reason is datadog is not modifying those values, and if we set those to mutable, we can't pass immutable value inside. But if we set it as immutable, we can pass mutable or immutable inside.

**Comment by BenoitZugmeyer** [comment]
Hello @azuruce and thank you for raising this issue.

`Context` objects are not readonly, even from a public API point of view: `DD_RUM.setRumGlobalContext(context)` sets a new context, and `DD_RUM.addRumGlobalContext(key, value)` mutates it. So I don't think we want to make everything readonly. Do you have a specific usecase? Maybe only arrays and values could be readonly.

**Comment by bcaudan** [comment]
Feel free to reopen if needed.
