### ISSUE TITLE
Uncaught ReferenceError: document is not defined

### ISSUE THREAD

**Issue by haranrk** [DataDog/browser-sdk#1281]
I am trying to use datadog to log from a web extension I am building. But, I get the following error whenever I call the logger.
```
Uncaught ReferenceError: document is not defined
```

The following a minimum viable test case to reproduce the error.

https://github.com/haranrk/test-webext

**Comment by BenoitZugmeyer** [comment]
Hello @haranrk.

It seems that you are using "manifest v3", which [only allows service workers in the background](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#background-service-workers). Unfortunately, the Logs Browser SDK [does not support workers yet](https://github.com/DataDog/browser-sdk/issues/432). Instead, you could use a "manifest v2" extension, with a background script or page.
