### ISSUE TITLE
Beforesend on event.type the contex value should be Error

### ISSUE THREAD

**Issue by maizoharil** [DataDog/browser-sdk#1320]

**Comment by maizoharil** [comment]
As it is written on the the [documentation](https://docs.datadoghq.com/real_user_monitoring/guide/enrich-and-control-rum-data/?tab=event#context) when the type of the event is "error" (not Error - like the table says)
The context value should be : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

But when we tried to find it : 
**context** is:
e: Object
error: "Script error."

the **event** is:
t: Object
action: {id: 'XXX'}
application: {id: 'XX'}
ci_test: undefined
context: {mh_context: {…}}
date: 1644224574852
error: {id: 'd99ab1da-0216-4a5f-8b31-2073960830b9', message: 'Script error.', resource: undefined, source: 'source', stack: 'Error: Script error.\n  at undefined @ ', …}
service: "mh-web"
session: {id: 'XXX', type: 'user', has_replay: undefined}
source: "browser"
synthetics: undefined
type: "error"

**Comment by BenoitZugmeyer** [comment]
Hello @maizoharil ,

The documentation is indeed imprecise, thanks for the headsup!

The `context.error` value is whatever value generated the error, and not necessarily an `Error` instance. In your particular case, the value is the string `"Script error."`: this is an expected browser behavior and you can fix it by following [this documentation](https://docs.datadoghq.com/real_user_monitoring/browser/collecting_browser_errors/?tab=npm#script-error).

I'll improve the doc, thanks for reporting it.

**Comment by maizoharil** [comment]
The error i sent was only an example, but also on production when all the scripts are loaded with crossorigin="anonymous"
We still get an empty context. the real error data is on the event.error
not as it is written in the documentation :
https://docs.datadoghq.com/real_user_monitoring/guide/enrich-and-control-rum-data/?tab=event#context

Thanks for the response 🥇

**Comment by BenoitZugmeyer** [comment]
> We still get an empty context

I'm not sure to get it. In your first message you wrote:

> context is:
> e: Object
> error: "Script error."

Meaning there is a `error` property in the context, no?

**Comment by bcaudan** [comment]
Feel free to reopen if needed.

**Comment by xMartin** [comment]
I have the same issue. Let me clarify:

If `event.type` is `"error"`, context should be the error itself (whatever was thrown) as by the doc pointed to above. But it is indeed just an empty object.

browser-rum version 4.34.1.

Please reopen.

**Comment by xMartin** [comment]
Nevermind. I confused `event.context` with the second argument `context`. The error instance is set as `context` as expected.
