### ISSUE TITLE
Preserve console log type for console handler

### ISSUE THREAD

**Issue by thebrubaker** [DataDog/browser-sdk#1329]
When using the console handler, all logs are rendered as a console.log call instead of the appropriate log level (examples being `console.warning` and `onsole.error`). For example, a call to `datadogLogs.logger.warn('this is a warning')` should be rendered to the console as a `console.warn('this is a warning')`.

Looking at the SDK it appears all logs are passed to `display.log()` - alternatively I would consider something like `display[status]()` to preserve the console's native logging levels.

Without this feature, it makes parsing through 100s of logs of varying levels incredibly more annoying as I can't use the native console filtering features.

Thanks for your help and hopefully I'm just doing something wrong and there is a way to preserve how the console renders.

**Comment by BenoitZugmeyer** [comment]
Hello @thebrubaker 

You are not doing something wrong. Thank you for your suggestion, we'll see what we can do!

**Comment by Scalahansolo** [comment]
+1 to this. This would be a massive improvement and make it much easier to use just the datalog logger during development compared to having to use console.log as well.

**Comment by bcaudan** [comment]
Available with 4.9.0 version.

**Comment by thebrubaker** [comment]
Thanks!!
