### ISSUE TITLE
Safari beacon error: reached maximum amount of queued data

### ISSUE THREAD

**Issue by paulrehkugler** [DataDog/browser-sdk#1348]
Hello!

We're seeing some errors from the `@datadog/browser-rum` package in Safari. Specifically, we get a beacon error:

```
Beacon API cannot load https://rum-http-intake.logs.datadoghq.com/v1/input/[...]?ddsource=browser&ddtags=sdk_version%3A2.12.0[...]. Reached maximum amount of queued data of 64Kb for keepalive requests
```

As you can see from the query parameters, we're running version 2.12.0, so it's possible that upgrading it will fix the issue. However, we're not seeing these issues in Chrome, so I am wondering if there are some unresolved browser-specific issues related to the Beacon API.

**Comment by bcaudan** [comment]
Hello @paulrehkugler,

This error is indeed only happening on safari, you can reproduce it with this code:

```javascript
const data = 'x'.repeat(100*1024)
const url = 'http://localhost'
try {
  console.log('beacon queued', navigator.sendBeacon(url, data))
} catch (e) {
  console.log('error caught', e)
}
console.log('after beacon')
```

Despite the try/catch the safari error is not caught.
This error does not prevent the SDK to collect the data, we have a fallback on XHR if the beacon data can not be queued.

**Comment by paulrehkugler** [comment]
Thank you! I'll keep in mind that we can safely ignore this error.

**Comment by MWChapel** [comment]
Hi, we are on 4.6.1 and are seeing this issue on Safari. It's spamming our console error log.
