### ISSUE TITLE
where is the best place to initialise datadog rum?

### ISSUE THREAD

**Issue by bzhaotheiconic** [DataDog/browser-sdk#1352]
Hi DD team,

We just start to use dd browser sdk and want to integrate DD with our nextJS app.

I'm wondering what is the best place to initialise it?
Shall I initialise it outside of top component as I did in the below screenshoot.
![Screen Shot 2022-02-22 at 1 58 24 pm](https://user-images.githubusercontent.com/97488935/155092597-a366e970-aabe-4303-9feb-ad0505691ea8.png)
Or Shall I put it inside a component and wrap it with useEffect above line 20?
Both seem to work at my end. Is there any suggestion?

**Comment by BenoitZugmeyer** [comment]
Both could work, but just initializing outside of a component seems simpler. Also, RUM will start to collect data when `init()` is called, so you might want to initialize it as early as possible to collect potential errors occuring during the first render of your app.
