### ISSUE TITLE
If I only use browser-log sdk instead of browser-rum sdk? Is there a place in DD website, I can track frontend app issue?

### ISSUE THREAD

**Issue by bzhaotheiconic** [DataDog/browser-sdk#1356]
Hi DD team,

I'm wondering if I can only use browser-log sdk (instead of browser-rum sdk) to log my frontend issue and see the logs in DD website?

Official Doc here mentions the setup for browser-log sdk and I'm wondering what is the use for that?
Can I track frontend issue in APM? or APM is strictly only for server side issue?
https://docs.datadoghq.com/logs/log_collection/javascript/?tab=npm

Thanks

**Comment by BenoitZugmeyer** [comment]
Hello @bzhaotheiconic

The Logs SDK will provide an API to send logs to Datadog manually (example: `DD_LOGS.logger.log("foo")`). By default, it will not do anything by itself.

But if you are using the `forwardErrorsToLogs: true` initialization parameter, the Logs SDK will automatically collect every errors happening on the page and send it as error logs that you'll be able to see in Datadog as any other log.

APM integration will only work with the RUM SDK though. You won't be able to see frontend traces with the Logs SDK alone.
