### ISSUE TITLE
Isomorphic SSR browser logging in Next.js throwing "document is not defined"

### ISSUE THREAD

**Issue by Southclaws** [DataDog/browser-sdk#1359]
Hey! This feels similar to https://github.com/DataDog/browser-sdk/issues/235 but I can't find any issues specific to the browser-logs package.

I work on a Next.js app with SSR and would love to be able to use the logger in either context (server and client) 

Any guidance on this? Or is the current solution just to disable the logger if the component is detected to be server rendered.

**Comment by BenoitZugmeyer** [comment]
The Browser SDK packages can be evaluated in Nodejs, but will fail to execute. So yes, loggers should not be used during server rendering.

**Comment by BenoitZugmeyer** [comment]
See our documentation: [NodeJS log collection](https://docs.datadoghq.com/logs/log_collection/nodejs/?tab=winston30)

**Comment by wintercounter** [comment]
@BenoitZugmeyer Can we re-open this? The answer isn't really helpful. I don't want logging on server side, I simply don't want my logs to fail during SSR. To make that happen, I need to mock the entire API of `datadogLogs` with noop functions, use a proxy, or create an overcomplicated custom logging solution. Besides, why I can't just send custom logs using the same API, without winston, without agent, etc... This makes SSR scenarios incredibly complicated to deal with.
