### ISSUE TITLE
Mention requirement of lowercase tags

### ISSUE THREAD

**Issue by ngbrown** [DataDog/browser-sdk#1361]
It's not mentioned on this page:

https://docs.datadoghq.com/real_user_monitoring/browser/
source: https://github.com/DataDog/browser-sdk/blob/main/packages/rum/README.md

that the initialization parameters need to be lower case, or specifically limited to these characters: `a-z0-9_:./-`.  Otherwise an error is shown in the browser console. Also the length is limited to (199-tag length) characters.

**Comment by BenoitZugmeyer** [comment]
Thanks for your feedback. The tags guidelines documentation is [here](https://docs.datadoghq.com/getting_started/tagging/#defining-tags). I will add a link to it in the SDK docs

**Comment by BenoitZugmeyer** [comment]
This has been released with #1362
