### ISSUE TITLE
Send custom metrics via HTTP with client token.

### ISSUE THREAD

**Issue by abhishekops** [DataDog/browser-sdk#1381]
Platform: Chrome Extension.

In relation to the [issue](https://github.com/DataDog/browser-sdk/issues/798), as Datadog RUM doesn't support non browser environments, as its based on a cookie, I was toying around on how metrics can be collected, and landed on the custom metrics API. As its client side, we would't want to expose the API key, according to the example cited [here](https://docs.datadoghq.com/api/latest/metrics/#submit-metrics). Is it possible to send custom metrics using the client token instead? Please assist. Thanks.

**Comment by BenoitZugmeyer** [comment]
Hello @abhishekops. It is not possible to use the metrics API with a client token, it requires an api key. If you want further details, please reach out to Datadog support, as the Browser SDK team does not have any ownership on the metrics API.

**Comment by abhishekops** [comment]
Thanks @BenoitZugmeyer.
