### ISSUE TITLE
All RUM data gone after 4.5->4.6 upgrade

### ISSUE THREAD

**Issue by nate-at-gusto** [DataDog/browser-sdk#1391]
<img width="1904" alt="Screen Shot 2022-03-09 at 10 23 44 AM" src="https://user-images.githubusercontent.com/82843455/157496506-5bad9ced-3954-4ec8-bbe3-3a0b37336f7d.png">

With no other changes except the upgrade from 4.5 -> 4.6, RUM seems to have completely stopped working. We are not seeing any errors in console.

**Comment by BenoitZugmeyer** [comment]
Hello @nate-at-gusto, thanks for the headsup. You are using the `@datadog/browser-rum` NPM package right? I just released a fix for that. Could you upgrade to `4.6.1`?

**Comment by nate-at-gusto** [comment]
Yup, 4.6.1 fixed it for us.
