### ISSUE TITLE
stopSessionReplayRecording breaks other replay libraries like FullStory

### ISSUE THREAD

**Issue by blimmer** [DataDog/browser-sdk#1397]
## Background

I have a client that's currently using both Datadog RUM Session Replay and [FullStory](https://www.fullstory.com/) to capture session replays. Currently, FullStory has other features and usability benefits (like tracking "Rage Clicks" and easier-to-create dashboards) that less technical users find easier to work with.

## The Problem

We've noticed that when Datadog session replay unloads its observers, it also breaks FullStory. I took a look at the source code and I believe this is the problem: https://github.com/DataDog/browser-sdk/blob/720b430a5356ca1de86e716cd1b6e0275288ec63/packages/rum/src/domain/record/observer.ts#L310-L343

The return value of this method is logic to `unload` the rule when `stop()` is called. As you can see, it captures the original prototype method in this function's closure.

This restoration behavior causes a problem in this scenario:

1. Datadog RUM loads **before** FullStory. The `prototype` methods captured are the native ones.
2. FullStory loads.
3. Datadog session replay is stopped.
4. The native prototype methods are restored, not the ones with the FullStory patch.

This issue holds true for any other libraries that patch these methods.

## FullStory

FullStory has some solution to this that maybe Datadog could crib off of. I spent a few minutes looking at their script (https://edge.fullstory.com/s/fs.js) and the `_hook` method they're defining and using to patch the prototype methods seems to be the key. Just in case something significantly changes in their code, here's the snippet at time of authoring this issue: https://pastebin.com/BCuJtfVL

Here's the testing I did:

| First Load | Second Load | Unloaded  | Result      |
| ---------- | ----------- | --------- | ----------- |
| Datadog    | -           | Datadog   | Native Code |
| FullStory  | -           | FullStory | Native Code | 
| Datadog    | FullStory   | Datadog   | Native Code |
| Datadog    | FullStory   | FullStory | Datadog     |
| FullStory  | Datadog     | Datadog   | FullStory   |
| FullStory  | Datadog     | FullStory | Datadog     |

As you can see from the top two rows, these are "baselines" to make sure that both libraries revert back to native code when unloaded.

The key difference is the third row. Ideally, the result of the third row is "FullStory" if this issue is fixed.

When I say "Unloaded" I mean:
- Datadog: run `DD_RUM.stopSessionReplayRecording()` in the console
- FullStory: run `FS.shutdown()` in the console

The "Result" is the function definition of `CSSStyleSheet.prototype.insertRule`. `Native Code` means "the original implementation provided by the browser". "Datadog" or "FullStory" means "the code that either library overwrites on the prototype of `CSSStyleSheet.prototype.insertRule`.

Here's a video to help explain:

<a href="https://www.loom.com/share/aebfae0185004634a204de90e1ed3dde">
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/aebfae0185004634a204de90e1ed3dde-with-play.gif">
</a>

**Comment by BenoitZugmeyer** [comment]
Hello, thank you very much for the thorough investigation! Like FullStory we also have utilities to [instrument methods](https://github.com/DataDog/browser-sdk/blob/main/packages/core/src/tools/instrumentMethod.ts), but it looks like we don't use it everywhere. We'll work on a fix soon.
