### ISSUE TITLE
DD_LOGS is already initialized (3 iframes in a single host website)

### ISSUE THREAD

**Issue by erkand-imeri** [DataDog/browser-sdk#1401]
Hello all, I created a RUM New Application and generated a client side token which i need to implement client-side browser logs.

Despite that i created a RUM New Application (the RUM dashboard is something i need for future), i am using the following package.

```js 
"@datadog/browser-logs": "^4.6.0",
```

and creating a Logger abstraction object for the datadog library.

```js
import { datadogLogs } from '@datadog/browser-logs';

const initDataDogLog = env => datadogLogs.init({
  applicationId: process.env.MIX_DATADOG_APPLICATION_ID,
  clientToken: process.env.MIX_DATADOG_CLIENT_TOKEN,
  site: process.env.MIX_DATADOG_SITE_NAME,
  service: process.env.MIX_SERVICE_NAME,
  env,
  // Specify a version number to identify the deployed version of your application in Datadog 
  // version: '1.0.0',
});


const successfulMessage = ticketId => (eventName, eventObj = null) => {
  if(eventObj) {
    datadogLogs.logger.info(`${eventName} has succeded for following ticket: ${ticketId}`, eventObj);
    return;
  }
  datadogLogs.logger.info(`${eventName} has succeded for following ticket: ${ticketId}`);
};

const failedMessage = ticketId => (eventName, eventObj = null) => {
  if(eventObj) {
    datadogLogs.logger.error(`${eventName} has failed for following ticket: ${ticketId}`, eventObj);
    return;
  }

  datadogLogs.logger.error(`${eventName} has failed for following ticket: ${ticketId}`);
};

const EVENT_NAME = {
  RANDOM_EVENT: "Random Event"
};

const Logger = (
  {
    ticketId,
    env,
  }) => {
  
  initDataDogLog(env);
  
  return {
    successful: successfulMessage(ticketId),
    failed: failedMessage(ticketId),
    EVENT_NAME,
  };
};

export default Logger;
```

So, i am actually using this dataDog.init in 3 iframes (separate hosted services) which are hosted at the same page. This code was working fine when i was testing at a single app, but when i uploaded the code to the other apps the logs were not coming to DataDog anymore and from browser console i could see the following log:

```js
DD_LOGS is already initialized.
```

From this i can deduce that DataDog does not allow more than one datadogLogs.init to happen.

If my assumption is correct how can i make each app datadogLogs.init unique on its own so this error gets not thrown.

Secondly, since i am using

```js 
@datadog/browser-logs
```

Do i need to specify the applicationId object field when initiliazing dataDog client-side logger when using @datadog/browser-logs or i can remove it?

```js
 datadogLogs.init({
  applicationId: process.env.MIX_DATADOG_APPLICATION_ID,
  clientToken: process.env.MIX_DATADOG_CLIENT_TOKEN,
  site: process.env.MIX_DATADOG_SITE_NAME,
  service: process.env.MIX_SERVICE_NAME,
  env,
  // Specify a version number to identify the deployed version of your application in Datadog 
  // version: '1.0.0',
});
```

Thanks in advance.

**Comment by BenoitZugmeyer** [comment]
Hello @erkand-imeri. As you are using three different iframes, I confirm that you should call `datadogLogs.init` once in each iframe (and once in the top document if you want to use logs there). Because `DD_LOGS is already initialized.` is displayed, I suspect that you are calling `datadogLogs.init` two times in the same iframe. Could you make sure that you only call it once?

> Do i need to specify the applicationId object field when initiliazing dataDog client-side logger when using @datadog/browser-logs or i can remove it?

You can remove it, logs don't use the `applicationId` param.

**Comment by erkand-imeri** [comment]
Hello @BenoitZugmeyer i confirm that it's working, the DD_LOGS is already initialized was indeed thrown when initializing second init, so putting the datadog init into separate iframes is not an issue at all since they seem to be encapsulated.

**Comment by BenoitZugmeyer** [comment]
Thanks for reporting back! Let us know if you need further assistance.
