### ISSUE TITLE
`forwardConsoleLogs` isn't documented

### ISSUE THREAD

**Issue by hognevevle** [DataDog/browser-sdk#1413]
Hi all,

In `LogsInitConfiguration`, I just noticed there is an `forwardConsoleLogs` option. However, this isn't documented on  https://docs.datadoghq.com/logs/log_collection/javascript/#configuration , or elsewhere for that matter, as far as I can see.

I wondered if it could be related to #400 , but I've tried enabling it, and it doesn't seem to work like I would expect.

EDIT: I see now in #1316 that this is under a feature flag, so I guess this simply isn't available for all users yet? If so, what would be the process to be able to use it?

**Comment by BenoitZugmeyer** [comment]
This feature is not released yet! As you observed, it is behind a feature flag as we are "dogfooding" it internally. We are still working out some issues, but it should be ready soon: our goal is to release it during next week if everything looks good.

**Comment by hognevevle** [comment]
Thanks a lot for clarifying @BenoitZugmeyer :)
