### ISSUE TITLE
@datadog/browser-rum 4.7.0 release is broken

### ISSUE THREAD

**Issue by beagleknight** [DataDog/browser-sdk#1468]
Hello!

I followed the documentation for the `@datadog/browser-rum` and it doesn't work as expected. Apparently, the `datadogRum` object doesn't include the method `init` like it was for version `4.6.2`. I don't know if it's a problem in the documentation or the public API object is broken.

Best regards,

**Comment by BenoitZugmeyer** [comment]
Hello, I can't reproduce. Could you provide more information? What are you using to build/bundle your project?

**Comment by beagleknight** [comment]
> Hello, I can't reproduce. Could you provide more information? What are you using to build/bundle your project?

Hi @BenoitZugmeyer !

I used the following code in our React application:

```
import { datadogRum } from '@datadog/browser-rum'

datadogRum.init({
  applicationId: '<DATADOG_APPLICATION_ID>',
  clientToken: '<DATADOG_CLIENT_TOKEN>',
  site: '<DATADOG_SITE>',
  //  service: 'my-web-application',
  //  env: 'production',
  //  version: '1.0.0',
  sampleRate: 100,
  trackInteractions: true,
})
```

We use Typescript, and we are building the app with `webpack@5.64.4`.

Cheers!

**Comment by BenoitZugmeyer** [comment]
I still cannot reproduce. If you manage to provide a minimal reproducible example, it could greatly help us understanding the issue. See this [gist](https://gist.github.com/BenoitZugmeyer/3a46eeb5204a21a24c4beee0dd826412) for example: building the project and serving the bundle file works as expected.

**Comment by beagleknight** [comment]
Hey @BenoitZugmeyer !
It looks like we were using different versions of `@datadog/browser-logs` and `@datadog/browser-rum`. This caused the wrong behavior, but after upgrading both packages to the latest version it works.
We can close the issue, thanks for your fast response!
