### ISSUE TITLE
Session Replay not masking placeholders

### ISSUE THREAD

**Issue by johnpangalos** [DataDog/browser-sdk#1504]
Input placeholders are not being masked when setting the `defaultPrivacyLevel: "mask"`. Is this the expected behavior?

**Comment by BenoitZugmeyer** [comment]
Thanks for your feedback. This is probably an omission on our part, and at first glance nothing prevents us from masking placeholders. We'll add this to our backlog.

**Comment by liywjl** [comment]
Hello @johnpangalos 

This issue has been resolved as of [v4.17.0](https://github.com/DataDog/browser-sdk/pull/1686)

Don't hesitate to open another ticket if you have a specific issue related to the SDK or contact [datadog support](https://www.datadoghq.com/support/) directly.
