### ISSUE TITLE
Getting the tracking type status

### ISSUE THREAD

**Issue by mortargrind** [DataDog/browser-sdk#1513]
What is the suggested way of getting the tracking status of the SDK for the given `sampleRate` value after calling the `init` method? Is it `_dd_s` cookie value?

I have a use case where I need to have additional logic executed _only_ for the sessions that are being actually tracked.

**Comment by amortemousque** [comment]
Hello @mortargrind,

We don't recommend to access the cookie as the format can change.
If you're using RUM browser SDK, you can use the `getInternalContext()` API mentioned in our [troubleshooting documentation](https://docs.datadoghq.com/real_user_monitoring/browser/troubleshooting/#browser-rum-sdk-initialized).
For Logs browser SDK, there is currently no recommended way to do it.

**Comment by mortargrind** [comment]
Ok that works for us; thanks for the answer.
