### ISSUE TITLE
datadogRum addRumGlobalContext/setUser and init Timing

### ISSUE THREAD

**Issue by indeediansbrett** [DataDog/browser-sdk#1517]
Could someone update the docs to indicate that setting users or adding RUM global context before the init method is allowed?  The documentation indicates to do this after, but the code indicates that setting before is allowed and is in fact preferred. It runs fine for the current version. Could this break in a future version?

Recently ran into a case where we had run datadogRum.init before running datadogRum.addRumGlobalContext/datadogRum.setUser. Initial resource events and the first document version event would had this extra information missing.

https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#replace-global-context

https://github.com/DataDog/browser-sdk/blob/cb1918e8a94a9fdabef9fcc3396a2bd0ddf8ad62/packages/rum-core/src/boot/rumPublicApi.ts#L59

https://github.com/DataDog/browser-sdk/blob/cb1918e8a94a9fdabef9fcc3396a2bd0ddf8ad62/packages/rum-core/src/boot/rumPublicApi.ts#L132

**Comment by amortemousque** [comment]
Thanks @indeediansbrett for the feedback. `setRumGlobalContext` and `setUser` used before RUM is initialized is officially supported. We will update the documentation accordingly.
