### ISSUE TITLE
Session Replay doesn't capture elements rendered in a Shadow DOM

### ISSUE THREAD

**Issue by ryan-willis** [DataDog/browser-sdk#1518]
I'm working in an environment where Web Components are loaded into a rendered page, and some of them [create shadow roots](https://web.dev/shadowdom-v1/) within their target elements in order to encapsulate their styles. These Web Components are not visible during Session Replay.

Furthermore, it appears as though _any_ elements in a `#shadow-root` are not visible during Session Replay. If you'd like to see an  example, I created a StackBlitz: https://stackblitz.com/edit/react-ts-5gwtzt (you'll need your own RUM application ID + token).

**Comment by bcaudan** [comment]
Hello @ryan-willis,

Shadow DOM is indeed not supported by our current implementation.
We'll look into it and keep you posted here.

Thanks for raising that!

**Comment by djm181** [comment]
We're interested in any update on this going into the sdk. Ionic PWAs end up missing out on a lot of content in the replay as a result of this gap.

**Comment by bcaudan** [comment]
We plan to make some progress on this topic this this quarter, we will let you know here when something is available.

**Comment by chankris** [comment]
We would like to know of any progress here. We are, like the others missing out on contents in our critical path with Shadow DOM

**Comment by amortemousque** [comment]
Hello @chankris ,
Shadow DOM is now official supported! 
I advice using our latest version (>=v4.44.0) to get the shadow DOM support and the performance improvement related to it.

**Comment by bcaudan** [comment]
@chankris RUM actions don't support shadow DOM for now and it is not in our current priorities.
Since this ticket is about session replay, I am closing it and you can follow [this one for RUM actions and shadow DOM](https://github.com/DataDog/browser-sdk/issues/2345).
