### ISSUE TITLE
Connecting logs with traces

### ISSUE THREAD

**Issue by luisabtrace** [DataDog/browser-sdk#1538]
First of all, I'd like to apologise for asking a question in an issue tracker.

I have what I think is a very simple use case, but I can't find a way to do it. I have a `fetch()` call that, if it fails, should log the trace id, so that when searching for the trace id in Datadog, I am able to see both the request to https://my-domain.com and the error log:

```
fetch('https://my-domain.com')
  .catch(error => {
    logger.error('Request failed. Your error id is ${trace_id here}');
  });
```

How can I get the current trace id and inject it into the log? Do you think I shouldn't be using trace ids for this?

Thanks.

**Comment by amortemousque** [comment]
Hello @luisabtrace,

If you're using the RUM browser SDK, you can use the [beforeSend API](https://docs.datadoghq.com/logs/log_collection/javascript/#advanced-usage) to access the `trace_id`.
```javascript
datadogRum.init({
  ...,
  beforeSend: (event) => {
    if (event.type === "resource" && event.resource.type === "fetch" && event.resource.status_code >= 500) {
      logger.error('Request failed. Your error id is ${event._dd.trace_id}');
    }
  }
})  
```

**Comment by amortemousque** [comment]
I see. For now, this is the only way to get the trace_id but having another API to handle your use case could be considered at some point.

**Comment by hipitihop** [comment]
@amortemousque when using version 4.11.2 of both the rum and logs SDK, I'm seeing `event._dd.trace_id` as undefined. Certainly when `event.type` is one of `view` or `resource` or those from logger itself i.e. there is no `type` property. As a general question, it seems unclear how to access or set trace ids in either SDK, and there also seems no support for spans.
Apologies if this is off topic. Let me know if you prefer a separate issue.

**Comment by bcaudan** [comment]
For the initial question, https://github.com/DataDog/browser-sdk/issues/1061#issuecomment-1363086661 would be the recommended approach.

@hipitihop your topic seems a bit different, please open a separate issue if you still need assistance.
