### ISSUE TITLE
@datadog/browser-rum broken with NextJS in versions >= 4.10.1

### ISSUE THREAD

**Issue by implosivemosaic** [DataDog/browser-sdk#1547]
Minimal reproduction:
https://stackblitz.com/edit/nextjs-cwgzwx?file=pages/_app.js

On initialization an exception is thrown reporting:
```
TypeError: Cannot read properties of undefined (reading 'INTAKE_SITE_US5')
```

See the reproduction above for details.

**Comment by bcaudan** [comment]
Hi @implosivemosaic,

Thanks for raising that!

From first investigations, it seems that it happen only in next.js development mode and related to a dependency loop introduced by browser-sdk@4.10.1 that next.js fails to handle (it is correctly handled by using webpack directly for example).

We'll do a quick fix to solve this one and find a way to detect this kind of situations earlier.
I'll keep you posted.

**Comment by fakhir-shad** [comment]
I am having the same issue with 4.10.2 When new version will be published?

**Comment by bcaudan** [comment]
The issue should be fixed with browser-sdk@4.10.3, let us know otherwise.

**Comment by implosivemosaic** [comment]
That was fast ⚡ thanks! Confirmed that 4.10.3 fixes the problem for me.

**Comment by fakhir-shad** [comment]
I can confirm too. Updating to 4.10.3 fixed the issue. Thanks for putting in a fix like a flash
