### ISSUE TITLE
What is minimum sdk version that I can use? 

### ISSUE THREAD

**Issue by dzienisz** [DataDog/browser-sdk#1548]
What is minimum SDK version that I can use? 

currently my project is using 3.1.2

Do DataDog somehow insist on upgrading to never version? or how to see that something is not working well?

**Comment by amortemousque** [comment]
Hello @dzienisz,
For now, we guarantee backward compatibility with all SDK versions. However, if you want to benefit new features and bug fixes I recommend to be up to date.
To know more about each version you can look at our [changelog](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md)

**Comment by dzienisz** [comment]
yes sure, but for ex is v2 already depreciated? or when v3 will be?

**Comment by amortemousque** [comment]
All versions are officially supported and there is no plan to deprecate old ones.
