### ISSUE TITLE
Cross-Origin Read Blocking (CORB)

### ISSUE THREAD

**Issue by Havunen** [DataDog/browser-sdk#1568]
Hey we are seeing Google chrome reports Cross-Origin Read Blocking messages to console when datadog browser rum is enabled.

Our content security policy header contains: 

```
connect-src: https://*.datadoghq.eu https://rum.browser-intake-datadoghq.eu
```

It fixed the errors but these warnings still exists

![image](https://user-images.githubusercontent.com/2021355/170211883-936423bf-6ca5-4f6c-b0fe-0794a582aa2a.png)

init script:

```js
   const datadogRum = window.DD_RUM;

    datadogRum.init({
        clientToken: datadogClientToken,
        applicationId: datadogApplicationId,
        beforeSend,
        service: 'our-app-name',
        site: 'datadoghq.eu',
        env: ENV,
        version,
        sampleRate: 100,
        replaySampleRate: 0,
        telemetrySampleRate: 0,
        trackInteractions: true,
        useSecureSessionCookie: true, // No RUM events over http,
        allowedTracingOrigins: [window.location.origin] // Connect RUM and traces,restapi is always origin/restapi
    });
```

**Comment by BenoitZugmeyer** [comment]
Hello @Havunen. Thanks for your report. This is a known Chrome issue and it is safe to ignore. Read the documentation [troublshoting section](https://docs.datadoghq.com/real_user_monitoring/browser/troubleshooting/#cross-origin-read-blocking-warning) for more details.
