### ISSUE TITLE
Have `logger.error` entries show up in `RUM - Error Tracking`

### ISSUE THREAD

**Issue by PhilDore11** [DataDog/browser-sdk#1573]
We have both `@datadog/browser-logs` and `@datadog/browser-rum` integrated in our web app and working fine, but noticed that none of the `datadogLogs.logger.error(...)` calls result in entries in `Error Tracking`.

After few tests, we can confirm that `console.error(...)` calls do in fact result in entries in the `RUM - Error Tracking` screen.

**Failed Attempt**

Tried calling `datadogRum` explicitly from the logger's `beforeSend`, to no avail.
```
import { datadogLogs } from '@datadog/browser-logs';
import { datadogRum } from '@datadog/browser-rum';

export function initializeLogger(params) {
  datadogLogs.init({
    ...
    forwardErrorsToLogs: true,
    forwardConsoleLogs: 'all',
    beforeSend: (event: LogsEvent) => {
      if (event.status === 'error') {
        datadogRum.addError(event);
      }
    },
    ...params,
  });
}
```

Any help would be appreciated.

**Comment by PhilDore11** [comment]
**Possible Solution**
Add a `'rum'` handler to also call `datadogRum.addError`

**Comment by BenoitZugmeyer** [comment]
Hello @PhilDore11 and thank you for the report.

I can confirm that Logs are not supported by the Error Tracking product yet. As you suggested, using `datadogRum.addError` would be a good solution. Let me know if you have any concern about this.
