### ISSUE TITLE
Using blob: to load the service worker code is unsafe

### ISSUE THREAD

**Issue by sileht** [DataDog/browser-sdk#1578]
The service worker uses a blob object to load static content.

https://github.com/DataDog/browser-sdk/blob/3a004b2be6d88f0797854be2aaf7b94fec2a06ff/packages/rum/src/domain/segmentCollection/deflateWorker.js#L6

This forces the lib consumer to add `worker-src: blob:` to their CSP header configuration.

Using `blob:` for service worker defeats the purpose of CSP configuration as now any js code can create a service worker on my app with javascript code I can't check the origin, the integrity, etc...

As w3c said `blob:` is like `eval-unsafe` https://www.w3.org/TR/CSP2/#source-list-guid-matching.

Since the javascript code here is static, there is no reason it couldn't be loaded from a static file.

I guess this has been done this way to facilitate the integration with any web application.

But this makes it impossible to use all Datadog products relying on browser-sdk in any web application that has basic security requirements like not allowing `eval-unsafe` or unlike.

I think to please everybody, the lib should at least provide a static file to load or a webpack plugin we can use to generate the service worker file, and anything else that doesn't require to add  `worker-src: blob:` in CSP header.

**Comment by thebrubaker** [comment]
Just wanted to add that what @sileht detailed is worth fixing - hoping your team looks at this lax CSP policy and provides a solution or work around.

If this is solved, it would also be helpful to add it to your documentation at https://docs.datadoghq.com/real_user_monitoring/faq/content_security_policy/#session-replay-worker

**Comment by jeebay** [comment]
@BenoitZugmeyer is this still being considered? This is forcing a conversation with our security team that will make us consider alternatives to DD. 

@sileht have you found a workaround?

**Comment by kwarkjes** [comment]
Any updates on this one? since we are facing the same issue is reported here. We don't feel comfortable allowing `blob:` after all the investment in CSP

**Comment by amortemousque** [comment]
Hello,
This is definitely something we have in mind. It's not in our top priorities right now but it is something that we would want to improve. We will keep you updated.

**Comment by BenoitZugmeyer** [comment]
With the [v4.47.0](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#v4470) release, the RUM SDK now supports an optional `workerUrl` option that you can use to provide a plain URL that will be used to build the Worker instead of a blob URL.

There are some [instructions in the documentation](https://docs.datadoghq.com/integrations/content_security_policy_logs/?tab=firefox#session-replay-worker) to explain how to host and provide the worker URL. As workers need to be hosted at the same origin as the document, we cannot provide a plain `workerUrl` ourselves. Feel free to contact the Datadog support or open an issue if you require further assistance.

**Comment by sileht** [comment]
Thanks a lot!

**Comment by ZebraFlesh** [comment]
> There are some [instructions in the documentation](https://docs.datadoghq.com/integrations/content_security_policy_logs/?tab=firefox#session-replay-worker) to explain how to host and provide the worker URL.

These instructions are pretty obtuse. A working example would go a long way here. I mean, I have no idea what the goal even is here:

> Install the [@datadog/browser-worker NPM package](https://www.npmjs.com/package/@datadog/browser-worker) and use your build tool to include it in the built assets
