### ISSUE TITLE
Can't append user information with `setUser`

### ISSUE THREAD

**Issue by annerajb** [DataDog/browser-sdk#1582]
Right now [setUser](https://github.com/DataDog/browser-sdk/blob/cb1918e8a94a9fdabef9fcc3396a2bd0ddf8ad62/packages/rum-core/src/boot/rumPublicApi.ts#L203)

Does not have an easy way to append data to a user.

What is the recommended way?

**Comment by BenoitZugmeyer** [comment]
There is not, sorry. We'll consider it! Does something like `mergeUser()` would sound good to you?

**Comment by annerajb** [comment]
It does

**Comment by liywjl** [comment]
Hello @annerajb,

We have have as of v4.17.0 added new methods to update the Session User Object. 

You can find these APIs documented [here](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#user-session).

The APIs most relevant to updating specific properties are [`setUserProperty`](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#addoverride-user-session-property) and [`removeUserProperty`](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#remove-user-session-property).

Don't hesitate to open another ticket if you have a specific issue related to the SDK or contact [datadog support](https://www.datadoghq.com/support/) directly.
