### ISSUE TITLE
Sending Network errors, when the flag `forwardErrorsToLogs` is false.

### ISSUE THREAD

**Issue by ntishkevich** [DataDog/browser-sdk#1590]
Hi guys.

I've noticed that amount of network errors has been increased significantly after upgrading `@datadog/browser-logs` to 4.9.0 from 3.7.0. I've checked the init configuration to be sure, that I've disabled forwarding all errors to `DataDog` using the flag `forwardErrorsToLogs` with `false` value. And this flag actually has `false` value, but network errors are still sent to `DataDog` and I'm able to see them in `Log Explorer`.

So I've checked the source code of sdk and this flag is used only for collecting [runtime errors](https://github.com/DataDog/browser-sdk/blob/dca682f599ae86280a1b277851d85c759eed20c5/packages/logs/src/domain/logsCollection/runtimeError/runtimeErrorCollection.ts#L21), but it isn't used for [network errors](https://github.com/DataDog/browser-sdk/blob/9b98fb6fa39c2093fbeec0c85de70d75415cd5ef/packages/logs/src/domain/logsCollection/networkError/networkErrorCollection.ts#L17) and the usage were removed in the PR #1463 (but it is still [disable gathering network errors in the version 4.7.0](https://github.com/DataDog/browser-sdk/blob/3e5bc9cf4a264d90bc39ed0aac257e86f2a096e8/packages/logs/src/boot/startLogs.ts#L66) . 
So I'm curious does this flag still disable gathering network errors anymore? Thanks.

**Comment by amortemousque** [comment]
Hello @ntishkevich,
Thanks for your feedback. You're right, the issue as been introduce by the PR https://github.com/DataDog/browser-sdk/pull/1463. I'll look into it and let you know when a fix is available.

**Comment by ntishkevich** [comment]
> Hi @ntishkevich ,
> The fix is available in @datadog/browser-logs version 4.11.5.
> 
It sounds great! Thank you so much.
