### ISSUE TITLE
Supporting customized view name

### ISSUE THREAD

**Issue by swisscat** [DataDog/browser-sdk#1595]
Dears,

In our use case (web app), the default view tracking mechanism works relatively well.
However, our URL contains unwanted parameters in the path (language / others) that we would like to remove in the view name (e.g resulting in "catalogue" instead of "/s/XXXXX/catalogue".

Is there any plans to support customized view names? It seems the only option would be to manually track views for us. Would you have a recommendation on how to do this best for a website?

Thanks!

**Comment by amortemousque** [comment]
Hello @swisscat,

Like you said, to have curated view names, we recommend [tracking view manually](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#override-default-rum-view-names). If you're using frontend framework,  we recommend using the `startView()` API at the framework router level.

**Comment by swisscat** [comment]
Thanks. I was hoping for something more elegant, as in our case we have no frontend framework and have hence had to replicate the observation logic (for reference for others, here's the logic to replicate: https://github.com/DataDog/browser-sdk/blob/main/packages/rum-core/src/browser/locationChangeObservable.ts)
Moreover, defining the manual view name based on a part of the URL does skip the "automatic id removal" in Datadog back-end.

I would think that it would make sense for non-frameworks to benefit from the automatic grouping of URLs, but this workaround works for us (manually detecting some IDs).
