### ISSUE TITLE
browser-sdk should honor unified tagging

### ISSUE THREAD

**Issue by fredleger** [DataDog/browser-sdk#1611]
Looking at DD docs it seems obvious that unified tagging and DD_* env vars are the way to go for a moderm monitorde app

Digging in browser-sdk code and docs i don't see any way to use DD_ENV, DD_SERVICE, DD_VERSION or similar trricks to avoid duplicating RUM applications and compare 2 versions together.

Did i miss something or is it something that is on the raodmap ?

**Comment by BenoitZugmeyer** [comment]
Hello,
The Browser SDK cannot read environment variables. You are responsible to pass `env` `service` and `version` to the Browser SDK when initializing it. You can tweak your build tool configuration to embed some environment variables in your JS bundle (ex: use the [Webpack `EnvironmentPlugin`](https://webpack.js.org/plugins/environment-plugin/))
Would that work for you?
