### ISSUE TITLE
Any way to ignore errors?

### ISSUE THREAD

**Issue by csantos1113** [DataDog/browser-sdk#1616]
Sometimes there are errors we don't want to track because they are benign (for example: https://github.com/WICG/resize-observer/issues/38#issuecomment-422126006 `"ResizeObserver loop limit exceeded"`)

Is there a way to ignore errors like Sentry does it? https://docs.sentry.io/clients/javascript/config/ 

> `ignoreErrors`
> Very often, you will come across specific errors that are a result of something other than your application, or errors that you’re completely not interested in. ignoreErrors is a list of these messages to be filtered out before being sent to Sentry as either regular expressions or strings. When using strings, they’ll partially match the messages, so if you need to achieve an exact match, use RegExp patterns instead.

**Comment by BenoitZugmeyer** [comment]
You can achieve this with the `beforeSend` initialization parameter. There is an example to do just that [in our documentation](https://docs.datadoghq.com/real_user_monitoring/guide/enrich-and-control-rum-data/?tabs=event#discard-a-frontend-error).
