### ISSUE TITLE
Object literal may only specify known properties, and 'premiumSampleRate' does not exist in type 'RumInitConfiguration'.

### ISSUE THREAD

**Issue by leonardoluan** [DataDog/browser-sdk#1628]
In the rum documentation it is informed to insert the premiumSampleRate but when inserting the TypeScript it informs that the property does not exist
![image](https://user-images.githubusercontent.com/35734728/177212492-26d07862-3b4b-4085-8daf-0623ce9f8ea6.png)

package.json: 
`"@datadog/browser-rum": "^4.14.0",
`
yarn.lock:
```
"@datadog/browser-core@4.14.0":
  version "4.14.0"
"@datadog/browser-rum-core@4.14.0":
  version "4.14.0"
  dependencies:
    "@datadog/browser-core" "4.14.0"

"@datadog/browser-rum@^4.14.0":
  version "4.14.0"
  dependencies:
    "@datadog/browser-core" "4.14.0"
    "@datadog/browser-rum-core" "4.14.0"`
```

**Comment by BenoitZugmeyer** [comment]
The property exists, though: https://github.com/DataDog/browser-sdk/blob/v4.14.0/packages/rum-core/src/domain/configuration.ts#L17

If you just updated the `@datadog/` packages, maybe try restarting your editor, so typechecking starts on a fresh state?

**Comment by BenoitZugmeyer** [comment]
I take the ❤️ emoji as an indication that the issue was solved 😄
