### ISSUE TITLE
Support W3C tracing headers

### ISSUE THREAD

**Issue by jtart** [DataDog/browser-sdk#1639]
Currently this lib supports and sends `x-datadog-` http headers for sampling traces, it would be great to support `traceparent` one, which is inherited from the W3C RFC: https://www.w3.org/TR/trace-context/#traceparent-header.

**Comment by bcaudan** [comment]
Hi @jtart,

We definitely plan to support w3c tracing headers at some point but it is not in our current priorities.
I'll notify here when we will make progress on this front.

**Comment by johnkors** [comment]
Subscribe.

**Comment by yannickadam** [comment]
Hi! OpenTelemetry headers are now available with support for `tracecontext`, `b3` and `b3multi`.
They can be enabled through the new `allowedTracingUrls` configuration parameter.

You can find documentation about it here: https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=browserrum#usage
