### ISSUE TITLE
Establish peer dependency between rum and logs packages?

### ISSUE THREAD

**Issue by agrobbin** [DataDog/browser-sdk#1666]
I'm curious if there is appetite for (or a specific reason for not) establishing a peer dependency between the rum and logs packages. It'd be nice to tell NPM/Yarn that if `@datadog/rum` is at 4.16.0, `@datadog/logs` also must be at 4.16.0 (if present), and vice versa. Luckily, [`peerDependencies`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies) does the trick for us.

Considering the RUM docs ([here](https://docs.datadoghq.com/real_user_monitoring/browser/#choose-the-right-installation-method) and [here](https://docs.datadoghq.com/logs/log_collection/javascript/#choose-the-right-installation-method)) state that it is recommended to match versions, this seems like a beneficial addition! I also believe (though I'm having a hard time fully parsing the [Dependabot](https://github.com/dependabot/dependabot-core) source to be sure) it will force Dependabot to update both `@datadog/rum` and `@datadog/logs` in tandem if both are included dependencies of a project.

I would love to hear thoughts on this option!

**Comment by BenoitZugmeyer** [comment]
This is a good idea, thank you for bringing it up! We'll work on it.
