### ISSUE TITLE
setUser info not sent with logs

### ISSUE THREAD

**Issue by hipitihop** [DataDog/browser-sdk#1675]
We use the RUM `setUser` and see correctly tagged RUM events including manual view changes, actions etc. However anything that goes via the `DD_LOGS.logger` fns like info, log, warn, do not include the user info. Is this an oversight that is being worked on ? or do we need to manually add the attributes e.g. `usr.id` and `user.name` to our logger payload ?

**Comment by BenoitZugmeyer** [comment]
Hello @hipitihop,
To be consistend with RUM, we'll add a `setUser` API to Logs! In the meantime, you can use `DD_LOGS.addLoggerGlobalContext('usr', { ... })` to achieve the same result.

Bear in mind that the RUM and Logs SDKs are independent and you would have to set the user on both.

**Comment by hipitihop** [comment]
> Hello @hipitihop,
> 
> To be consistend with RUM, we'll add a `setUser` API to Logs! In the meantime, you can use `DD_LOGS.addLoggerGlobalContext('usr', { ... })` to achieve the same result.
> 
> Bear in mind that the RUM and Logs SDKs are independent and you would have to set the user on both.

Hi @BenoitZugmeyer thanks. Does 14.7.x address this ? namely https://github.com/DataDog/browser-sdk/pull/1641 ?

**Comment by BenoitZugmeyer** [comment]
No, implementing `setUser` on logs is still in our backlog.

**Comment by yannickadam** [comment]
Hi!
This feature is available with SDK 14.24.0.
Feel free to open another issue if you experience any problem when using it.
