### ISSUE TITLE
Server Timing missing on beforeSend context in Safari

### ISSUE THREAD

**Issue by quinnlangille** [DataDog/browser-sdk#1679]
Hi all,

I'm working on an investigation for an image cache we're using, and have the following `beforeSend` function:

```typescript
DD_RUM.init({
   beforeSend: (event, context) => {
      if (event.type === 'resource' && event.resource.type === 'image') {
          const imageCache = context.performanceEntry.serverTiming.find(
            st => st.name === 'fastly'
          );
          event.context = {...event.context, imageCache }
      }
  },
})
```

This should send me sever timing, plus hit/miss from fastly. The entry for server timing looks something like `fastly;dur=1;start=2022-08-04T15:49:12.380Z;desc=hit,rtt;dur=35`.

I can see this `server-timing` header come back on the response in chrome and safari, but only in chrome is `context.performanceEntry.serverTiming` defined—it's null in safari.

Any idea what might be the issue here?

**Comment by BenoitZugmeyer** [comment]
Hi! It looks like Safari does not implement it yet: https://caniuse.com/mdn-api_performanceresourcetiming_servertiming
