### ISSUE TITLE
Connecting RUM with Traces, can't see traces from RUM application

### ISSUE THREAD

**Issue by Oghenebrume50** [DataDog/browser-sdk#1681]
Hi, I am trying to connect Datadog RUM setup on a SPA React frontend to the APM traces setup on another application(backend Ruby on Rails app). Basicallyt I want to get traces of graphql calls made from the frontend. 

I have properly setup and initialized RUM on my React app like this. 

```
datadogRum.init({
  applicationId: 'xxxxxxxxxxxxxxx',
  clientToken: ''xxxxxxxxxxxxxxx'',
  site: 'datadoghq.com',
  service: 'order',
  // Specify a version number to identify the deployed version of your application in Datadog
  // version: '1.0.0',
  sampleRate: 100,
  premiumSampleRate: 100,
  trackInteractions: true,
  defaultPrivacyLevel: 'mask-user-input',
  allowedTracingOrigins: [/https:\/\/(?:api|app)\.example\.(?:cc|com|dev)/],
})
datadogRum.startSessionReplayRecording()
```

and I have tracing setup on the domain app.example.com and also in my local app.example.dev but I cannot see the trace from the RUM application. I see the graphql request trace on the APM service but not on the RUM application. I am not sure what to do I have been long on this issue. 

I have also allowed all headers in my Ruby app 
  ```
allow do
    origins /(?:http|https):\/\/(?:.*):\d{4}.*/

    resource '/graphql',
             headers: :any,
             methods: %w[options post],
             credentials: true
  end
```

Any idea what I am doing wrong?

**Comment by bcaudan** [comment]
Hi @Oghenebrume50,

There is a known [graphql issue](https://github.com/apollographql/apollo-client/issues/7130) that prevent the SDK to instrument graphql calls, so we can't collect related RUM events or add frontend context to the backend traces.
One way to solve this issue is to ensure that the SDK is initialized before graphql is executed.

In order to be sure that this is the issue you are facing, does it work correctly for requests that are not made by graphql?

**Comment by Oghenebrume50** [comment]
@bcaudan   No it doesn't work for any request, in the resources tab for a page view both  XHR and Fetch requests are empty

**Comment by bcaudan** [comment]
What do you mean by XHR and Fetch requests are empty?

**Comment by Oghenebrume50** [comment]
<img width="1014" alt="Screenshot 2022-08-08 at 10 09 06" src="https://user-images.githubusercontent.com/37092867/183382622-f07ecc6b-b900-4998-a7a7-0a81676236da.png">

This

**Comment by bcaudan** [comment]
OK, can you reach out to [datadog support](https://www.datadoghq.com/support/)? It will be easier to provide information on you app and continue the investigation.

**Comment by Oghenebrume50** [comment]
Alright I will thank you

**Comment by ralphstodomingo** [comment]
Mind leaving notes here what causes the logs/RUM-to-trace connection to be missing? Facing a similar issue on our end.

**Comment by Oghenebrume50** [comment]
> Mind leaving notes here what causes the logs/RUM-to-trace connection to be missing? Facing a similar issue on our end.

So sorry but I really do not know, I fixed it without having to message support
