### ISSUE TITLE
`beforeSend` not working as expected

### ISSUE THREAD

**Issue by jamestowers** [DataDog/browser-sdk#1718]
We are experimenting with filtering out events and although this seems to work when we check for specific conditions, I'm currently attempting to filter ALL events until a specific cookie has been accepted.

I'd expect the below to not send _any_ data but we are instead seeing requests to browser-intake endpoint, is that expected?

We are using v4.15.0

```ts
datadogRum.init({
      ...
      beforeSend: (event, context) => {
        return false;
      },
    });
  }
```

**Comment by BenoitZugmeyer** [comment]
Yes it's expected, RUM Views can't be filtered because they are the bedrock of all other data.

You should call `datadogRum.init()` only when the condition is rearched instead. Note that you can use other `datadogRum.*` methods before `init()` is called.
