### ISSUE TITLE
View name and service going back to default after startView

### ISSUE THREAD

**Issue by lucashm** [DataDog/browser-sdk#1727]
I'm working on a micro-frontend application, and I'm having the following issue: After changing the view using `datadogRum.startView`, the view gets updated but it goes back to default from time to time.

```typescript
    afterMount: async (app) => {
      if (app.name === Constants.CONTAINERIZED_APP_NAMES.PLATFORM_TOPBAR_FE) {
        return null;
      }
      console.log('setting view', 'my-service-name');
      datadogRum.startView({ name: 'my-service-name', service: 'my-service-name' });
      datadogRum.setGlobalContext({ name: 'my-service-name', service: 'my-service-name' });
      return null;
    }
```
Note that I also set the global context here

```typescript
  datadogRum.init({
    applicationId: process.env.DATADOG_APP_ID,
    clientToken: process.env.DATADOG_CLIENT_TOKEN,
    site: process.env.DATADOG_SITE,
    service: 'default',
    env: process.env.NODE_ENV,
    sampleRate: 100,
    premiumSampleRate: 100,
    trackInteractions: true,
    defaultPrivacyLevel: 'mask-user-input',
    beforeSend: (event, context) => {
      console.log('before send!');
      console.log('event.view.name, event.service, event.context.service');
      console.log(event.view.name, event.service, event.context.service);
      const user = JSON.parse(localStorage.getItem('lscache-currentUser') ?? '{"organizationId": ""}');
      event.context = { ...event.context, user };
      if (event.type === 'resource' && event.resource.status_code >= 400 && event.resource.type === 'xhr') {
        event.context = {
          ...event.context,
          error_response: (context as any).xhr.response,
          url: window.location.href,
          organization_id: user.organizationId,
        };
        console.log('sending error to -> ', event.view.name);
      }
    },
  });
```

Then in the console:
![image](https://user-images.githubusercontent.com/16053704/189192305-d70f3fb2-3153-4014-80bb-77d3f55227d0.png)

This is not something that happens only at the start, even without changing between microfrontends, the view keeps changing between `my-service-name` to `undefined`. Note that this is the only place in the code where I call `startView`, and from the logs it seems that it's being called only once too (since I'm not changing between microfrontends).

I haven't tried on a fresh app (maybe there's something specifically on this application that's causing this issue?), but I might do it so  I can give you something to test yourselves

**Comment by lucashm** [comment]
After some further tests, enabling `trackViewsManually` solved my issue! My bad for skipping some of the documentation...
The view and the service were changing every time I switched to another route. It makes sense to change the view, but not so sure about changing the service as well!

One minor detail though is regarding the startup... With `trackViewsManually` disabled there's a lot of view changes, while when it's turned on, it looks way smoother:

- `trackViewsManually` disabled
![image](https://user-images.githubusercontent.com/16053704/189221888-3a788e90-9d90-4a4e-8a59-c42015723e66.png)

- `trackViewsManually` enabled
![image](https://user-images.githubusercontent.com/16053704/189222055-cc315c41-cb9e-4e78-9ea2-386b07d1266a.png)

Example available here (switching trackViewsManually between enabled/disabled will give you similar results to the images above): https://github.com/lucashm/ddrum-test

**Comment by bcaudan** [comment]
Hello @lucashm,

What is your suggestion?

**Comment by lucashm** [comment]
It would be to not change the service when switching between routes, just the view name
