### ISSUE TITLE
Dashboard global time is not working correctly

### ISSUE THREAD

**Issue by dzienisz** [DataDog/browser-sdk#1733]
When you create custom dashboard and set time to "global time" it's not working when you change global time.

**Comment by liywjl** [comment]
Hello @dzienisz,

You might be able to get some help regarding that issue via the support team; you can contact them here: https://www.datadoghq.com/support/

If there is anything relating to the Browser SDK, feel free to open a new issue here.

**Comment by dzienisz** [comment]
it's working right now
