### ISSUE TITLE
Url masking 

### ISSUE THREAD

**Issue by Ayushi-Sama** [DataDog/browser-sdk#1758]
I want to mask url  ....it is showing in url_path in attributes. 

It is app/accounts/18903620189/...
It should rather bs app/accounts/?     Or anything ...number shouldn't be shown 

Kindly help

**Comment by ayushisama** [comment]
Even after doing this...in Attributes -> view -> url_path it is showing 

/app/accounts/21329304823/view-bill (example)

**Comment by Ayushi-Sama** [comment]
Even after doing this...in Attributes -> view -> url_path it is showing

/app/accounts/21329304823/view-bill (example)

**Comment by liywjl** [comment]
Hello @Ayushi-Sama 

I will reopen this thread, its probably easier for us to keep all the comments here.

Regarding your issue mentioned here: https://github.com/DataDog/browser-sdk/issues/1761#issue-1400621391

I have updated the example as to not cut off what is followed by the URL:
```
window.DD_RUM &&
    window.DD_RUM.init({
        ...,
        beforeSend: (event) => {
            // remove email from view url
            event.view.url = event.view.url.replace(/accounts\/[^&]*^/, "accounts/REDACTED")
        },
        ...
    });
```

You can modify the [Regex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) pattern to change the behaviour of what you match. In the case above I am matching any string after `accounts/`.

Hope this helps. If this has resolved your issue feel free to close the issue.

**Comment by Ayushi-Sama** [comment]
But account number is still coming after /accounts ...Nothing changed
             /app/accounts/21329304823/view-bill (example)

Can you please check with issue #1762 as well.

**Comment by liywjl** [comment]
Yes in fact the example I shared did not work correctly for you case. Sorry about that, here is an updated example:

```
window.DD_RUM &&
    window.DD_RUM.init({
        ...,
        beforeSend: (event) => {
            // remove email from view url
            event.view.url = event.view.url.replace(/accounts\/[^&\/]*/, "accounts/REDACTED")
        },
        ...
    });
```

I find [Regex101](https://regex101.com/) a useful tool when testing out regex.

**Comment by Ayushi-Sama** [comment]
I tried different regex but still account number comes up. 
Is it possible to mask it in URL_path

**Comment by liywjl** [comment]
Hello @Ayushi-Sama,

I was curious to know if you have any update on this? 

I was also hoping on getting some clarification on what your objective is with the `URL_path`. Your original comment you showed 2 examples:

`app/accounts/18903620189/...`
`app/accounts/?`

Furthermore you mentioned that you wanted to hide the number in the URL.

As I mentioned in previous comment you can use the `beforeSend` method and replace your matched string with `REDACTED` to anonymous.

However in your example `app/accounts/?`, it seem that you might be referring to grouping. When you send RUM events, we process it on the server and try to detect keys like `18903620189` and covert them into searchable elements by replacing the keys like `18903620189` into `?`.

This allows you to be able to search through multiple different events regardless of the exact ID (in this case user account IDs).

I am not sure if this clarifies your question?

**Comment by Ayushi-Sama** [comment]
it was like in resources I could see account number like
app/accounts/18903620189/...

But I didn't wish to send my account number alongwith this URL
I tried beforeSend redacted method using regex (many different types) but it still just shows up.

Also if you could just tell me if there is a way to mask dropdown data ?
