### ISSUE TITLE
URL Masking 

### ISSUE THREAD

**Issue by Ayushi-Sama** [DataDog/browser-sdk#1761]
I want to mask url ....it is showing in url_path in attributes.

It shows: /app/accounts/21329304823/view-bill 
It should be : /app/accounts/?/view-bill 

Even after doing this (below mentioned) , it is still same as above one.

datadogRum.init({
        beforeSend: (event) => {
            event.view.url = event.view.url.replace(/accounts\/[^&]*/, "accounts/REDACTED")
        }
    });

Kindly assist me on this one .

**Comment by liywjl** [comment]
closing in favour of https://github.com/DataDog/browser-sdk/issues/1758
