### ISSUE TITLE
Data Masking 

### ISSUE THREAD

**Issue by Ayushi-Sama** [DataDog/browser-sdk#1762]
If we mask first and last name by doing data-di-mask 
Then in any way is this masked data being sent to Datadog as attributes or something ??
i.e Datadog recieves first name and last name as it is ??

**Comment by liywjl** [comment]
If you do any masking of data in the `beforeSend`, Datadog will only receive that masked data.

Does this answer your question?

**Comment by Ayushi-Sama** [comment]
I am setting it in the template file itself ,  Can you please share a reference of how to send data in beforeSend !!

**Comment by Ayushi-Sama** [comment]
I meant by masking in beforeSend ....how can we do that ?

**Comment by liywjl** [comment]
`beforeSend` is present on both RUM SDK and Logs SDK method that will allow you to mask data. The `beforeSend` gives you access to 2 parameters: `event` and `context`. I assume you are likely trying to mask data in the `event` parameter. It might be easiest to `console.log(event)` in the `beforeSend` to find the data you wish to modify. From there you can modify the data to anonymous it. Converting strings to 'REDACTED' will indicate to Datadog that this has been masked.

For RUM this is documented [here](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#enrich-rum-events)

For Logs this is documented [here](https://docs.datadoghq.com/logs/log_collection/javascript/#scrub-sensitive-data-from-your-browser-logs)

Here is an example from the Logs documentation where `log.someKey` has been replaced to `REDACTED`.
```
import { datadogLogs } from '@datadog/browser-logs'

datadogLogs.init({
    ...,
    beforeSend: (log) => {
        if(log.someKey) {
            log.someKey = "REDACTED"
        }
    },
    ...
});```

**Comment by Ayushi-Sama** [comment]
Do our personalized data/token gets captured by datadog before/after masking ?

Before mask: what is sending as part of datadog request -> any personalised data/token.

**Comment by liywjl** [comment]
> Do our personalized data/token gets captured by datadog before/after masking ?

All changes done in the `beforeSend` are done client side and therefore the original data is not sent off to Datadog servers.

**Comment by Ayushi-Sama** [comment]
But how we can give token in beforeSend ?

**Comment by liywjl** [comment]
Sorry I don't think I fully understand. What do you mean by token? Also what kind of event/log are you referring to?

**Comment by liywjl** [comment]
You can refer to a variable outside of `beforeSend`
```
import { datadogLogs } from '@datadog/browser-logs'

const token = 'token'

datadogLogs.init({
    ...,
    beforeSend: (log) => {
        log.token = token
    },
    ...
});```

**Comment by Ayushi-Sama** [comment]
With token ..I meant like when we authenticate with a username and password a token is generated , that shouldn't be sent to datadog

I am using rum , not logs . So examples with rum would be more appreciated .

**Comment by liywjl** [comment]
We do not collect payloads from `fetch`/`XHR` requests, thus not exposing auth tokens to Datadog

**Comment by amortemousque** [comment]
Hello @Ayushi-Sama,

Did we answer your question?

**Comment by Ayushi-Sama** [comment]
I some places I could find token being sent in Resource URL !!
