### ISSUE TITLE
RUM for error tracking only

### ISSUE THREAD

**Issue by tleunen** [DataDog/browser-sdk#1765]
What's the best way to use RUM for error tracking only, without the session tracking and other stuff?

I've tried to remove the sample rate on everything else, but no events are sent when I do that. Does that mean it's impossible to use RUM only for error tracking and we must use the rest?

```
telemetrySampleRate: 0,
tracingSampleRate: 0,
sessionReplaySampleRate: 0,
sampleRate: 0,
```

Implementing error tracking within Datadog Logs, [as suggested here](https://github.com/DataDog/browser-sdk/issues/703#issuecomment-767414446) would definitely be ideal for my usecase.

**Comment by amortemousque** [comment]
Hello @tleunen,

Yes, you must use the rest in order for error tracking to work. You can find the documentation of every RUM initialization parameters [here](https://docs.datadoghq.com/real_user_monitoring/browser/#initialization-parameters).

**Comment by tleunen** [comment]
Thank you @amortemousque !
