### ISSUE TITLE
I want to exclude some API call from the loading time.

### ISSUE THREAD

**Issue by amortemousque** [DataDog/browser-sdk#1766]
I want to exclude some API call from the loading time.
In my case, I request a cms content at beginning, but this cms content is not necessary for first page, just like a prefetching, how do I deal this case?

_Originally posted by @cjz9032 in https://github.com/DataDog/browser-sdk/issues/639#issuecomment-1277189706_

**Comment by amortemousque** [comment]
Hello [cjz9032](https://github.com/cjz9032),

I think what you're looking for is [how page activity is calculated](https://docs.datadoghq.com/real_user_monitoring/browser/monitoring_page_performance/#how-page-activity-is-calculated).

**Comment by cjz9032** [comment]
> Hello [cjz9032](https://github.com/cjz9032),
> 
> I think what you're looking for is [how page activity is calculated](https://docs.datadoghq.com/real_user_monitoring/browser/monitoring_page_performance/#how-page-activity-is-calculated).

OH bro, thanks, it works, your answer save my time!

**Comment by KiranUppunda** [comment]
Hi @amortemousque , @cjz9032  , I am trying to with ```excludedActivityUrls``` already. 

But in my case I have few dynamic urls.

For example: 
```https://cdn-url/agent/<--id-->/abc```
```https://some-end-point/url?dynamic_params```
```https://endpoint/<id>```

As per this one,  I guess we will have to add the exact URL or ending url, [how page activity is calculated](https://docs.datadoghq.com/real_user_monitoring/browser/monitoring_page_performance/#how-page-activity-is-calculated).
So if it is dynamically coming, how can we restrict it ?

Thank you.
