### ISSUE TITLE
Dropdown Masking

### ISSUE THREAD

**Issue by Ayushi-Sama** [DataDog/browser-sdk#1769]
Is it possible to mask dropdown in Datadog ?

**Comment by BenoitZugmeyer** [comment]
👋  Are you talking about session replay? You can mask any element by using `data-dd-privacy="hidden"` attribute. See [documentation](https://docs.datadoghq.com/real_user_monitoring/session_replay/privacy_options/?tab=maskuserinput#completely-hide-an-element).
