### ISSUE TITLE
Command failed in puppeteer - The chromium binary is not available for arm64

### ISSUE THREAD

**Issue by beccajellinek** [DataDog/browser-sdk#1772]
I'm following the installation instructions so I can track user actions locally. I'm using an M1 Mac. During `yarn` process I receive the following error: 

> error /Users/rebecca.jellinek/dev/browser-sdk/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/rebecca.jellinek/dev/browser-sdk/node_modules/puppeteer
Output:
The chromium binary is not available for arm64.

I've tried installing chromium directly via homebrew but that leads me to another error:

> Error: Cask 'chromium' does not have a sha256 checksum defined and was not installed.
This means you have the --require-sha option set, perhaps in your HOMEBREW_CASK_OPTS.

From what I've read online, this could be mitigated by changing the dockerfile. I'm hesitant to make changes but could raise a PR if we find something that works.

**Comment by BenoitZugmeyer** [comment]
I think we should update our puppeteer dependency to support M1 macs (cf [this comment from puppeteer contributor](https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-906476717))

In the meantime using chromium from brew is the workaround (cf [this blog post](https://linguinecode.com/post/how-to-fix-m1-mac-puppeteer-chromium-arm64-bug)). I have no idea why brew is failing to install chromium in your case. Editing the [Dockerfile](https://github.com/DataDog/browser-sdk/blob/main/Dockerfile) won't probably fix it, as it has nothing to do with local development or puppeteer.

**Comment by bcaudan** [comment]
I had the same issue with chromium from brew but manage to bypass the install error by only putting this variable in my env:

```bash
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
```

**Comment by write2aj** [comment]
You could try installing chromium using brew. 
For my Mac M1 with `macOS 12.6` it got installed using the below command.
`brew install chromium --no-quarantine` and installed it at - `/opt/homebrew/bin/chromium`. It has the Chromium app in Applications folder as well.

**Note** - without the `--no-quarantine` MacOS's Gatekeeper prevents the command from completing the install correctly.

Hope this helps.

**Comment by bcaudan** [comment]
Should be fixed by #1843, feel free to re-open otherwise.
