### ISSUE TITLE
DataDog RUM and electron error

### ISSUE THREAD

**Issue by felixpro** [DataDog/browser-sdk#1776]
Datadog rum works fine in development, but it doesn't work after I build the app in electron. I don't get any logs. 

This is the error from my console when the app it's builded: 

![error electron](https://user-images.githubusercontent.com/42367473/196304718-56ee163d-2f83-466e-849e-d3278ebf6797.png)

**Comment by bcaudan** [comment]
Hello @felixpro, 

Indeed, browser-rum sdk don't support electron environment as it does not allow us to set cookies to track the session.
You can find similar issues for other web environments that are not supported:  https://github.com/DataDog/browser-sdk/labels/use-case%2FSession%20without%20cookie.

Electron support is something that we would want to have in the fulness of time but it is not in our current priorities.
We will let you know here if there are some progress on this front.

**nb:** I've removed your setup screenshot showing your application id and client token, even if it meant to be used publicly, no need to expose this data.

**Comment by felixpro** [comment]
> Hello @felixpro,
> 
> Indeed, browser-rum sdk don't support electron environment as it does not allow us to set cookies to track the session. You can find similar issues for other web environments that are not supported: [ use-case/Session without cookie](https://github.com/DataDog/browser-sdk/labels/use-case%2FSession%20without%20cookie) .
> 
> Electron support is something that we would want to have in the fulness of time but it is not in our current priorities. We will let you know here if there are some progress on this front.
> 
> **nb:** I've removed your setup screenshot showing your application id and client token, even if it meant to be used publicly, no need to expose this data.

Thank you, if I'm able to get the session information from my main process `main.js` is it possible to manually send the session information to DataDog? 

There's a way to set the cookies from the rendered process. If datalog has a way to manually allow me to add this would be awesome.

**Comment by bcaudan** [comment]
> Thank you, if I'm able to get the session information from my main process main.js is it possible to manually send the session information to DataDog?

We don't have such capability for now.

**Comment by mberrg** [comment]
Any update on electron support?

**Comment by mberrg** [comment]
> Any update on electron support?

I tested now, and it seems to work in electron 22 :-)

**Comment by mberrg** [comment]
I've found solution. The problem is that in production the electron is serving from file, and chrome does not support cookies when serving files. So the solution is to fork a local webserver that is serving the files.

e.g. in electron-main.js:
```
 if (process.env.DEBUGGING) {
    mainWindow.loadURL(process.env.APP_URL);
  } else {
    fork(path.join(__dirname, '/server.js'), {
      env: { APP_URL: process.env.APP_URL },
    });
    mainWindow.loadURL('http://localhost:9090');
  }
```
Then add a server.js:
```
const handler = require('serve-handler');
const http = require('http');
const path = require('path');
const publicFolder = path.join(__dirname);

const server = http.createServer((request, response) => {
  // You pass two more arguments for config and middleware
  // More details here: https://github.com/vercel/serve-handler#options
  return handler(request, response, {
    directoryListing: false,
    public: publicFolder,
    cleanUrls: true,
    // remove unwanted files or folders (these are inside app.asar)
    unlisted: [   
      'node_modules',
      '.npmrc',
      '.yarnrc',
      'server.js',
      'electron-main.js',
      'electron-preload.js',
      'package.json',
    ],
  });
});

server.listen(9090, '127.0.0.1', () => {
  console.log('Running at http://localhost:9090');
});
```

However a better solution is if Datadog rum could instead use locale storage and headers to transmit user sessions.

**Comment by felixpro** [comment]
> mberrg

Thank you! I'll try this option.

**Comment by felixpro** [comment]
Hi [mberrg](https://github.com/mberrg) thank you for this solution. It's not working for me, it's there any other extra configuration I should do? Or do you have a Github project configured with this solution that I can have a look at? Thank you so much.

**Comment by felixpro** [comment]
I see we have it now https://docs.datadoghq.com/real_user_monitoring/guide/monitor-electron-applications-using-browser-sdk/

**Comment by yannickadam** [comment]
Hi all,

As noted by @felixpro, the browser SDK can now be initialised in environments where cookies are not supported by setting the initialization parameter allowFallbackToLocalStorage: true. (See [documentation here](https://docs.datadoghq.com/real_user_monitoring/browser/#initialization-parameters))
