### ISSUE TITLE
🐛 why startSessionReplayRecording is not working ??

### ISSUE THREAD

**Issue by ys-zhifu** [DataDog/browser-sdk#1784]
**Describe the bug**

`datadogRum.startSessionReplayRecording()`  and I didn't see the upload media

**To Reproduce**

1. install `"@datadog/browser-rum": "^4.22.0"`
2. datadogRum.init({})
3. datadogRum.startSessionReplayRecording()
4. View the network, only RUM reports can be seen, no file upload

**Expected behavior**
`datadogRum.startSessionReplayRecording()` is working and file upload

**Comment by bcaudan** [comment]
Hi @ys-zhifu,

> datadogRum.startSessionReplayRecording() and I didn't see the upload media
> View the network, only RUM reports can be seen, no file upload

If I understand correctly, in the network panel of your browser debugger, you are seeing requests to `rum.browser-intake-datadoghq.com` but not request to `session-replay.browser-intake-datadoghq.com`, is that right?

By reproducing your steps in a blank app:

```js
datadogRum.init({})
datadogRum.startSessionReplayRecording()
```

I see a console error since some parameters are required.

Instead with:

```js
datadogRum.init({
    applicationId: 'xxx',
    clientToken: 'yyy',
})
datadogRum.startSessionReplayRecording()
``` 

After the loading the page and waiting 30s, you should see requests to both domains.

**Comment by ys-zhifu** [comment]
![image](https://user-images.githubusercontent.com/105471350/197439573-ee8b86c2-0086-419f-b18d-0fd86d94e0e5.png)
![image](https://user-images.githubusercontent.com/105471350/197439713-0e167a13-54c3-40c0-8459-5c74a9aaac4c.png)

In case, only has 4 RUM requests, no requests to session-replay.browser-intake-datadoghq.com.

**Comment by ys-zhifu** [comment]
Hi @bcaudan 

I adjusted the configuration, but it didn't work

![image](https://user-images.githubusercontent.com/105471350/197506360-64699577-fbbb-4542-9f1d-bb8087522c69.png)
![image](https://user-images.githubusercontent.com/105471350/197506457-49885696-d7c7-46fc-a2ca-b9e748329033.png)

**Comment by bcaudan** [comment]
I can't reproduce the behavior you experience with a [simple app](https://codesandbox.io/s/simple-datadog-rum-integration-ufs2m4).

 could you share with us a minimal setup reproducing your issue?

**Comment by ys-zhifu** [comment]
Hi @bcaudan , thank you for answering my question, the problem has been solved. 

The reason for this problem is that `sessionReplaySampleRate: 20`, after I adjust the value, I need to clear the cookie, otherwise the sessionReplay will not take effect.

I thought that `sessionReplaySampleRate` was the transmission ratio of each session, but unexpectedly, it was the transmission ratio of the whole session.

A new discovery, session replay by_ dd_ S cookie's rum decision. If it is rum=1, it will be sent, otherwise it will not be sent.

![image](https://user-images.githubusercontent.com/105471350/197675206-10d6d297-fecf-47fd-a3e7-eac613537b3c.png)

**Comment by bcaudan** [comment]
Hi @ys-zhifu,

`sessionReplaySampleRate` is used at the beginning of the session to determine if the session will track session replay data.
Then the track session replay data or not information is stored in the cookie in order to be consistent during the session.

All good with this issue then?
