### ISSUE TITLE
Checkbox is seen as ticked in session replay

### ISSUE THREAD

**Issue by Ayushi-Sama** [DataDog/browser-sdk#1785]
I have a login page where we login by username and password and there is a checkbox for Remember Me 
Even if the checkbox is checked or unchecked it shows as checked in Datadog session replay. 
Is there be any way it can be masked or seen as it is in the page .

**Comment by BenoitZugmeyer** [comment]
👋 If you are using a `defaultPrivacyLevel: "mask-user-input"` (the default) or `defaultPrivacyLevel: "mask"`, checkboxes state are not recorded to protect privacy. To record the checkbox state, you should use the `data-dd-privacy="allow"` attribute on the checkbox or any of its ancestor element. See [documentation](https://docs.datadoghq.com/real_user_monitoring/session_replay/privacy_options/?tab=maskuserinput#override-an-html-element).
