### ISSUE TITLE
💡  Path customization for distributed tracing

### ISSUE THREAD

**Issue by mortargrind** [DataDog/browser-sdk#1823]
**Is your feature request related to a problem? Please describe.**
I have a lot of endpoints that are under the same domain. I don't want to track all of them. Current allowed `allowedTracingOrigins` configuration is an all-in solution that forces me to track every request that I have for each different microservice that I am consuming.

**Describe the solution you'd like**
I would like this option to be renamed and reworked something like `allowedTracingUrls` and extend the alternative "matcher" function to receive things like the full request URL so I can make the tracing decision on a more granular level. 

**Describe alternatives you've considered**
I don't see much alternative to "not restricting distributed tracing per origin", but open to suggestions of course. I can open a PR if needed but first wanted to make sure if this is a feature to be added and what needs to be changed.

**Comment by BenoitZugmeyer** [comment]
Thank you for your feedback. This has recently been discussed in #1818. We agreed to implement `allowedTracingUrls` and deprecate `allowedTracingOrigin` in the future. We'll keep you posted on this change updates.

**Comment by mortargrind** [comment]
Ah sorry, didn't see that. Thanks!

**Comment by yannickadam** [comment]
Hi! `allowedTracingUrls` is now available.
You can find documentation about it here: https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=browserrum#usage
