### ISSUE TITLE
🐛 Logs aren't sent to console unless datadogLogs.init is called first (new behaviour since 4.9.0)

### ISSUE THREAD

**Issue by timabb031** [DataDog/browser-sdk#1841]
**Describe the bug**
When using `datadogLogs.logger.setHandler("console")` without first calling `datadogLogs.init(...)`, no messages are logged to the console when calling `datadogLogs.logger.info("test info");`.  Prior to 4.0.9 this worked fine, but it doesn't appear to work in any version since.

See the block of code below for an example.  Basically it will call `datadogLogs.init` when running in staging/production, so that logs are sent to Datadog.  For local development I don't want to send logs to Datadog so the code will just write to the console instead.

**To Reproduce**
```
import { datadogLogs } from "@datadog/browser-logs";

// assume this value is empty for local dev, populated for staging & production
const datadogClientToken = "";

if (datadogClientToken) {
  // this block on runs on staging/production because datadogClientToken is populated
  datadogLogs.init({
    clientToken: datadogClientToken,
    site: "datadoghq.com",
    forwardErrorsToLogs: true,
    sampleRate: 100,
  });
} else {
  // this block runs when developing locally because datadogClientToken is empty
  datadogLogs.logger.setHandler("console");
}

datadogLogs.logger.setLevel("info");

// when developing locally, this line logs out to the console when using < 4.9.0
// when using >= 4.9.0, nothing is printed to the console
datadogLogs.logger.info("test info");
```

**Expected behavior**
I would expect calls to `datadogLogs.logger.info("test info");` to log messages to the console when running locally based on the code above.

**Comment by liywjl** [comment]
Hello @timabb031,

Thank you for raising this, your example was super helpful. 

`console.log` calls coming from using [custom logs](https://docs.datadoghq.com/logs/log_collection/javascript/#custom-logs) before the SDK was initialised was more of a side effect than intended behaviour.

Depending on your setup, it might be easy to abstract the logging, using this useful trick to determine if the SDK has been initialised using this [trick](https://docs.datadoghq.com/real_user_monitoring/browser/troubleshooting/#the-rum-browser-sdk-is-initialized).
