### ISSUE TITLE
No matching version found for @datadog/browser-rum@4.27.1.

### ISSUE THREAD

**Issue by just-web-dev** [DataDog/browser-sdk#1881]
After updating to version 4.28.0 for both browser-logs and browser-rum, when running npm install I get an npm error of  **No matching version found for @datadog/browser-rum@4.27.1.**

**Comment by BenoitZugmeyer** [comment]
Thank you for opening this issue, and sorry for the inconvenience. Something went wrong during the v4.28.0 release and some versions were not updated. A new release has been made to fix the issue.
