### ISSUE TITLE
exclude dynamic API URLs 

### ISSUE THREAD

**Issue by KiranUppunda** [DataDog/browser-sdk#1930]
I am trying with ```excludedActivityUrls``` already.

But in my case I have few dynamic urls.

For example:
```https://cdn-url/agent/<--id-->/abc```
```https://some-end-point/url?dynamic_params```
```https://endpoint/<id>```

As per this one, I guess we will have to add the exact URL or ending url, [how page activity is calculated](https://docs.datadoghq.com/real_user_monitoring/browser/monitoring_page_performance/#how-page-activity-is-calculated).
So if it is dynamic, how can we restrict it ?

Thank you.

**Comment by BenoitZugmeyer** [comment]
You can either use a regex or use a function predicate. For example, given the dynamic URL `https://cdn-url/agent/<--id-->/abc`, you could use:
```ts
excludedActivityUrls: [
 /^https:\/\/cdn-url\/agent\/\d+\/abc$/
]
```
or

```ts
excludedActivityUrls: [
  (url) => {
    const parsedUrl = new URL(url)
    return parsedUrl.hostname === 'cdn-url' &&
        parsedUrl.pathname.startsWith('/agent/') &&
        parsedUrl.pathname.endsWith('/abc')
]
```

**Comment by KiranUppunda** [comment]
Thank you @BenoitZugmeyer
