### ISSUE TITLE
🙏 How to implement Fullstack tracing with RUM and APM?

### ISSUE THREAD

**Issue by 5er9e1** [DataDog/browser-sdk#1989]
I'm trying to implement Fullstack tracing according these articles

[first](https://www.datadoghq.com/blog/unify-apm-rum-datadog/)
[second](https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?_gl=1*b8ka5g*_ga*MTMzMTkzMjQzNS4xNjc1MjQ1MTcw*_ga_KN80RDFSQK*MTY3NTI0NTE3MC4xLjAuMTY3NTI0NTE3MC42MC4wLjA.&_ga=2.204618646.703574186.1675245171-1331932435.1675245170&tab=browserrum)

`DatadogRum` is initializing like:

```javascript
datadogRum.init({
    applicationId: someApplicationId,
    clientToken: someToken,
    site: 'datadoghq.com',
    service: serviceName,
    env: envName,
    sampleRate: isDevelopEnv ? 50 : 30,
    premiumSampleRate: isDevelopEnv ? 0 : 0,
    telemetrySampleRate: isDevelopEnv ? 20 : 0,
    useSecureSessionCookie: isDevelopEnv ? false : true,
    trackUserInteractions: true,
    defaultPrivacyLevel: 'mask-user-input',
    trackFrustrations: false,
    allowedTracingUrls: [
      {match: backendURL, propagatorTypes: ["datadog"]}
    ],
    traceSampleRate: isDevelopEnv ? 50 : 30,
});

datadogRum.startSessionReplayRecording();
```

Where `backendURL` is `https://api.some-url.com`

When URL like `https://api.some-url.com/api/v1/path` is accessed I'm expecting to see `x-datadog-trace-id`, etc... headers.
But RUM doesn't add any custom headers.

`x-datadog...` headers allowed by CORS policy. Prefilght requests are returning:

```text
Response headers:
  access-control-allow-headers: ..., x-datadog-trace-id, x-datadog-parent-id, x-datadog-origin, x-datadog-sampling-priority
```

Our frontend is Vue based and we sending XHR requests like:

```javascript
axios
  .post(
    `${backendURL}/api/v1/path`,
    payload,
    {
      headers: {
        'Content-Type': 'application/json',
      },
    }
  )
```

Is my understanding about headers correct?
What may remove headers if RUM is adding it?
Is it possible that RUM avoid to add headers for some reason / condition automatically?

Usual RUM requests are working properly and I can see
```
https://rum.browser-intake-datadoghq.com/api/v2/rum?ddsource=browser&ddtags=sdk_version%3A4.18.1%2Cenv%3Adevelop%2Cservice%3AserviceName&dd-api-key=pub1234xxxxxxxxxxxxx&dd-evp-origin-version=4.18.1&dd-evp-origin=browser&dd-request-id=uuid&batch_time=1675247515044
```
requests periodically

**Comment by yannickadam** [comment]
Hi @5er9e1 !

Your configuration looks fine. I've tried similar requests using Axios and the datadog headers can already be seen in the `request headers` of the preflight request. 

Could you try to:
- Bump `sampleRate` to 100 in your dev environment, clear your cookies (_dd_s) and see if that works for you? Headers will not be added if the session is not sampled.
- Check if you have any other library that could tamper with the headers of your network requests

Let us know if that fixes your issue.
