### ISSUE TITLE
RUM data not captured if we access our app using puppeteer

### ISSUE THREAD

**Issue by sbansal-clickup** [DataDog/browser-sdk#2000]
**What are you trying to achieve and what is your issue? Please describe.**
We at Clickup uses Datadog RUM for our production monitoring of user experience and page load times and it works great. On the other side, when we run the user flow automated using puppeteer (by chrome) we don't see any RUM data being captured in DD RUM.

**Describe the solution you'd like**
RUM data captured when exercising our app navigation using Puppeteer.

**Describe alternatives you've considered**
NA

**Comment by BenoitZugmeyer** [comment]
👋 Puppeteer-driven Chrome instances should be supported by the RUM Browser SDK. Though, for performances reason, we batch requests and flush only periodically or on some condition. We flush all pending data when the page is unloading.

When Puppeteer is closing the browser, by default, the page does not go through the whole unload process. To make this work, you will need to use [the `runBeforeUnload` option when calling `page.close`](https://pptr.dev/api/puppeteer.page.close/):

```js
  page.close({ runBeforeUnload: true })
```

Let us know if this works for you!

**Comment by sbansal-clickup** [comment]
@BenoitZugmeyer Thanks for your response. let me try this option and get back to you.

**Comment by sbansal-clickup** [comment]
@BenoitZugmeyer It didn't work. I still don't see RUM events as we run the user flow using puppeteer.  I am pasting snippet of code.

    import puppeteer from "puppeteer";
    await homePage.login(page, userName);
    //browse sidebar hierarchy
    await list.browseSpace(page);
    await page.close({ runBeforeUnload: true });
    await sleep(5000);
    await browser.close();

**Comment by BenoitZugmeyer** [comment]
A few troubleshooting leads:

* Are you sure that the `teamId` variable is correctly defined? 
* Are you using `datadogRum.setUser()` later? This function replaces the whole `usr` object, so using it later would remove the `workspaceId` property.
* Outside of the `if (teamId)` statement, could you set a user property to see if it is correctly set on RUM events? (ex: `datadogRum.setUserProperty("test", "foobar")`)

**Comment by sbansal-clickup** [comment]
@BenoitZugmeyer we don't know the userId and workspace id until the user is authenticated and this happens during initial load while user is logged in. After the user is authenticated, we fetch workspace and user id from localstorage. 
But as Datadog load script is loaded in beginning and if teamid is not in localstorage, we will miss this detail on our RUM samples until user is authenticated.

**Comment by bcaudan** [comment]
Hi @sbansal-clickup, indeed when using the `setUser` API, the provided info are added to the current view and session and on all subsequent events.
Events that have been generated before the call of the API won't have those infos.

**Comment by bcaudan** [comment]
@sbansal-clickup feel free to re-open if needed
