### ISSUE TITLE
🐛 Unable to provide a list of handlers to `datadogLogs.logger.setHandler`

### ISSUE THREAD

**Issue by borisyordanov** [DataDog/browser-sdk#2014]
**Describe the bug**
Unable to provide a list of handlers to `datadogLogs.logger.setHandler`

**To Reproduce**

1. Include `datadogLogs.logger.setHandler([HandlerType.http, HandlerType.console]);` in a TS codebase
![image](https://user-images.githubusercontent.com/12392666/218685465-caa8c085-7783-40d5-a710-419845adec2e.png)

**Expected behavior**
The TS error makes it impossible to apply multiple handlers [as described in the docs](https://docs.datadoghq.com/logs/log_collection/javascript/#change-the-destination)

**Comment by bcaudan** [comment]
Hello @borisyordanov,  do you have this issue with the latest version of the SDK?

**Comment by borisyordanov** [comment]
@bcaudan I apologise, I should have checked the version first. Works fine on the latest version

**Comment by bcaudan** [comment]
No worries, I'll update the bug template with this check 🙂
