### ISSUE TITLE
🐛 Errors don't show up if the exception thrown is not instance of Error

### ISSUE THREAD

**Issue by xMartin** [DataDog/browser-sdk#2033]
In RUM I want to track uncaught exceptions (Error Tracking). It works fine for TypeErrors or if my code contains `throw new Error("message")`. If my code is `throw "message"` the error gets sent to `https://rum.browser-intake-datadoghq.eu/api/v2/rum` as well but doesn't show up in https://app.datadoghq.eu/rum/error-tracking.

**To Reproduce**

1. Trigger runtime error in application code by throwing an exception like this: `throw "message"` or `throw { message: "message", data: "foo" }`
2. Go to Error Tracking page (https://app.datadoghq.eu/rum/error-tracking)
3. Cannot find the error

**Expected behavior**
See error as it happens if the exception was thrown like this: `throw new Error("message")`

--

@datadog/browser-rum: 4.34.1

**Comment by yannickadam** [comment]
Hi @xMartin,

You are correct - Such errors are currently not being tracked, and do not get grouped into issues. This is why you cannot see them in the Error Tracking tab. 

In the meantime, you can see these errors by navigating to [RUM - Sessions & Replays](https://app.datadoghq.eu/rum/sessions). Then, in the search bar, select `In | Errors`, then `Group into | Errors`.

**Comment by xMartin** [comment]
Thanks! Is there plans to fix it?

**Comment by jqlee85** [comment]
We are running into this too. Though we actually get this _even_ when throwing Error objects. Is there any guidance as to what kind of missing information causes errors not to get grouped into issues? Here's an example of the JSON which I see getting POSTed to `https://rum.browser-intake-datadoghq.com/api/v2/rum`:

````
"error":{
    "id":"aff69e84-287a-4700-9b75-153435e68494",
    "message":"Cannot read properties of undefined (reading 'parentIsUndefined')",
    "source":"source",
    "stack":"TypeError: Cannot read properties of undefined (reading 'parentIsUndefined')\n  at <anonymous> @ <anonymous>:1:32\n  at <anonymous> @ <anonymous>:1:54\n  at <anonymous> @ <anonymous>:4:15",
    "type":"TypeError",
    "handling":"unhandled",
    "source_type":"browser"
  },
````

**Comment by bcaudan** [comment]
@xMartin, with version `4.42.0`, cases like `throw "message"` or `throw { message: "message", data: "foo" }` should now have a stacktrace and then show up in error tracking.

@jqlee85, you can have a look at the [error tracking doc](https://docs.datadoghq.com/real_user_monitoring/error_tracking/browser/#overview) for explanation on which errors are grouped into issues. If you are noticing something wrong, feel free to open a dedicated issue for it.
