### ISSUE TITLE
[developer-extension] doesn't seem to work.

### ISSUE THREAD

**Issue by Manu-prisma** [DataDog/browser-sdk#2043]
**What are you trying to achieve and what is your issue? Please describe.**
I am trying to use the Chrome extension to validate and verify the integration and proper functioning of Datadog RUM on site pages.
Currently I managed to build the extension but it doesn't seem to work.
The configuration seems to identify well (cf Capture d’écran 2023-02-27 à 14.39.07.jpg) 
![Capture d’écran 2023-02-28 à 14 41 29](https://user-images.githubusercontent.com/87384634/221871681-c0b13846-2c3c-4031-bf79-1fd30c2a24f0.jpg)
but no logs go back to the console (cf Capture d’écran 2023-02-27 à 14.39.18.jpg).
![Capture d’écran 2023-02-28 à 14 43 32](https://user-images.githubusercontent.com/87384634/221871837-808be698-e850-4811-89e7-d5b308bb2cb7.jpg)

**Describe the solution you'd like**
I would like to be able to use the Chrome extension in order to be able to verify and validate the operation and configuration of datadog RUM on my sites

**Describe alternatives you've considered**
I have not found any solution to validate the operation without having to go through the dashboards

**Comment by yannickadam** [comment]
Hi @Manu-prisma, 

Your configuration shows a sampleRate of 1. You may want to bump this to 100 and clear your cookies to ensure your session is sampled. 
Let us know if that fixes your issue.

**Comment by Manu-prisma** [comment]
Ok, it's work, thanks :)
