### ISSUE TITLE
Getting lint error while working with browser logs

### ISSUE THREAD

**Issue by NevilDabre** [DataDog/browser-sdk#2067]
**Issue**
Included browser logs scripts in NextJS project but getting this eslint error
`error  'DD_LOGS' is not defined  no-undef`

**Documentation link**
https://docs.datadoghq.com/logs/log_collection/javascript/#cdn-sync

**Code**
_Added this code in _document.js_

`<Script type="text/javascript" src="https://www.datadoghq-browser-agent.com/datadog-logs-v4.js" strategy="beforeInteractive"></Script>
          <Script strategy="beforeInteractive">
            {window.DD_LOGS &&
              window.DD_LOGS.init({
                clientToken: process.env.DATADOG_CLIENT_TOKEN,
                forwardErrorsToLogs: true,
                site: 'datadoghq.com',
                sessionSampleRate: 100,
              })}
          </Script>
          {/* End Datadog script */}`

Added this code to the pages/signup.js
`  useEffect(() => {
    datadogLogs.logger.info('Signup Init', { file: 'signup.js' });
    window.DD_LOGS && DD_LOGS.logger.info('Signup Button clicked', { name: 'buttonName', id: 123 })
    }, [])`
    
  Temporary fix:
  Added window as the parent function
  window.DD_LOGS && window.DD_LOGS.logger.info('Signup Button clicked', { name: 'buttonName', id: 123 })
  
Just checking if the documentation is correct.

**Comment by bcaudan** [comment]
Hi @NevilDabre,

Indeed, during execution on the browser side, using `window.DD_LOGS` or `DD_LOGS` should be equivalent but linter can be triggered by the later.
Looking at our documentation, there are some inconsistencies in our usages, prefixing by `window` all the time should not hurt.

**Comment by bcaudan** [comment]
We have updated our docs to use `window` all the time.
