### ISSUE TITLE
🙏 Start new session manually when Datadog has already initialised

### ISSUE THREAD

**Issue by UNRULYEON** [DataDog/browser-sdk#2103]
**What are you trying to achieve and what is your issue? Please describe.**
I'm working on a SPA which is deployed in a store. With it, visitors are able to check themselves in. We have enabled Session Replay which works like a charm :). However, in the RUM session dashboard, I see sessions which last for up to 50 minutes (see screenshot). I know this session contains multiple visitors checkins as the check-in process takes at most a couple of minutes.

![Screenshot 2023-03-24 at 14 29 43](https://user-images.githubusercontent.com/29234113/227534193-691ec9ca-b3ce-42c7-b297-a7e1f2e4ffcf.png)

**Describe the solution you'd like**
From what I understand, a session is based on the `sessionId` in the internal context of `DD_RUM`. Is there a way of changing/updating/refreshing the session ID so sessions in the dashboard will be of a unique visitors? The SPA has a clear "start" and "end" when checking in, so starting a new session manually and calling something like `DD_RUM.generateNewSessionId()` would solve this as I am able to call it when a new check in starts.

**Comment by yannickadam** [comment]
Hi @UNRULYEON,

For the time being, the SDK does not have the functionality you describe.
We are currently working on a feature to support Kiosk applications, which should satisfy your needs. 
Please have a look at the following PR https://github.com/DataDog/browser-sdk/pull/2064
