### ISSUE TITLE
👿 Dark Pattern in RUM Script

### ISSUE THREAD

**Issue by kylepauljohnson** [DataDog/browser-sdk#2119]
**What are you trying to achieve and what is your issue? Please describe.**
As shown on your [documentation page](https://docs.datadoghq.com/real_user_monitoring/browser/#npm) when you run the init command for the RUM script depending version used the property name may vary but the behavior is the same. 

If you don’t include or set the (sessionReplaySampleRate, premiumSampleRate or replaySampleRate) it defaults to 100%. When implementing a script for any other platform this is very unexpected behavior. Typically if you omit a property it disables the functionality and defaults to a falsy value. Opt in vs. explicit opt out especially when it comes to something that is billable.

To make things worse, you have changed the name of this property 3 times since May of 2022 further exacerbating this dark pattern and making it feel like an intentional way to generate revenue from customers. With each of these version changes if someone upgrades and doesn’t notice this specific change you are billing them for 100% of sessions vs whatever they had set previously. 

**Describe the solution you'd like**
When sessionReplaySampleRate, premiumSampleRate or replaySampleRate are omitted default value should be 0%, disabling the feature.

**Comment by yannickadam** [comment]
Hi @kylepauljohnson !

The `sessionReplaySampleRate` parameter's behaviour is aligned with `sessionSampleRate`, which also defaults to 100% if not specified. Also, please note that for `sessionReplaySampleRate`, 100% is relative to the sessions captured by `sessionSampleRate`. 

When creating a new RUM application on Datadog, the onboarding snippet provided includes both parameters, accompanied by a side-panel describing the exact percentage of sessions which will be captured with, and without session replays. 

We're always striving to improve the clarity of our configuration parameters - sorry about the frequent name change. However, the deprecated parameters (`premiumSampleRate` and `replaySampleRate`) are still being taken into account in the current major release. Hence, no change has occurred in the number of billed sessions for customers who still use the deprecated parameters with the latest version today (4.x.x).

Thank you for your feedback! There are always talks around how to improve the usage and onboarding of our SDKs, and we take all comments in consideration.

**Comment by kylepauljohnson** [comment]
I would suggest that if `sessionSampleRate` is aligned with `sessionReplaySampleRate` they should both be changed to reflect 0% if omitted. 

If I strip the initialization code entirely of this value in an effort to turn off this feature, I would expect it to be disabled as it's are not referenced at all, not turned on to be 100%. This is extremely counter intuitive and is contrary to how almost all other SDK's/scripts operate. 

I would suggest moving towards a more conventional pattern regardless of the script generator you offer at setup time, or documentation. This will prevent surprises from your customers that will negatively impact your relationships with your customers.

**Comment by bcaudan** [comment]
Hi @kylepauljohnson,

We have updated this behaviour with the rum SDK v5, now `sessionReplaySampleRate` is 0 by default to avoid unexpected extra billing.
Mode details in the [upgrade guide](https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#from-v4-to-v5).

**Comment by erik-hunter** [comment]
Hey all, I'm glad that we updated sessionReplaySampleRate, but my organization just updated from v4 to v5, and we missed the change from "sampleRate" to "sessionSampleRate". We normally budget for only a 1% sample so the automatic increase to 100% was a problem for us. Changing the behavior to turn sampling off could save a lot of people some unexpected RUM costs, would that be possible?
