### ISSUE TITLE
🙏 Warning/Errors on Console After SDK Installation

### ISSUE THREAD

**Issue by BenedictFLW** [DataDog/browser-sdk#2154]
**What are you trying to achieve and what is your issue? Please describe.**
Background: I am trying to use Datadog to log events on an application. The project is written with Vue.js and JavaScript, the UI is divided in a way. We use rollup for bundling the application and we have other NPM packages within the application.

 Currently installed package:
- `"@datadog/browser-logs": "^4.38.0",`

Main Issue: When I serve the project using our serve command, I get these errors showing as warnings on the terminal, they don't affect the application in the browser, but it will be more comforting to have a clear terminal. 

See the image shown below:
<img width="711" alt="Screenshot 2023-04-11 at 13 58 49" src="https://user-images.githubusercontent.com/97960480/231171008-7a9b583b-0c9c-47c8-a13e-51d9cbff2dce.png">

What I’ve done so far:
I have installed other versions of the package, but the error on the console still persists.

**Describe the solution you'd like**
A version to install that I will not have the warnings show up in the terminal OR a way to fix the issue completely with the current version.

**Describe alternatives you've considered**
I do not want to use the CDNs as the NPM package works best for my use-case.

**Comment by bcaudan** [comment]
Hello @BenedictFLW,

Could you share a setup allowing us to reproduce this behaviour?

**Comment by BenedictFLW** [comment]
Hiya @bcaudan, I'm afraid I won't be able to spin up one so identical to my current setup easily, but I think you can reproduce the issue with a JavaScript project that uses rollup as a bundler.

Will that suffice?

**Comment by BenedictFLW** [comment]
Yeah, I thought about making changes in the rollup configuration, I've been looking through rollup's docs but haven't found anything that addresses this specifically.

I'll try to come up with a demo project on codesandbox and drop a link here for you.
Thanks for the prompt response.

**Comment by bcaudan** [comment]
Feel free to re-open if you can provide a setup allowing us to reproduce this behaviour.
