### ISSUE TITLE
Can't recording a user session inside an iframe

### ISSUE THREAD

**Issue by camilosegura** [DataDog/browser-sdk#2168]
Hi team,  I'm trying to use Session Replay Recording inside an iframe but it is not recording, I'm using `useCrossSiteSessionCookie: true` in the DD RUM config and can see data logged in DD dashboard but not the session replay

I'd like to can record a user session inside an iframe

**Comment by bcaudan** [comment]
Hello @camilosegura,

Recording inside an iframe is not yet supported, cf [docs](https://docs.datadoghq.com/real_user_monitoring/session_replay/troubleshooting#some-html-elements-are-not-visible-at-replay).
It is definitely something that we would want to address at some point but no ETA to share yet.

**Comment by obiscr** [comment]
@bcaudan Hey, Is recording iframes still not supported? I'm using https://www.datadoghq-browser-agent.com/us1/v6/datadog-rum.js this file. The area of the Iframe is displayed in a blank gray color.
