### ISSUE TITLE
Update RUM Browser Support (safari)

### ISSUE THREAD

**Issue by aharelick** [DataDog/browser-sdk#2174]
Hi! We have RUM data coming in from our website that is mainly used on mobile phones (safari/chrome & in app browsers like Instagram/FB). We are also getting some RUM data through our hosting provider (vercel). There is a pretty significant difference in the FCP and LCP numbers we're seeing with vercel showing less than 1 second and DD showing 1.5-3 seconds.

We're trying to track down the source of the difference. My understanding is that [LCP is not supported by Safari](https://developer.mozilla.org/en-US/docs/Web/API/LargestContentfulPaint#browser_compatibility) at all while [FCP should be](https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming#browser_compatibility). However, the [Browser Support](https://github.com/DataDog/browser-sdk/blob/af0787ad83b58bdb81ae222bc7a02feae2a3d89f/packages/rum/BROWSER_SUPPORT.md) page in this repo makes it seem like nothing but FID is supported for Safari. Is this still accurate or is this page outdated?

**Comment by amortemousque** [comment]
Hello @aharelick,

Thanks for the feedback. Yes it seems that our Browser Support is not up to date but we do support FCP for Safari. We will update it.

Regarding the FCP and LCP difference with Vercel, are you looking at the average FCP/LCP on a page or the same FCP/LCP on the same page load?

**Comment by aharelick** [comment]
Hi, we actually just figured out the difference in the timings was because we had Datadog Synthetics running against prod that we were excluding from our Datadog RUM metrics, but were not being excluded from Vercel. Thanks for updating the browser support page!
