### ISSUE TITLE
🐛 browser-logs: fields of custom Error objects passed in log context no longer included (since 4.41.0)

### ISSUE THREAD

**Issue by niekert** [DataDog/browser-sdk#2195]
**Describe the bug**
Since version 4.41.0 of `@datadog/browser-logs` any custom errors included in the log context field are serialized as `[Error]` instead of the fields being included in the error. I'm not sure if this was intentional, but it altered behavior quite significantly for our logging setup.

**To Reproduce**
Example code:

```
class CustomError extends Error {
  constructor(message, opts) {
    super(message);
    this.opts = opts;
  }
}

// initialize logger

datadogLogs.logger.error("just a log", {
  anotherError: new CustomError("something went wrong", {
    please: "showthisInDatadog "
  })
});
```

We are using this pattern in some places where we aggregate errors, or provide the original error cause as a custom field on the log context (where we do not wrap errors with `cause`)

**Expected behavior**

Would expect the behavior to be similar to that of v4.40.0

**V4.40.0**
<img width="684" alt="image" src="https://user-images.githubusercontent.com/5508905/235450610-2c6a181e-f5d3-4e7a-a0a0-52e4ddadce8d.png">

**V4.41.0**
<img width="668" alt="image" src="https://user-images.githubusercontent.com/5508905/235450760-1c6728f7-83d2-4f0e-9d87-b1e1b16f617e.png">

**Comment by yannickadam** [comment]
Hi @niekert !

Thanks for reporting this issue. We have reverted the behavior of serializing an `instanceof Error` in `4.42.0`. Let us know if everything works as expected. 

However, it is our intention to enhance the serialization of certain object types - notably errors - in our next major release.
Currently:
```
=> JSON.stringify( new Error('Error') )
=> '{}'
```
This hides the fact that the object was actually an error. 

Could you give us more insights about your use-cases, and how you would expect errors to be presented?
Also - have you tried the [new Error parameter](https://github.com/DataDog/browser-sdk/pull/2029) of the logger APIs, introduced in `4.36.0`?
`logger.[level](message: string, messageContext?: object, error?: Error)`
