### ISSUE TITLE
🙏 Best practice, session lifetime

### ISSUE THREAD

**Issue by Bertie-Chapman** [DataDog/browser-sdk#2220]
My company generate orders through a SPA that gets given a unique id. Once completed the user is able to start a new order. We are wanting to capture data in the context of each individual order. What is the best approach for this? Is a session supposed to represent a users entire lifetime through the application and if so is there a way to mimic scope-life functionality to capture timeframes within a session for particular orders? Or is it best to have separate sessions for each order with the order id added as a global context property? Any insight or direction to documentation would be greatly appreciated.

**Comment by bcaudan** [comment]
Hi @Bertie-Chapman,

We are currently working on something similar to your use case.
The guide to explain how to do that is not ready yet but in a nutshell, the default behaviour of the user session is (cf [doc](https://docs.datadoghq.com/real_user_monitoring/browser/data_collected/)):

>  It aggregates all RUM events collected during the user journey with a unique session.id attribute. Note: The session resets after 15 minutes of inactivity.

However, in v4.37.0 we have introduced a [`stopSession()` API](https://github.com/DataDog/browser-sdk/pull/2064) to manually stop the RUM session.

So in your use case, you could manually stop the session after each individual order.

**Comment by Bertie-Chapman** [comment]
Hi @bcaudan, okay great thanks for the reply! I will incorporate and see how it works for us 👍

**Comment by muriloalvestravelpass** [comment]
Hey guys, I have a similar scenario. I'm working in call-center application and we want to have a session for each call. Is there a `starSession` method? Because after I stop a session, how can I guarantee another one has started?

Something like this:
```
useEffect(() => {
  if(callState == "call_ended")
    stopSession()
  if(callState == "new_call_started")
    starSession()
}, [callState])
```
