### ISSUE TITLE
🐛 Spec files included in npm packages

### ISSUE THREAD

**Issue by charkour** [DataDog/browser-sdk#2221]
**Describe the bug**
`.spec.ts` files are included in the packaged versions on NPM. I understand that `/src` files are included for easy reference, but including the test files simply bloats the size of the package on the disk. Is there a compelling reason to continue to keep `.spec.ts` in the package NPM versions of the packages?

**To Reproduce**

1. NPM JS and search for `@datadog/browser-rum` or `@datadog/browser-logs`
2. Click on `try on RunKit`
3. View source files
4. See the `.spec.ts` files included

<details>
<summary>Screenshot from RunKit showing that `.spec.ts` files are included</summary>

![image](https://user-images.githubusercontent.com/33156025/236846336-493f5e76-8458-4bf8-b865-7aee8dc9bfd4.png)

</details>

**Expected behavior**
Do not include `.spec.ts` files in the packaged `/src` because it bloats the download size of the package from NPM. We need to be conscious of the fact that disk space is finite and including bloat is wasteful.

Thank you.

**Comment by charkour** [comment]
Here is a [good conversation](https://stackoverflow.com/a/37421736/9931154) about what to include within a package. I would argue that including `src/` is also bloat and should be removed as well as removing the test files.

**Comment by bcaudan** [comment]
Hi @charkour, 

We have included the src files in the npm package in response of this issue: #535
But indeed, specs file should not be necessary, we will remove them.

**Comment by charkour** [comment]
Hi @bcaudan, thanks for the quick reply! 

I appreciate linking the past issue. Because source maps are included, we then need to bundle the `src/` directory, correct?

**Comment by bcaudan** [comment]
> I appreciate linking the past issue. Because source maps are included, we then need to bundle the src/ directory, correct?

Exactly!

About spec files, cf #2224, they should be excluded in the next release.

**Comment by charkour** [comment]
Thanks for the quick update!

**Comment by BenoitZugmeyer** [comment]
It's been released as part of v4.42.1
