### ISSUE TITLE
💡 Interaction to Next Paint metrics

### ISSUE THREAD

**Issue by wylieconlon** [DataDog/browser-sdk#2233]
The [Interaction to Next Paint](https://web.dev/inp/) metric is a missing part of the Datadog web vitals tracking. Ideally, it would be tracked automatically.

**Describe alternatives you've considered**

This can be implemented as a custom metric using a snippet such as this:

```
import { onINP } from "web-vitals/attribution";

onINP(
  (metric) => {
    return datadogRum.addAction("web-vitals.onINP", {
      ...metric,
      duration: metric.value,
    });
  },
  {
    reportAllChanges: true,
  },
);
```

**Comment by amortemousque** [comment]
Hello @wylieconlon,
Thanks for the feedback. It's on our radar, but hasn't been prioritised yet. We will keep you updated.

**Comment by RyanMulready** [comment]
Any update here? We started getting search console warnings about this new metric. Would love to start collecting real data in Datadog on nit.

**Comment by cy4n** [comment]
i would also love to see this metric sooner than later. 
Google will use the INP metric for their SEO placements from 03/2024, but website providers will need time ahead to actually monitor this metric and fix issues this creates. 
(and web vitals monitoring is a major selling point of DD RUM)

per the custom metric the OP stated: as a customer, my main concern using a SaaS service is NOT building stuff myself

**Comment by nhientrandatadog** [comment]
Hi everyone, thanks for your feedback. This has been prioritized for implementation, targeting early Q4 for it to be available in Datadog RUM. Stay tuned for updates.

**Comment by cy4n** [comment]
early Q4 which year? *SCNR*

**Comment by imteekay** [comment]
Apparently, this was first implemented a couple of months ago https://github.com/DataDog/browser-sdk/pull/2355 but it was running as [an "experiment"](https://github.com/DataDog/browser-sdk/pull/2355/files#diff-a23dad5d5f0dfd2d7b93bac9e0580133cb7f5aff9cbfc7767bae7cac81d5fcb0R20). After a [couple](https://github.com/DataDog/browser-sdk/pull/2466) of [fixes](https://github.com/DataDog/browser-sdk/pull/2405), I saw a new PR removing this experiment 5 days ago https://github.com/DataDog/browser-sdk/pull/2448 and it released the change in [v5.1.0](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#v510).

Is it ok to assume that from `v5.1.0`, we'll have INP being collected automatically on datadog?

**Comment by amortemousque** [comment]
Hello everyone,
Yes, the core web vital Interaction To Next Paint (INP) is officially available since `v5.1.0`!

**Comment by ischell** [comment]
This is great to see! I know that when we get this out and see high values, one of the first questions is going to be how to track down the source of the long interactions. Can you share any plans you have around collecting and exposing the recommended INP contextual info referenced here? https://web.dev/articles/find-slow-interactions-in-the-field#what_you_should_collect_in_the_field_and_why

**Comment by amortemousque** [comment]
Hello @ischell, 
Yes this is something we have in mind and we are currently working on collecting the target element attributed to the Core Web Vitals, including INP.

**Comment by amortemousque** [comment]
Hello everyone, 
We now collect the Core Web Vital selectors (including the INP selector) since the RUM browser SDK v5.4.0. It is visible in the Datadog UI 
![image](https://github.com/DataDog/browser-sdk/assets/4342515/1796bdb2-3b76-4d8c-b9f7-e4ef41b30f2e)
