### ISSUE TITLE
🐛  Setting dd_fingerprint is not changing Error fingerprint

### ISSUE THREAD

**Issue by dletran** [DataDog/browser-sdk#2312]
**Describe the bug**
Using v4.43 of @datadog/browser-rum, adding the code described in the [docs](https://docs.datadoghq.com/tracing/error_tracking/custom_grouping/) we're not getting the custom fingerprint in the error
<img width="795" alt="Screenshot 2023-06-28 at 16 11 01" src="https://github.com/DataDog/browser-sdk/assets/3493265/8a3a32e0-ef42-4480-ad7c-1b3250c981e2">

For extra context: what we aim to achieve is getting a way of creating custom errors that we can query in a new Monitor to get custom alerts (since looks like the error context props are not available in the Monitor query). If there's a different way to achieve this (like being able to set the another Error property such as type) let me know

**To Reproduce**
```javascript
const { datadogRum } = require('@datadog/browser-rum')

const error = new Error('Validation Error: ...');
error.dd_fingerprint = 'validation'
datadogRum.addError(error)
``` 

**Expected behavior**
The fingerprint for the error should be 'validation'.

**Comment by amortemousque** [comment]
Hello @dletran, 
The fingerprint you see in the Datadog UI is a hash of the fingerprint you send this is why it is different. I tried with your code snippet and the errors are well grouped under the same issue. Can you confirm the grouping work on your side?

**Comment by dletran** [comment]
Oh ok got it! I thought the actual fingerprint would be the one we set, the grouping is indeed working correctly. Then I guess if we'd want to use this in a monitor to filter certain types of errors we'd need to filter by the fingerprint hash right?

Is there any other way to filter an error event in a monitor by a custom value?

**Comment by amortemousque** [comment]
The [addError API](https://docs.datadoghq.com/real_user_monitoring/browser/collecting_browser_errors/?tab=npm#collect-errors-manually) has a second argument called `context` that you can use to enrich your error events with new attributes. I recommend using it if you want to filter your errors on custom attributes.

**Comment by dletran** [comment]
nice! I thought context couldn't be used as a filter, I just saw I can use it 👍
