### ISSUE TITLE
🙏 If sessionReplaySampleRate is set to 0 while startSessionReplayRecording is enabling.

### ISSUE THREAD

**Issue by usagi-f** [DataDog/browser-sdk#2318]
**What are you trying to achieve and what is your issue? Please describe.**

I was using `datadog-rum`, but I want to disabled the Session Replay feature for a while because I have concern for costs.

I had set `sessionReplaySampleRate: 0` because I can change only rate number. However, some replay record came in a dashboard.

In document, wrote a disable way - you should remove `startSessionReplayRecording()`.
https://docs.datadoghq.com/real_user_monitoring/session_replay/#disable-session-replay

It can't be help to me if this is specification, I'm worried that I don't know behavior in execute Recording and sample rate is 0 combined.

**Describe the solution you'd like**

- Even if recording method executed, sample rate is 0 would recording stop.
- Specify the behavior of this case in the documentation.

**Comment by amortemousque** [comment]
Hello @usagi-f,
If `sessionReplaySampleRate` is set to 0, calling `startSessionReplayRecording()` shouldn't do anything. You should not see replay records. Can you give me more details about your setup: environment, tech stack, RUM SDK version and configuration?

**Comment by usagi-f** [comment]
@amortemousque
Thank you for reply.

Maybe it's just an operation mistake. I was taken steps the following on this time. 

1. To enable RUM, id and token were made environment variables, and implementation code was written first like "feature toggle" (sessionReplaySampleRate was 10 at this point).
2. changed the rate to 0 at the **same time** as enabling RUM by passing the environment variable.

You have a cookie in the client to determine when RUM is sent, right?
If the timing of accessing strangely the browser coincides with the moment of deployment, is there a possibility of a session replay being sent?

In fact, we have not received a session replay since then while the deployment is all complete and the new version of the service is running.

- @datadog/browser-rum@4.44.0
- next@12.3.4 (node@18.16.1)
- k8s
  - Application has multiple pods.
  - Blue green deployment

```tsx
// pages/_app.tsx in Next.js
import getConfig from 'next/config';

const { publicRuntimeConfig } = getConfig();

if (publicRuntimeConfig?.id && publicRuntimeConfig?.token) {
  datadogRum.init({
    applicationId: publicRuntimeConfig.id,
    clientToken: publicRuntimeConfig.token,
    site: 'datadoghq.com',
    service: 'my-service',
    env: 'production',
    sampleRate: 1,
    sessionReplaySampleRate: 0,
    trackInteractions: true,
    trackResources: true,
    trackLongTasks: true,
    defaultPrivacyLevel: 'mask-user-input',
    allowedTracingUrls: [
     'https://my-service',
      (url) => url.startsWith('https://my-service'),
    ],
  });
  datadogRum.startSessionReplayRecording();
}
```

**Comment by amortemousque** [comment]
Yes the RUM browser SDK rely on cookie to determine if a session is tracked. Do you mean that after your step 1, users could have loaded the application with a sessionReplaySampleRate to 10?

**Comment by usagi-f** [comment]
Due to the way the deployment works, it is unlikely that a pod with sessionReplaySampleRate of 10 will be accessed with the environment variable set to enable RUM.

Even now, session replay is still not coming to the dashboard, so it appears that replay is currently stopped based on the rate being 0 as per the specification.
If you have no idea, it may not be an SDK problem. You can close this issue.
