### ISSUE TITLE
🐛 browser-rum-slim does not include the bundle folder on npm.

### ISSUE THREAD

**Issue by shajz** [DataDog/browser-sdk#2320]
**Describe the bug**

Hi, I'm trying to use `@datadog/browser-rum-slim` on a very old project via the bundle .js files. 

They exist for [@datadog/browser-logs](https://www.npmjs.com/package/@datadog/browser-logs?activeTab=code) and for [@datadog/browser-rum](https://www.npmjs.com/package/@datadog/browser-rum?activeTab=code) but they are not included into [@datadog/browser-rum-slim](https://www.npmjs.com/package/@datadog/browser-rum-slim?activeTab=code).

This seems like a bug since there is a [bundle build script](https://github.com/DataDog/browser-sdk/blob/main/packages/rum-slim/package.json#L10).

**To Reproduce**

N/A

**Expected behavior**

The bundle files should be published for the `@datadog/browser-rum-slim` package.

**Comment by BenoitZugmeyer** [comment]
Thank you for reporting this issue! This should have been fixed in `v4.44.1` ([changelog](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#v4441)), but please install the latest version, as `v4.44.1` had packaging issues.
