### ISSUE TITLE
Safely access `window` or wait until after calling `.init`

### ISSUE THREAD

**Issue by dcurletti** [DataDog/browser-sdk#235]
We would like to implement RUM in our server-side rendered React application. We get an error at runtime because this library attempts to access `window` during script load.

The ask is:
* can we avoid invoking `window` until after calling `init`?
OR
* can we safely access `window` and do an early termination if its not defined?

We reverted to execute the code via html script download, but would really like to avoid that. Thanks!

**Comment by bcaudan** [comment]
Hi @dcurletti!

I have been able to reproduce your issue with a simple server side rendering setup.
We will see how to handle that and let you know when a fix is ready.

Thanks for the feedback!

**Comment by slavik-chapelskyi** [comment]
We experienced same issue using this package in `next.js`.

**Comment by slavik-chapelskyi** [comment]
@bcaudan Thanks :tada:

**Comment by bcaudan** [comment]
@dcurletti, @slavik-chapelskyi it should be fixed in v1.5.0.
