### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by vladgolubev** [DataDog/browser-sdk#236]
Logging objects with circular structures causes an uncaught error. For example, try `DD_LOGS.logger.info('hello', window)`.

Normally, we don't log such objects, but when it happens by accident it can break the whole application.

What about using smth like `fast-json-stringify`?

![image](https://user-images.githubusercontent.com/3817380/72455342-44c6f600-37cb-11ea-8a81-80779d891a85.png)

**Comment by bcaudan** [comment]
Hi @vladgolubev!

Thanks for the report, we will look into it and get back to you when it is fixed.

**Comment by bcaudan** [comment]
It should be fixed with 1.2.10 version.
