### ISSUE TITLE
Execution is not allowed in the current context.

### ISSUE THREAD

**Issue by rthreei** [DataDog/browser-sdk#238]
**Browser:** Safari 13.0.4

<img width="586" alt="Screen Shot 2020-01-20 at 2 59 07 PM" src="https://user-images.githubusercontent.com/5098873/72754603-495a2880-3b96-11ea-8e2a-fa7488298c42.png">

https://github.com/DataDog/browser-sdk/blob/9acbda2858cf11f2eeefd7bcbf165795195069b5/packages/core/src/init.ts#L61-L64

`'prerender'` seems to be [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState).

The error goes away after a page refresh.  Not sure what that is about.

**Comment by bcaudan** [comment]
Hi @rthreei,

Thanks for the report!
It should be fixed in the 1.2.9 version.

**Comment by rthreei** [comment]
@bcaudan thank you!
