### ISSUE TITLE
🐛 RUM: Styles coming from CSS-in-JS (Stitches) are not recorded

### ISSUE THREAD

**Issue by sandgraham** [DataDog/browser-sdk#2380]
**Describe the bug**

With `@datadog/browser-rum@v4.45.0`, we are seeing that session recordings do not pick up styles which come from a CSS-in-JS library we use: [Stitches](https://github.com/stitchesjs/stitches). We use Stitches along side static compiled CSS and we can see that the static CSS is recorded whereas styles coming from Stitches are not.

Stitches uses JavaScript to manage styles with the CSSOM API. We render a static `<style id="stitches" />` element in the `head` of our document, which Stitches uses for runtime styling injections.

Note, we had similar issues with FullStory. Originally they were only recording styles if added with `insertRule` to `CSSStyleSheets`, but Stitches adds styles to CSSMediaRules which are children of a top level `CSSStyleSheet`. I don't know the exact changes they made but I think they started recording `insertRule` to `CSSMediaRules` as well. Additionally, we had to add a class to the `<style id="stitches">` element to help FullStory's SDK pick up the runtime insertions.

**To Reproduce**

1. Load a web app using Stitches.
2. Observe that the DataDog session recording is not styled as the page is.

**Expected behavior**

I would expect the styles in the recording to reflect the styles applied in the browser. For instance, when using FullStory, all of our styles are picked up properly in session replays.

Here is an example of the un-styled pages we are observing. Note, styles that are picked up come from static CSS:
| Actual | DataDog |
| --- | --- |
| <img width="1424" alt="Screenshot 2023-08-12 at 04 25 09 PM@2x" src="https://github.com/DataDog/browser-sdk/assets/1939257/d9199a15-f158-4e64-abf7-3dc3066a8243"> | ![Screenshot 2023-08-10 at 3 54 46 PM](https://github.com/DataDog/browser-sdk/assets/1939257/e489866a-40a3-446a-b329-f809353ae8f8) |

**Comment by bcaudan** [comment]
Hello @sandgraham,

If I remember correctly, we already did a couple of fixes for stitches.
Could you share a web app that reproduce the issue?

**Comment by BenoitZugmeyer** [comment]
> Originally they were only recording styles if added with insertRule to CSSStyleSheets, but Stitches adds styles to CSSMediaRules which are children of a top level CSSStyleSheet. I don't know the exact changes they made but I think they started recording insertRule to CSSMediaRules as well

Very good analysis. We've been there, and we did that :) https://github.com/DataDog/browser-sdk/pull/1699, released in v4.18.0 one year ago. I just tried and failed to reproduce your issue with a small React application using stitches like you suggested.

> I could put up a temporary unauthenticated page with some styling test cases- would that be enough to help share reproduction? Would still need access to our DD instance to see the other end though.

We would love that. Or you could get in touch with the support support@datadoghq.com and provide a test account. We don't need to access your DD instance, we have the tooling to inject a development version of the SDK and configure it to send data to one of our DD instance.

**Comment by sandgraham** [comment]
@BenoitZugmeyer - I added an unauthenticated page in our app to demonstrate the issue [here](https://app.ashbyhq.com/dd-stitches). On this page we're rendering a few random components that use Stitches. This is what it should look like:

<img width="657" alt="Screenshot 2023-08-28 at 03 45 11 PM@2x" src="https://github.com/DataDog/browser-sdk/assets/1939257/b44bf4b8-da8d-4d72-89b2-614a1002871a">

Here is what it looks like in our session replay:

<img width="637" alt="Screenshot 2023-08-28 at 03 45 37 PM@2x" src="https://github.com/DataDog/browser-sdk/assets/1939257/5c9393bf-046c-48cc-aa17-9bf0810a500f">

In this demo, some of the components are styled directly with Stitches and some are styled with static CSS that references the css vars created by Stitches (as part of [`createTheme`](https://stitches.dev/docs/tokens)). It seems that all of the static CSS loads fine, but Stitches doesn't work at all, nor does any reference the static CSS makes to Stitches' css vars.

As an example, I created some boxes at the bottom of the page that reference Stitches' css vars from static CSS. Below is a snippet of the styles applied to each box (with differing background colors). Note, the `--ashby-*` css vars are the ones created and injected by Stitches.

```scss
.box {
  background-color: var(--ashby-colors-bgSecondary); // fails
  border: solid 0.5px #0001;                         // works
  border-radius: var(--ashby-radii-md);              // fails
  box-shadow: var(ashby-shadows-normalOutlined);     // fails
  height: 64px;                                      // works
  width: 64px;                                       // works
}
```

Hopefully this helps shed some light on the issue!

**Comment by BenoitZugmeyer** [comment]
Thank you for your cooperation. A fix is in progress, see https://github.com/DataDog/browser-sdk/pull/2397.

**Comment by sandgraham** [comment]
@BenoitZugmeyer - I noticed the fix is part of v4.48.2 but that hasn't been published yet. Any blockers on publishing? Would love to try the fix out.

**Comment by BenoitZugmeyer** [comment]
We released it today! Sorry for the wait, we deployed it slowly so we have time to catch errors related to this change.

**Comment by sandgraham** [comment]
Thank you for the fix @BenoitZugmeyer! Things look good in our RUM sessions:

<img width="375" alt="Screenshot 2023-09-08 at 03 51 12 PM@2x" src="https://github.com/DataDog/browser-sdk/assets/1939257/5084fd11-f022-4d4c-b898-347692ccfa8d">
