### ISSUE TITLE
excludedActivityUrls doesn't work for url like "data:image/jpeg;base64,...."

### ISSUE THREAD

**Issue by wheat-yjy** [DataDog/browser-sdk#2393]
**What are you trying to achieve and what is your issue? Please describe.**
I have several urls like [data:image/jpeg;base64,....], then I will use`fetch` to read it and convert it to blob.
The code will be like
`fetch(url).then(resp => resp.blob())`

The problem here is I found datadog caused the page frozen for about 8s. Then I found this one

![image](https://github.com/DataDog/browser-sdk/assets/37967180/81214e9d-fd20-4253-87d3-56fb27daf9ee)

I think I don't need datadog to trace urls like [data:image/jpeg;base64,.... ], So I add `/data:image\/jpeg;.*$/` into excludedActivityUrls. But it doesn't work

**Describe the solution you'd like**
How can I block the trace for urls like [data:image/jpeg;base64,.... ]?

**Describe alternatives you've considered**

**Comment by amortemousque** [comment]
Hello @wheat-yjy,
What you see in the console, is the RUM resource created from your fetch request. If you don't want to send them, you can use the [beforeSend API](https://docs.datadoghq.com/real_user_monitoring/guide/enrich-and-control-rum-data/?tab=event).
