### ISSUE TITLE
💡 Skip a node during privacy check

### ISSUE THREAD

**Issue by samueldmeyer** [DataDog/browser-sdk#2395]
**Is your feature request related to a problem? Please describe.**
Currently, I'm seeing performance issues while using [ApexCharts](https://apexcharts.com/) with DataDog RUM. On building a chart, something about the way nodes are updated in the chart causes DataDog RUM to run a privacy check for seconds, but this only happens in Chrome, not in Firefox or Safari. As a result, it seems I can use only one tool or the other.

I'm currently using version 4.47.0 of `@datadog/browser-rum`

**Describe the solution you'd like**
While fixing the performance issue would be nice, I would happily just let DataDog skip tracking that node. A `data-dd-privacy="skipped"` could work around the performance issue.

**Describe alternatives you've considered**
I have tried using `data-dd-privacy="hidden"` to skip that node, but the performance did not change.

**Comment by amortemousque** [comment]
Hello @samueldmeyer,
Thanks for the feedback. I tried with ApexCharts Line chart and vanilla JS but I could not reproduce the issue. Could you provide a minimal reproducible example?

**Comment by samueldmeyer** [comment]
After investigating more, I realized that the issue only occurred while I had DevTools open. At this point, I don't have a real issue to report, so I'm fine to close this issue if you want to.
