### ISSUE TITLE
🙏 Change configuration parameter during runtime

### ISSUE THREAD

**Issue by ryandegruyter** [DataDog/browser-sdk#2444]
**What are you trying to achieve and what is your issue? Please describe.**
We have a button in our UI to toggle between environments. What's the recommended way to change the "service" configuration parameter when clicking on a button?

**Comment by yannickadam** [comment]
Hi @ryandegruyter,

Once the SDK is initialized, you cannot change the configuration parameters. 
However, if you enable `trackViewsManually` in your configuration, you would be able to pass the relevant service when you start a new view: https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#override-default-rum-view-names

Let us know if that works for you!

**Comment by ryandegruyter** [comment]
does that mean we have to call 

datadogRum.startView({
...
})

on every page/screen?

**Comment by ryandegruyter** [comment]
@yannickadam What about the "env" parameter? How would I be able to change that?

**Comment by ryandegruyter** [comment]
@yannickadam any idea's?

**Comment by BenoitZugmeyer** [comment]
We don't support changing the `env` parameter for now. Can you work around this limitation by using `version` or `service`?

**Comment by ryandegruyter** [comment]
The thing is we want to connect with Traces and we need to match the env variable with same value as the backend.

**Comment by BenoitZugmeyer** [comment]
To my knowledge, there is no need to have a matching `env` to connect RUM events and traces. Could you make sure it does not work in your case? If you need further assistance, please [contact Datadog support](https://help.datadoghq.com/hc/en-us/requests/new).

**Comment by ryandegruyter** [comment]
Thanks, will create a ticket.
