### ISSUE TITLE
🙏 RUM client never initalized

### ISSUE THREAD

**Issue by dumaron** [DataDog/browser-sdk#2447]
**What are you trying to achieve and what is your issue? Please describe.**
I am trying to use Datadog RUM by following the guidelines provided both from public documentation and the private snipped provided when creating a new RUM project.

However, it seems that the RUM client never gets initialized. I have enriched the original initialization code to have more checks, and everything seems to run smoothly, except that the client never gets initialized.

```typescript
if (
  process.env.NEXT_PUBLIC_SERVICE_NAME !== undefined &&
  process.env.NEXT_PUBLIC_APPLICATION_ENVIRONMENT !== undefined &&
  process.env.NEXT_PUBLIC_DATADOG_APPLICATION_ID !== undefined &&
  process.env.NEXT_PUBLIC_DATADOG_CLIENT_TOKEN !== undefined
) {
  console.log('one') // <- confirms we enter the block
  console.log( // <- confirms the values are as expected
    process.env.NEXT_PUBLIC_DATADOG_APPLICATION_ID,
    process.env.NEXT_PUBLIC_DATADOG_CLIENT_TOKEN,
    process.env.NEXT_PUBLIC_SERVICE_NAME,
    process.env.NEXT_PUBLIC_APPLICATION_ENVIRONMENT,
  )
  try {
    datadogRum.onReady(console.log) // <- it is never triggered
    datadogRum.init({
      applicationId: process.env.NEXT_PUBLIC_DATADOG_APPLICATION_ID,
      clientToken: process.env.NEXT_PUBLIC_DATADOG_CLIENT_TOKEN,
      site: 'datadoghq.eu',
      service: process.env.NEXT_PUBLIC_SERVICE_NAME,
      env: process.env.NEXT_PUBLIC_APPLICATION_ENVIRONMENT,
      version: '1.0.0',
      sessionSampleRate: 1, // <- every event should be a send
      sessionReplaySampleRate: 1,
      trackResources: true,
      trackLongTasks: true,
      trackUserInteractions: true,
      beforeSend: console.log, // <- it is never triggered
    })
    datadogRum.startSessionReplayRecording() // <- I can also remove this, nothing changes
    console.log('two') // <- confirms that all the block is executed
  } catch (error) {
    console.error(error) // <- catches eventual errors, but never saw anything so far
  }
}
```

This is the client version: `4.50.0`. I have disabled all ad-blockers.

What am I doing wrong? Maybe some config elements are missing? Maybe the library doesn't work on localhost?

Thanks!

**Describe the solution you'd like**
I would like to see network calls inside chrome debugger tools, and to see live sessions and data on Datadog RUM interface

**Comment by BenoitZugmeyer** [comment]
```
      sessionSampleRate: 1, // <- every event should be a send
      sessionReplaySampleRate: 1,
```

Sample rates are values between `0` and `100`, so setting `1` will actually send events in 1% of user sessions. This could explain why you don't see any data being sent. Could you try to set `sessionSampleRate` to `100`, clear the `_dd_s` cookie (to make sure a new session is created), and check again?

See the [sampling documentation](https://docs.datadoghq.com/real_user_monitoring/guide/sampling-browser-plans/) for more details.

 Let me know

**Comment by dumaron** [comment]
As I expected, it was just something obvious that I wasn't able to see 🥲 . Thanks @BenoitZugmeyer !
I wrongly assumed that the rates were used as a stack to batch events, and not as percentages of events sent. Setting it up to 100 I can see everything is working as expected.

Closed, thanks again! 🎉
