### ISSUE TITLE
🐛 "Empty string passed to getElementById" printed to console in Firefox

### ISSUE THREAD

**Issue by valscion** [DataDog/browser-sdk#2463]
**Describe the bug**

Firefox displays a warning in developer tools console after an AJAX request has happened:

> Empty string passed to getElementById().

I have 99% confidence that this is the code which originates the problem:

https://github.com/DataDog/browser-sdk/blob/2871cc5c739084bb99a8aa7eac9cd0189201624b/packages/rum-core/src/domain/view/trackViews.ts#L307-L318

We have this code:

```js
import { datadogRum } from '@datadog/browser-rum';

function initializeDatadogRum() {
  datadogRum.init({
    // ... some options ...
  });
}

if (consentGivenForCategory('performance') || environment === 'test') {
  initializeDatadogRum();
}
```

When I stop the code calling to `datadogRum.init()`, I don't get the warning logged in Firefox

**To Reproduce**

1. Go to https://venuu.fi/en/catering?cuisine%5B%5D=3 with Firefox
2. Open developer tools
3. Click on some search filter, e.g. uncheck the "Desserts" option
4. See that the we get this warning printed in the console: "Empty string passed to getElementById()."

These steps trigger an AJAX request as well as change the current URL with `pushState`.

**Expected behavior**

I'd expect the warning to not be shown.

It might be enough to protect the call to `getElemenyById` with an empty string check.

**Comment by amortemousque** [comment]
Hello @valscion, 
Thanks for the feedback. A fixed has been released in version 5.1.0.
