### ISSUE TITLE
🙏 Github actions: "Field 'browser' doesn't contain a valid alias configuration" error fails a workflow when I'm trying to use "@datadog/browser-rum" lib. 

### ISSUE THREAD

**Issue by yauhenihrabun** [DataDog/browser-sdk#2491]
Hello.
Spent two and half days already to build the project with freshly installed "browser-rum" library using **Github actions**. It constantly failing workflow with the error below, despite library is actually been installed. And funny moment, that locally it works as expected (Configuration, Node and TS versions are the same):

```
ERROR in ./src/utils/datadog.ts 1:0-49
Module not found: Error: Can't resolve '@datadog/browser-rum/bundle/datadog-rum' in '../src/utils'
resolve '@datadog/browser-rum/bundle/datadog-rum' in '../src/utils'
  Parsed request is a module
  using description file: ../package.json (relative path: ./src/utils)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      ../src/utils/node_modules doesn't exist or is not a directory
     ../src/node_modules doesn't exist or is not a directory
      looking for modules in ../node_modules
        ../node_modules/@datadog/browser-rum doesn't exist
      ../node_modules doesn't exist or is not a directory
    ../node_modules doesn't exist or is not a directory
      /home/runner/work/node_modules doesn't exist or is not a directory
      /home/runner/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./src/index.tsx 18:0-25

webpack 5.88.2 compiled with 1 error in 49999 ms
Error: Process completed with exit code 1.
```

Error is illogical, as I should not have any external modules resolution inside of the "browser" field of package.json. At least, from my experience and docs from "browser-rum" lib. Please don't look at "@datadog/browser-rum/bundle/datadog-rum", I've tried to use way of importing for old TS version. With the modern way I experience exactly the same error.

You can find TS and Webpack configs below. They're fairly simple.

**TS config:**
```js
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": false,
    "jsx": "react",
    "pretty": true,
    "noUnusedLocals": false,
    "types": [
      "react",
      "node",
      "jest"
    ],
  },
  "include": [
    "src",
    "src/custom.d.ts",
    "babel.config.js"
  ],
}

```

**Webpack config:**

```js
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const TerserPlugin = require("terser-webpack-plugin");

module.exports = (env, argv) => {
	const devMode = argv.mode !== "production";

	return {
		entry: path.join(__dirname, "src/index.tsx"),
		output: {
			path: path.join(__dirname, "/staticresources/projectname"),
			filename: "static/js/[name]-[chunkhash].js",
			clean: true,
		},
		devtool: devMode ? "eval-source-map" : false,
		optimization: devMode
			? {}
			: {
				minimize: true,
				minimizer: [new TerserPlugin()],
				splitChunks: {
					chunks: "all",
				},
			},
		resolve: { extensions: [".tsx", ".ts", ".js", ".jsx"] },
		module: {
			rules: [
				{
					test: /\.(js|jsx)$/,
					exclude: /node_modules/,
					use: "babel-loader",
				},
				{
					test: /\.(ts|tsx)$/,
					exclude: /node_modules/,
					use: ["ts-loader"],
				},
				{
					test: /\.(js|jsx)$/,
					loader: "babel-loader",
				},
				{
					test: /\.(sa|sc|c)ss$/,
					use: [
						devMode
							? "style-loader"
							: MiniCssExtractPlugin.loader,
						"css-loader",
						"postcss-loader",
						"sass-loader",
					],
				},
				{
					test: /\.(svg)$/,
					loader: "url-loader",
					options: {
						limit: 2048,
						outputPath: "static/media",
					},
				},
			],
		},
		plugins: [
			new HtmlWebpackPlugin({
				template: "./src/index.html",
			}),
		].concat(devMode ? [] : [
			new MiniCssExtractPlugin({
				filename: "static/css/[name]-[contenthash].css",
			}),
		]),
	};
};

```

**And shortened version of the package.json:**

```json
{
  "scripts": {
    "build": "webpack --mode=production", // <-- command I'm trying to execute in Github actions
  },
  "dependencies": {
    "@datadog/browser-rum": "^5.1.0",
  },
  "devDependencies": {
    "typescript": "^4.7.3",
    "webpack": "^5.76.0",
  }
}

```

Due to some tech restrictions, we are not allowed to use CDN version of the lib, so please don't advise me to do that.

Kindly asking for help and thanks in advance.

**Comment by BenoitZugmeyer** [comment]
👋  I reviewed your configuration and tried a bit locally, but didn't reproduce.
To investigate your issue in GitHub Actions, could you add a few steps in the action, like:

```
ls -lR node_modules/@datadog/browser-rum/bundle
```

Also, maybe you are using a different package manager (Yarn, npm,...) or package manager version locally? Could you tell me which one do you use and which one do the GitHub action uses?

**Comment by yauhenihrabun** [comment]
We're using npm v8.19.4, node v16.20.2. Exactly the same versions locally and in Github actions.

I guess, I figured it out a bit. So, we're using actions/cache@v2 for caching `node_module` folder and `npm ci` for deps installing. If cache is empty, everything works*. But after cache is there, second run of workflow fails, because `@datadog` folder is not in `node_modules` folder, so it was not put to cache for some reason.

I'll try to figure it out, why the lib is not included in the cache.

*seems that part of the builds was failed due to missing line in the `webpack.config`:
 ```js
{
	test: /\.(js|jsx)$/,
	include: [
		path.join(__dirname, "node_modules/@datadog/browser-rum") // <-this line
	],
	loader: "babel-loader"
}
```
Without it, I experience exactly the same error, even though the library was installed (without cache). And yes, locally it works even without that line =)

**Comment by yauhenihrabun** [comment]
Big thanks for help, I finally figured it out. No issues in the `browser-rum` library =)

I'll keep the origin of our issue there, maybe it would help somebody.

We're using Github action lib for Jest test coverage which works incorrect (ArtiomTr/jest-coverage-report-action@v2). And it constantly replaces `node_module` folder with the one, installed with package.json from base branch (dev in our case). The lib need it to compare "original" test coverage with the new one. But it never reverts `node_module` from current branch.  And as `browser-rum` was not installed in the base branch (only in the current one) I constantly faced this issue from original message.

A bit more visual explanation, how our previous workflow worked:

1. Get GA cache
2. If cache is empty
    3. npm ci // <-- new lib successfully installed
4. Lint
5. Test // <-- node_modules from step 2 replaced with node_modules from dev branch
6. Build // <-- build failed because it cannot resolve new library
7. Save new cache // <-- caches node_modules installed by "Test" step
