### ISSUE TITLE
💡 RUM linking to traces when request is a form action

### ISSUE THREAD

**Issue by Noojuno** [DataDog/browser-sdk#2509]
**Is your feature request related to a problem? Please describe.**
While implementing RUM into our application, we found that RUM and APM tracing isn't linking correctly when hitting an endpoint from a form action property

```
<form action="/save.php">
    <input type="submit" value="Save" />
</form>
```
Something like the above will not correctly have trace information injected into the request as it's not a fetch/XHR request

**Describe the solution you'd like**
We would like for form actions to have the tracing information injected, even if behind a config option

**Describe alternatives you've considered**
We looked into whether it was possible to manually inject the required headers, but it didn't seem particularly feasible

**Comment by bcaudan** [comment]
Hi @Noojuno,

The form action request is handled by the browser directly and unfortunately we can't instrument it.
A workaround could be to trigger a XHR or fetch request on form submit.

**Comment by Noojuno** [comment]
@bcaudan Thanks for the update! I appreciate the suggestion, we were hoping to avoid having to edit our more legacy code, but we will have a look and see whether it's feasible or not :)
