### ISSUE TITLE
🙏 A question regarding Google's decision to phase out of using third-party cookies.

### ISSUE THREAD

**Issue by mariusgrybauskas** [DataDog/browser-sdk#2518]
**What are you trying to achieve and what is your issue? Please describe.**
https://developer.chrome.com/docs/privacy-sandbox/third-party-cookie-phase-out/?utm_source=techcomms&utm_medium=email&utm_campaign=FY24_Core#migrate

Google is preparing to phase out third-party cookies from it's browser. From what I understand this should impact datadog RUM ability to track user sessions. If so is there a plan to find a work-around or implement as google use Partitioned cookies with CHIPS?

**Describe the solution you'd like**
Just want to raise a question regarding Google's decision to phase out third-party cookies. 

**Describe alternatives you've considered**
From the link that I provided regarding third party cookies, Google suggests to use Partitioned cookies with chips.

**Comment by BenoitZugmeyer** [comment]
We are aware of this decision. Luckily our SDK does not use third party cookies, only first-party cookies, so we will probably be fine with this.

**Comment by provAlyssaKrueger** [comment]
@BenoitZugmeyer have you been able to make any progress here? Looking at integrating RUM in an iFrame widget / app

**Comment by BenoitZugmeyer** [comment]
Yes we are actively working on it.

**Comment by bcaudan** [comment]
Hi @mariusgrybauskas and @provAlyssaKrueger, 

we have just released browser-sdk@5.6.0 with a new config parameter allowing to set cookie as partitioned, with init configuration:

```js
usePartitionedCrossSiteSessionCookie: true
```

`_dd_s` cookie is set with `same-site=none;secure;partitioned`

Let us know if you have any feedback.
