### ISSUE TITLE
🙏 The accuracy of providing my own timing to `addTiming`

### ISSUE THREAD

**Issue by warpech** [DataDog/browser-sdk#2552]
Hi! Thanks for a great SDK! I have a question about RUM.

Here's what the docs at https://docs.datadoghq.com/real_user_monitoring/browser/monitoring_page_performance/ have to say about providing my own time to `addTiming`:

> If you are using an asynchronous setup, you can provide your own timing (**the number of milliseconds relative to the start of the current RUM view** or **the UNIX epoch timestamp**) as a second parameter.
> 
> For example:
> ```js
> document.addEventListener("scroll", function handler() {
>     //Remove the event listener so that it only triggers once
>     document.removeEventListener("scroll", handler);
> 
>     const timing = Date.now()
>     window.DD_RUM.onReady(function() {
>       window.DD_RUM.addTiming('first_scroll', timing);
>     });
> });
> ```

I think that this API is not perfect, because:

1. **the number of milliseconds relative to the start of the current RUM view** - it is hard to know the start of the current RUM view, especially when that is determined automatically. The snippet below shows how I do it today. Is this the best way?
   ```js
   beforeSend: (event) => {
     if (event.type === 'view') {
       // https://docs.datadoghq.com/real_user_monitoring/browser/data_collected/
       if (!eventDates.has(event.view.id)) {
         eventDates.set(event.view.id, event.date);
     }
   }
   ```
2. **the UNIX epoch timestamp** - this would be good if not for the fact that if I use `Date.now()`, that uses the user's clock which might not be in sync with Datadog clock. Does JS SDK use `Date.now()` internally?

**Describe the solution you'd like**

I would like to have certainty, that the times that I send to Datadog are correctly normalized. Perhaps, a good way to do it would be:
1. support sending the result of `performance.now()` to the `addTiming` method, AKA milliseconds since time origin
2. have a utility method in SDK that allows to convert `performance.now()` time to a UNIX epoch timestamp that is in sync with the SDK clock
3. a more detailed description in the docs about how to get accurate timing

**Describe alternatives you've considered**

I noticed that 0,001% of my users have very off dates reported by `Date.now()`, such as the year 1970, 2011, 2085. This is obviously a small number of users, but it got me thinking, how many of the users have their `Date.now()` time only slightly off?

Mostly, I want to avoid a problem that the dates provided using `addTiming(name)` and `addTiming(name, customTime)` would be out of sync.

**Comment by bcaudan** [comment]
Hi @warpech,

 > 1. the number of milliseconds relative to the start of the current RUM view - it is hard to know the start of the current RUM view, especially when that is determined automatically. The snippet below shows how I do it today. Is this the best way?

I don't get why you are using loading times for the start of the view 🤔
But indeed, providing a way to get the start time of the curent view could help for that but ideally we would like you to not have to do this kind of computations.

> 2. the UNIX epoch timestamp - this would be good if not for the fact that if I use Date.now(), that uses the user's clock which might not be in sync with Datadog clock. Does JS SDK use Date.now() internally?

The SDK is using Date.now() internally and the times are then normalized on the backend side to correct potential end user clock issues.
We are not using performance.now() since the underlying clock can be frozen by browsers when the tab is frozen or when the computer is going to sleep, which makes it unreliable in those conditions. 

> 1. support sending the result of performance.now() to the addTiming method, AKA milliseconds since time origin

I think that is here that we have an issue today, it works well for the initial view since its start is the time origin but it does not work for other views.
Fixing this behaviour would be a breaking change though, so we could fix it with the next major version of the SDK. 


> 2. have a utility method in SDK that allows to convert performance.now() time to a UNIX epoch timestamp that is in sync with the SDK clock

I think we would prefer you to not be bothered by that, to provide us either a `performance.now()` or a `Date.now()` and we will deal with it accordingly.

> 3. a more detailed description in the docs about how to get accurate timing

With previous answers, are there still some areas around how to get accurate timing that you'd like to get more details on?

> I noticed that 0,001% of my users have very off dates reported by Date.now(), such as the year 1970, 2011, 2085. This is obviously a small number of users, but it got me thinking, how many of the users have their Date.now() time only slightly off?

Date.now() slightly off is not really an issue for timing since we'll make the difference between times with the same error.
However for event dates, it is where the backend correction is helpful.
Dates reported with year 1970, 2011, 2085 seems odd to me though, could you open a datadog support case to have a look at those?

> Mostly, I want to avoid a problem that the dates provided using addTiming(name) and addTiming(name, customTime) would be out of sync.

I'd recommend you to provide an epoch timestamp for custom time.

**Comment by warpech** [comment]
> I don't get why you are using loading times for the start of the view 🤔

Thank you for pointing it out. I corrected the snippet above to use `event.date`.

> But indeed, providing a way to get the start time of the curent view could help for that but ideally we would like you to not have to do this kind of computations.

I agree with the ideal. But then it means that the ability to give relative time to `addTiming` should not be recommended, as long as the basis for the relative time is a kind of an internal detail of SDK.

> The SDK is using Date.now() internally and the times are then normalized on the backend side to correct potential end user clock issues.
> We are not using performance.now() since the underlying clock can be frozen by browsers when the tab is frozen or when the computer is going to sleep, which makes it unreliable in those conditions.

Thanks for the tip about computer sleep. It saved me from a long investigation about an issue that I observed! 

I have changed my code to not use the monotonic clock for long measurements.

My preferred way now is to use `Date.now()` and only adjust it using durations measured with `performance.now()`.

However, `Date.now()` also has an issue: If the user (or their OS) changes the "wall clock" (system time) during the session, the timestamps by `Date.now()` change accordingly. Does the SDK have any way of dealing with it? 

> I think we would prefer you to not be bothered by that, to provide us either a `performance.now()` or a `Date.now()` and we will deal with it accordingly.

👍 If you have a reliable way to calculate the clock drift, that would be the preferable way indeed.

> With previous answers, are there still some areas around how to get accurate timing that you'd like to get more details on?

Nope, that's all :)

> Dates reported with year 1970, 2011, 2085 seems odd to me though, could you open a datadog support case to have a look at those?

I now think that problem is unrelated and likely to be a bug on my side. Thanks!

**Comment by bcaudan** [comment]
> But then it means that the ability to give relative time to addTiming should not be recommended, as long as the basis for the relative time is a kind of an internal detail of SDK.

I agree, we'll clarify that in the doc and do a fix with the next major.

> My preferred way now is to use Date.now() and only adjust it using durations measured with performance.now().

If you are interested, you can have a look at how we are dealing with it ourself in [timeUtils](https://github.com/DataDog/browser-sdk/blob/main/packages/core/src/tools/utils/timeUtils.ts).

> However, Date.now() also has an issue: If the user (or their OS) changes the "wall clock" (system time) during the session, the timestamps by Date.now() change accordingly. Does the SDK have any way of dealing with it?

Indeed, for now, we don't do anything on the browser SDK side and let the backend apply a correction for this case. 

> I now think that problem is unrelated and likely to be a bug on my side. Thanks!

Thanks for raising the issue with addTiming and relative time 🙂
