### ISSUE TITLE
Support recording session replays when an iframe is used on the page

### ISSUE THREAD

**Issue by hmd-ai** [DataDog/browser-sdk#2556]
**Is your feature request related to a problem? Please describe.**
As part of the app that I'm building, some of the content is loaded within an iframe, however in the session replay this section of the app is always blank, despite actually having some content shown to the end user. For context the iframe is load from the same origin as the parent page.

**Describe the solution you'd like**
Record the content of the iframe, similar to the rest of the app.

**Describe alternatives you've considered**
Alternatively, exposing an API on the session replay, e.g. `beforeSend` to add meta data about the content of the iframe could be helpful.

**Comment by hmd-ai** [comment]
Related issue: https://github.com/DataDog/browser-sdk/issues/2168, however, I'm not sure if this one is for using datadog from within an iframe or just having an iframe in the main app.

**Comment by hmd-ai** [comment]
This [PR](https://github.com/DataDog/browser-sdk/pull/2092 ) was an attempt to support this but it has been closed without providing any reason, maybe @ThibautGeriz can provide some insights here.

**Comment by bcaudan** [comment]
Hi @hmd-ai, as pointed out in #2168, we don't support iframe during the recording of sessions, regardless of the origin of the iframe.

We still don't have an ETA to share on this front.

**Comment by hmd-ai** [comment]
@bcaudan Thanks for your response. I do have a couple of questions:

1. Since the main app has access to the iframe's content, is there anyway to add it the session replay using the sdk?

2. Is there any other way (other than session replay) to capture the iframe's content?

**Comment by bcaudan** [comment]
For now, we don't provide any workaround for any kind of iframe.
It is still something that we want to support but it is not in our current priorities.

**Comment by hmd-ai** [comment]
For context the underlying library `rrweb` already supports iframe (even cross-origin), therefore other providers (e.g. sentry) already have this feature.

**Comment by mcheung610** [comment]
@bcaudan Do you know if this feature is on the roadmap?
