### ISSUE TITLE
Upgrade from v4 to v5 causing POST rejections from RUM & LOGS

### ISSUE THREAD

**Issue by hipitihop** [DataDog/browser-sdk#2558]
**What are you trying to achieve and what is your issue? Please describe.**
We have been successfully using the SDK 4.50.1 (npm dependency) and earlier in from our Clojurescript apps for considerable time. Attempting to upgrade to the 5.x series, causes POST rejected issues from both RUM & LOGS without a clear indication of the cause.

We have followed the v4 to v5 upgrade guide to change init parameters and API changes etc.
The browser console and devtools network errors don't indicate what the problem is.
Comparing to a working app, the request/intake URLs seem the same e,g,
`https://logs.browser-intake-datadoghq.com/api/v2/logs`

Platform Chrome Version 120.0.6099.129 (Official Build) (64-bit) although oour deployment target is Chrome 87

Before we spend any further time on this and dig deeper,  perhaps creating a minimal repo for you to reproduce, we'd like to eliminate anything obvious like JS/ES language level requirements or the like that is causing the incompatibility.

We would appreciate a pointer or suggested path to investigate.

![image](https://github.com/DataDog/browser-sdk/assets/4626024/8e05d452-a42d-40e6-8759-0105946a8727)

**Comment by bcaudan** [comment]
Hi @hipitihop,

Is there any additional information from the browser debug tools, either on network or console panel? 
On v5 there was a [change on intake domains](https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#intake-domains), is there any CSP that could block those requests?

**Comment by hipitihop** [comment]
@bcaudan 
> Is there any additional information from the browser debug tools, either on network or console panel? 

No real extra details can be gleaned from console. Above screenshot is network panel, and the request headers and payload look normal, but nothing shows in the response.

> On v5 there was a [change on intake domains](https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#intake-domains), is there any CSP that could block those requests?

We don't explicitly set any CSP. I experimented by adding CSP meta to the app via `<meta>` in its HTML. Because the app makes other calls outside its self domain, then those requests started to fail, but the network panel clearly showed them as CSP failures, whereas the RUM & LOGS post don't show them as CSP failures. I saw the mention of new intake domains, but when I compare a working app using 4.5.1 vs 5.6.0, the request domain looks the same https://browser-intake-datadoghq.com/api/v2/ 
So I find this puzzling. something subtle I'm not seeing yet. I'd be surprised despite same URLS between working app and failing app, if it was firewall or something else getting in the way, but will do some more tests there.

Any other thoughts ?

**Comment by bcaudan** [comment]
Does the requests even reached the server?
From the network panel, can you see response headers or server timing?

Does the request still fail if you copy it as curl and execute it from a terminal? or copy as fetch and execute it from a dummy web page?
Does it still fail if you connect to a network outside of your firewall?

If none of those checks allow you to troubleshoot the issue, I'd recommend you to reach out to [datadog support](https://www.datadoghq.com/support/) and mention this issue.
We could ask you for more specific debug information there.

**Comment by hipitihop** [comment]
> Does the requests even reached the server? From the network panel, can you see response headers or server timing?
> 
> Does the request still fail if you copy it as curl and execute it from a terminal? or copy as fetch and execute it from a dummy web page? Does it still fail if you connect to a network outside of your firewall?
> 
> If none of those checks allow you to troubleshoot the issue, I'd recommend you to reach out to [datadog support](https://www.datadoghq.com/support/) and mention this issue. We could ask you for more specific debug information there.

@bcaudan Apologies for the tardy response. I have had to park this upgrade due to other pressing tasks, but I will come back with more details and tests in a week or so

**Comment by bcaudan** [comment]
Feel free to re-open if you can provide us more details.
