### ISSUE TITLE
Opt-in approach to action tracking

### ISSUE THREAD

**Issue by dariodevito** [DataDog/browser-sdk#2573]
**Is your feature request related to a problem? Please describe.**
Our applications present potentially sensitive data and we are not able to expose this to Datadog. In enabling RUM actions; the SDK's programmatic generation of an Action name may inadvertently expose sensitive data from a HTML element.

**Describe the solution you'd like**
I would like the ability to only track actions relating to elements that I have explicitly chosen. Preferably this could be inferred by virtue of setting the `data-dd-action-name` attribute. 

For example:

- New SDK configuration option `trackUserInteractionsExplicitly`
- If `true` - only track actions for elements that have the `data-dd-action-name` attribute set
- If `false` - use existing behaviour 

**Describe alternatives you've considered**
I have looked at setting the `data-dd-action-name` name explicitly for all HTML elements. However, the surface area for error is too large and unmanageable. Particularly if introducing third party UI components.

I have looked at using the `beforeSend` API, however the event & context to not offer enough information to ascertain whether the HTML element had a `data--dd-action-name` property. The potentially sensitive data is also unstructured and therefore I cannot apply pattern driven redaction rules either.

**Comment by amortemousque** [comment]
Hello @dariodevito,
Thanks for you feedback! 
This is a topic we are working on. There is no ETA for now but we will keep you posted.
By the way, in the mean time, you could use [beforeSend API](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#enrich-and-control-rum-data) to mask sensitive data on your RUM actions.

**Comment by dariodevito** [comment]
@amortemousque does the beforeSend API offer a way for us to check if the `data-dd-action-name` attribute has been set? I can't see that from the docs. 

I.e. I'd like to write behaviour like this sudo code:

```
datadogRum.init({
    ...,
    beforeSend: (event) => {
        // discard events that don't have a `data-dd-action-name` explicitly set
        if (`data-dd-action-name` IS NOT SET) {
           return false;
        }
    },
    ...
});
```

**Comment by dariodevito** [comment]
I can see that the context object includes the source element, so we'll try using that.
