### ISSUE TITLE
Core Web Vitals INP - Immediate Feedback - loading spinners / progress bar / acknowledgement pop-ups etc

### ISSUE THREAD

**Issue by patrjst** [DataDog/browser-sdk#2583]
**Is your feature request related to a problem? Please describe.**
I'm trying to identify optimization opportunities for a web application using DataDog RUM to be ready for INP in 2024. Experimenting on a staging environment with many running testflows it looks like it does not have any visible effect on the INP calculation if I try to mitigate long running tasks for interactions by providing immediate feedback to the user. What I tried:

- loading spinner covering the whole viewport
- loading spinner next to single controls that might take long

E.g. in this staging environment I was able to affect the RUM metrics by artificially increasing response time for a single interaction (far more than 200ms, tested with 500ms, 1s, 5s). Expectation was, that this, as one of the overall slowest interactions but still part of quite many user flows, must affect the INP calculation. And it does. The INP metrics just incease in my DataDog dashboard. I can also verify this by manually clicking through userflows containing this interaction in the Chrome Web Vitals extension. But when I add a Loading spinner - Web Vitals Extension in Chrome shows improved times for the interaction and INP calculation, while Datadog still shows a bad INP (due to artificially extended loading times for this interaction).

For the the RUM script I'm using v5.8.0

I'm aware that the overall INP calculation depends on all the user flows and might be affected by the  interactions with worst performance, even if all other interactions are quite ok. This is why I tried to verify the negative case, having one very long interaction in place that is affecting the measurement negatively.
 
 
**Describe the solution you'd like**
The INP calculation should take into account the usage of "immediate feedback" provided to a user, so that long loading interactions can be mitigated by taking measurements like progress bars, loading spinners, pop-ups, to cover the same behavior like tools as Web Vitals extension is showing, and probably Google will apply while collecting performance profiles as field data.

**Describe alternatives you've considered**
A clear statement about DataDog RUM INP metrics VS Google INP data collection, would be beneficial.

**Comment by bcaudan** [comment]
Hi @patrjst,

Our INP implementation aims to be as close as possible as the [google one](https://github.com/GoogleChrome/web-vitals/blob/main/src/onINP.ts).
In order to dig deeper into that, could you share a case where our implementation behaves differently?
