### ISSUE TITLE
🐛 developer-extension does not load: "It may have been moved, edited or deleted"

### ISSUE THREAD

**Issue by sombrerosheep** [DataDog/browser-sdk#2608]
**Describe the bug**
After running the steps in the README for the developer-extension I get a sad face and the text "It may have been moved, edited, or delete". Inspecting the dev tools for the extension gives the following console error:

![image](https://github.com/DataDog/browser-sdk/assets/9325163/ec97cfbd-39f8-4e58-b6b5-2f96a1b58620)

> - Main._createAppUI: 4.757080078125 ms   main.js:1
> - Main._showAppUI: 53.14892578125 ms   main.js:1
> - Main._initializeTarget: 1.118896484375 ms   main.js:1
> - Main._lateInitialization: 1.803955078125 ms   main.js:1
> - Ignoring unauthorized client request from null   extensions.js:1
>    registerExtension @ extensions.js:1

![image](https://github.com/DataDog/browser-sdk/assets/9325163/52853faa-c85f-4726-b859-64a34b250428)

**To Reproduce**

1. Follow the instructions for the [developer-extension](https://github.com/DataDog/browser-sdk/blob/main/developer-extension/README.md)
2. Load a RUM enabled application in the browser
3. Open browser tools and select the "Browser SDK" tab

**Expected behavior**
The extension to load and display RUM information.

**Environment:**
browser: Google Chrome Version 121.0.6167.160 (Official Build) (arm64)
system: Macbook Pro M1
os: macOS 12.6.5
yarn version: 1.22.21

**Comment by amortemousque** [comment]
@sombrerosheep,
Thanks for your feedback. I can't reproduce the issue. Can you give more context:
- Have you tried on different RUM enabled applications?
- What is the version of the developer extension you're using?
- Is your browser managed by your company which could have some restrictions on extensions?
