### ISSUE TITLE
🙏 How to customize device.type ?

### ISSUE THREAD

**Issue by arichard-info** [DataDog/browser-sdk#2620]
Hello ! 

I have an application that is used directly on the web and also in a webview, in native applications (IOS and Android).
I'm looking for the best way to identify this on datadog.

In the native application, the webview sets a custom user-agent : "app-android" or "app-ios". So I guess in `device.type`, this sessions are in "Other".

How can I identify these use cases ? 

Is there a way to have `device.type=app-android` or `device.type=app-ios` ?

**Comment by amortemousque** [comment]
Hello @arichard-info,
To my knowledge, we can't have custom device type. However you could directly filter based on the user-agent: `@session.useragent: app-android`. 
Another approach could be to use the dedicated native [IOS](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/ios/?tab=cocoapods) and [Android](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/android/?tab=kotlin) SDKs which also allow to collect webview RUM data. Then you can filter events coming from webviews like so: `source:browser @os.name:iOS`

**Comment by bcaudan** [comment]
Hi @arichard-info,

 > @session.useragent should be available in Datadog ? 
 
It seems that the raw user agent is on the `@session.useragent` attribute on all events except session events and it is not documented 😕.
We'll try to clarify that.

**Comment by arichard-info** [comment]
Hi @bcaudan 

Thanks for your response
If I understand well, i'm supposed to find the attribute `@session.useragent` here ? 
![Screenshot 2024-03-11 at 11 07 02](https://github.com/DataDog/browser-sdk/assets/56544866/4cbade0c-b7c4-4b42-859a-80e6238bae58)

I'm curious to have some documentation on this because I can't find it 😕

**Comment by bcaudan** [comment]
The attribute should be on the view events but there is no default facet on it, which prevent you from selecting it in the group by select.

From a view event side panel > attributes > JSON, you should be able to see the `@session.useragent` attribute and create a facet from it.
