### ISSUE TITLE
🐛 Wrong city name

### ISSUE THREAD

**Issue by SerhiiKorolik** [DataDog/browser-sdk#2661]
**Describe the bug**
Noticed on the UI that when I'm using the Ukraine/Kyiv timezone there is misspelled  "Kiev" is used.

Note:
Ukrainians call their capital “Kyiv” (kee-yiv), the spelling, a transliteration of the Ukrainian Київ. The Russian version is “Kiev” (kee-yev)

**To Reproduce**

1. Go to 'Monitors'
2. Click on any monitor
3. See the message at the top of the page: 'Monitor status since 1 minute ago (20 Mar, 12:00:59 Europe/Kiev)'

**Expected behavior**
I'd like to see it as ''Monitor status since 1 minute ago (20 Mar, 12:00:59 Europe/Kyiv)''

P.S. If this is the wrong project to create the bug in then please let me know where I can move the bug. Thanks!

**Comment by amortemousque** [comment]
Hello @SerhiiKorolik,
Thanks for the feedback. The timezone names are not computed by the browser SDK but somewhere else in the Datadog stack. Please [contact Datadog support](https://help.datadoghq.com/hc/en-us/requests/new) for further assistance regarding this matter.
