### ISSUE TITLE
only one between datadogRum and datadogLogs is available at a time 

### ISSUE THREAD

**Issue by smellai** [DataDog/browser-sdk#2699]
**Describe the bug**
Initialising both datadogRum and datadogLogs only makes one of them work

**To Reproduce**
Set up both:
`datadogRum.init`
and
`datadogLogs.init`
in the same web application.

They both use the **_dd_s** cookie and they override it, so you will see only RUM events or log events happening.

**Expected behavior**
I can both send RUM events and logs to my datadog dashboard

**Comment by N-Boutaib** [comment]
Hello @smellai

This is a weird and unexpected behaviour. Could you please provide more details about your use-case and how you perform the initialisation ?

**Comment by smellai** [comment]
```
"@datadog/browser-logs": "5.10.0",
"@datadog/browser-rum": "5.10.0"
```

```
import { datadogLogs } from '@datadog/browser-logs';
import { datadogRum } from '@datadog/browser-rum';

datadogLogs.init({
    clientToken: 'abc',
    service: 'my-service',
    env: 'stable',
    sessionSampleRate: 100,
    version: 'x.y.z',
    forwardErrorsToLogs: true,
    site: 'datadoghq.eu',
  });

datadogRum.init({
    applicationId: 'app-id'
    clientToken: 'abc',
    service: 'my-service',
    env: 'stable',
    sessionSampleRate: 100,
    version: 'x.y.z',
    site: 'datadoghq.eu',
    trackUserInteractions: true,
    trackSessionAcrossSubdomains: true,
  });
```

I alternatively see a value that starts with
`logs=1` inside the _dd_s cookie and in this case if I print `window.DD_LOGS.getInternalContext()` in the console I get an object with a sessionId and if I try to print `window.DD_RUM.getInternalContext()` I get undefined.

OR

I see a value that starts with
`rum=number` inside the _dd_s cookie and in this case if I print `window.DD_LOGS.getInternalContext()` in the console I get undefined and if I try to print `window.DD_RUM.getInternalContext()` I get an object with several properties.

**Comment by N-Boutaib** [comment]
Hello 👋 
I set app a small app with the configuration you gave [here](https://codesandbox.io/p/sandbox/rum-sdk-test-s7n9fs). Tell me if you could reproduce it **locally** (the cookie is not set on the sandbox, so the sdk is not properly initialised).

** trackSessionAcrossSubdomains** option should have the same value for logs configuration and rum configuration (cf. [docs](https://docs.datadoghq.com/real_user_monitoring/browser/#initialization-parameters))

**Comment by smellai** [comment]
Thanks, apparently that not-matching flag was the source of the issue!

**Comment by N-Boutaib** [comment]
Good to hear that it solved. Closing the issue ✔️
