### ISSUE TITLE
💡 More attribution data for event timings and core web vitals

### ISSUE THREAD

**Issue by niallwingham** [DataDog/browser-sdk#2716]
The web-vitals reference implementation includes an [attribution build](https://github.com/GoogleChrome/web-vitals?tab=readme-ov-file#attribution-build) with useful data.

Datadog includes some of this data but not all.  For example, INP events have a selector path to the interaction target, but not the time the interaction happened or the current load state of the document.  This would be helpful to have when diagnosing e.g. if an interaction is slow on its own, or if it just happened to be slow because the document was still loading.

(Given a single Datadog view with INP data, you can usually _kinda_ tell by looking at the actions tab and the overall timeline.  But it would be better to have it as actual data points on the view, so you could use them as a facet when searching and graphing.)

Based on the reference implementation, it looks like it's not too hard to implement (easy for me to say, ha).  Some of this data is already available on the underlying `PerformanceEventTiming` and is [just copied over](https://github.com/GoogleChrome/web-vitals/blob/21edecf75b20d09b5a977d6fa8bf243c5ee75619/src/attribution/onINP.ts#L51-L53).  The load state needs to be [cross referenced with a navigation timing](https://github.com/GoogleChrome/web-vitals/blob/21edecf75b20d09b5a977d6fa8bf243c5ee75619/src/lib/getLoadState.ts#L20-L51).

Full documentation on web-vital's attribution data is [here](https://github.com/GoogleChrome/web-vitals?tab=readme-ov-file#attribution).

**Comment by amortemousque** [comment]
Hello @niallwingham,
Thanks for your feedback! We've planned to add the timestamp of INP and CLS. I'll keep you updated. 
As for the soft navigation, we are also very interested in this feature! As it's still experimental under feature flag, we haven't planned to integrate it yet, but we are tracking it closely.

**Comment by amortemousque** [comment]
Hello @niallwingham, 
We are now collecting INP and CLS timestamp. They can be queried as follow: `@view.interaction_to_next_paint_time` and `@view.cumulative_layout_shift_time`.

**Comment by niallwingham** [comment]
Fantastic, thank you! 🙇🏻
