### ISSUE TITLE
🙏🏻 Does the sampleRate of native and webview affect each other?

### ISSUE THREAD

**Issue by devhyunseok** [DataDog/browser-sdk#2736]
### Question

👋🏻 Hello!

I'm asking because it seems like not all traffic is collected in the webview when the iOS rum sampleRate is set to 10% and the webview sampleRate is 100%. 

I'm curious if the sampleRate of native sdk (dd-sdk-ios) and browser sdk(browser-rum) affect each other.

**Comment by bcaudan** [comment]
Hi @devhyunseok,

Indeed, in a webview context, only the native sample rate is used to create sessions and send data to datadog servers.
When a native session is tracked, we ensure that the webiew is also tracked and then don't take into account the sample rate configured on the browser SDK side.

**Comment by devhyunseok** [comment]
Thank you for your answer, @bcaudan 

If the session is not included in native sampling (not tracked), isn't all browser traffic untracked?

I'm also curious if there's a way to take browser and native sampling independently.

**Comment by bcaudan** [comment]
> If the session is not included in native sampling (not tracked), isn't all browser traffic untracked?

In a webview context, browser data is handled by the native SDK before being sent to datadog servers.
So if the session is not tracked on the native side, browser data is then not sent by the native SDK.

> I'm also curious if there's a way to take browser and native sampling independently.

What would you like to achieve?

**Comment by devhyunseok** [comment]
> What would you like to achieve?

We are using multiple webviews within a single app, each with its own browser-rum sdk
I asked because each web view has different user traffic, so I wanted to define each sampling.

**Comment by bcaudan** [comment]
> I asked because each webview has different user traffic, so I wanted to define each sampling.

Do you mean the websites have different user traffic outside of the webview usages?
The browser SDK sampling rate is correctly taken into account when the website is not in a webview inside an application instrumented with a native SDK.

**Comment by devhyunseok** [comment]
We are using multiple webviews with different domains in one app. (It's not outside the webview context)

Each webview in the app has a different frequency of use by users, so I tried to separate sampling for each webview, but rather than dividing the webview from the app, I will think again on the basis of one app.

Thank you for your kind answer, it was very helpful.

**Comment by devhyunseok** [comment]
> Any concern that would make you want to have additional sampling on the webview data?

Let's suppose that one app processes 'A webview with a lot of user use' and 'B webview with a small user use' as sampling of the same native app.
At this time, I am concerned that it will be difficult to obtain the desired amount of performance indicators for webview B compared to webview A.

Increasing the sampling of the app could solve the problem, but it seems like it would result in an overall increase in costs 😭
I thought it would be helpful to get the desired amount of data by adjusting sampling for each webview.

**Comment by bcaudan** [comment]
If I understand correctly, with a low sampling on the host app, you may not get a lot of data for the webviews with a low traffic.
Indeed, for now you would need to increase the overall sampling for having more visibility on it but we are working on providing more dynamic sampling capabilities that should help you to have more control on that.
No ETA to share yet but stay tuned!

**Comment by devhyunseok** [comment]
> Indeed, for now you would need to increase the overall sampling for having more visibility on it but we are working on providing more dynamic sampling capabilities that should help you to have more control on that.
No ETA to share yet but stay tuned!

Thank you. I'm using the datadog product so well and I'll look forward to it in the future.
I will close the question, thank you. 😄
