### ISSUE TITLE
🙏 Document how action target name is computed

### ISSUE THREAD

**Issue by blchelle** [DataDog/browser-sdk#2763]
Hi Datadog folks,

**What are you trying to achieve and what is your issue? Please describe.**

I apoligize in advance if this documentation already exists. Unfortunately I wasn't able to find anything for this. I was looking at [these docs](https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/#declare-a-name-for-click-actions) and discovered that click actions can have their name explicitly defined if the `data-dd-action-name` attribute is present on the element. I also noticed that you can override the attribute name if you want to use something other than `data-dd-action-name` to explicitly define your action names.

Unfortunately I couldn't find anything about how the action names are computed if neither of those attributes are present.

**Describe the solution you'd like**

I was able to eventually find my answer in the source code around [here](https://github.com/DataDog/browser-sdk/blob/6db95af143adf9054eb7871cbbfc07c7854b5418/packages/rum-core/src/domain/action/getActionNameFromElement.ts#L18-L22). However, I believe that this is something that would be valuable to document on that same page I referenced earlier so that future customers don't need to dig into the source code to find this.

**Describe alternatives you've considered**

N/A

**Comment by N-Boutaib** [comment]
Hello @blchelle 
Thanks for reaching out. Indeed, we don't have documentation about other alternatives to compute action names if not explicit naming is provided.

It does make sense to have those alternative documented, thing that we'll do asap. Yet, we do encourage you to add explicit action names to have full control over them.

**Comment by blchelle** [comment]
Thank you, @N-Boutaib. We're working on adding the explicit action names to our project. However, it is a very large project and adding the action names everywhere will take us quite some time. So for the time being we just wanted to understand how the current action names are computed.

I think we have a pretty good grasp on it now, but having this explicitly in the docs would be helpful.

Thanks Again!

**Comment by cy-moi** [comment]
Hi @blchelle , we updated [the documentation](https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/#how-action-names-are-computed) to include how the action names are computed.
