### ISSUE TITLE
Nuxtjs application not loading Datadog RUM properly and no data is reported to Datadog

### ISSUE THREAD

**Issue by eduardocampano** [DataDog/browser-sdk#2773]
Using `@datadog/browser-rum` version `5.16`

**What are you trying to achieve and what is your issue? Please describe.**
Monitor my nuxtjs web application with Datadog RUM, I'm not able to load the library properly.

**Describe the solution you'd like**
I created a nuxtjs application with no SSR. I followed the instructions to use `@datadog/browser-rum` package. I created a simple nuxtjs plugin which initializes datadog RUM as follows:

```
import { DefaultPrivacyLevel, datadogRum } from '@datadog/browser-rum';

export default defineNuxtPlugin(() => {
    const config = useRuntimeConfig(); 
    const { ddApplicationId, ddApplicationToken, ddVersion, ddEnv } = config.public;
    datadogRum.init({
        applicationId: ddApplicationId,
        clientToken: ddApplicationToken,
        site: 'us3.datadoghq.com',
        service: 'my-app',
        version: ddVersion,
        env: ddEnv,
        sessionSampleRate: 100,
        sessionReplaySampleRate: 100,
        trackUserInteractions: true,
        trackResources: true,
        trackLongTasks: true,
        defaultPrivacyLevel: DefaultPrivacyLevel.MASK_USER_INPUT,
    });
    datadogRum.startSessionReplayRecording(); 
});
```
Application starts, I verified `datadogRum.init()` method is executed with the expected parameters, no errors are logged in the browser console, no data is sent to datadog and there is no network activity connected to datadog in the browser.

**Describe alternatives you've considered**
I followed the troubleshooting guide instructions. When checking `window.DD_RUM.getInternalContext()` in the browser console, I get `undefined`. Doing `window.DD_RUM.init({ .... })` from the console once the app is loaded works and I start seeing the session in datadog website. Also I confirmed network activity to datadog endpoints from the browser. I tried doing `window.DD_RUM.init({ ... })` from the plugin but I get exactly the same behavior as with `datadogRum.init()`

**Comment by N-Boutaib** [comment]
Hello 👋 

Your config looks good to me as long as data from public config is defined.
However, session replay recording will start automatically (as long as you don't include `startSessionReplayRecordingManually: true` in the config). Could you remove `datadogRum.startSessionReplayRecording()` from the plugin and give a try ?

**Comment by eduardocampano** [comment]
ok, the problem was the `version` being a numeric type, I updated to version `5.18` and I was able to see an error about it in the browser console. Once the version is a string, it started working as expected. Thank you very much for your help.
