### ISSUE TITLE
No way to check if init has already been called or to catch/ignore resulting console error.

### ISSUE THREAD

**Issue by adamond** [DataDog/browser-sdk#280]
Please let me know if I'm missing something but:

- There doesn't appear to be a way to check if `datadogLogs.init()` has already been called, and `console.error()` is called if it had already been initialized. However, since we're sending our console errors to datadog, this leads to our logs getting spammed by these error messages that we don't care about. Ideally, there would be something on the datadogLogs API that we could check before calling `init` to see if it has already been called.

- There's no good workaround at the moment for suppressing these console errors, because they're using `console.error()` rather than `throw` - presumably this is because you don't want to halt execution, which is understandable - however, it'd be nice in this case if there was a way to configure the logger to filter out certain console errors. If such functionality already exists, that would be something that would be helpful to highlight in the documentation. 

Thanks!

**Comment by bcaudan** [comment]
Hi @adamond! 
Indeed, there is no API to check if the sdk is already initialized.
We chose to send error because multiple calls to init was related to sdk setup mistakes.
In order to avoid these errors, I would suggest to add the datadog init call in some bootstrap phase of your page that happens early and only once.
If it is not possible in your case, could  you give me extra details on your setup?

**Comment by Sangrene** [comment]
I must agree with @adamond on the usefulness of a `isInit` function.

Actually, a workaround I use is to add an abstraction layer on top of browser-logs, and then use a singleton pattern on this abstraction.

**Comment by bcaudan** [comment]
Hi @Sangrene

Could you give me some details on your setup?
It would help me to understand your need and see if adding a `isInit` function is the best way to go or if we could find an alternate strategy.

Thanks!

**Comment by donovanclarke** [comment]
+1 for this.

**Comment by Sangrene** [comment]
> Hi @Sangrene
> 
> Could you give me some details on your setup?
> It would help me to understand your need and see if adding a `isInit` function is the best way to go or if we could find an alternate strategy.
> 
> Thanks!

Hi @bcaudan 

I have an application divided in multiples containers. Each containers has its own bootstrap function, sometimes initialising _browser-logs_. A user might (or might not) navigate between containers, triggering the associated bootstrap function. When navigating between two containers which have initialised _browser-logs_, the initialise function is therefore called twice.
As I said, I use an abstraction layer and a singleton pattern to workaround this.

**Comment by bcaudan** [comment]
Thanks for the details, it makes sense.

Would an init option be more convenient to suppress the `already initialized` error?

something like:

```js
datadogLogs.init({
  ...
  silentMultipleInit: true,
  ...
})
```

**Comment by Sangrene** [comment]
Yes totally, it would prevent browser-logs from sending its own error message to datadog !

**Comment by mquentin** [comment]
Hey, a new option has been added to the `datadogLogs.init()` : [silentMultipleInit](https://github.com/DataDog/browser-sdk/blob/master/packages/rum/README.md). If you turn this optional boolean on, the multiple init will still be aborted but will not trigger any `console.error`.
