### ISSUE TITLE
💡 Support for "pending" for trackingConsent

### ISSUE THREAD

**Issue by dlmr** [DataDog/browser-sdk#2819]
Is it possible to enable support for `pending` similar to what is [available on iOS](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios/?tab=swift#set-tracking-consent-gdpr-compliance) for `trackingConsent`. As this does not exist for the [Browser SDK](https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm#user-tracking-consent) as far as I can tell.

The use case is that we only want to send data to Datadog that we have consent to use but we don't want to miss anything happening before the user have taken an action with the consent screen.

**Comment by BenoitZugmeyer** [comment]
Hello and thank you for your feedback.

When we implemented consent management in the Browser SDK, our legal team told us that collecting data in memory prior to consent was forbidden by privacy regulations as GDPR. This is why we didn't implement `pending` in the first place.
