### ISSUE TITLE
sourcemap support?

### ISSUE THREAD

**Issue by d3ming** [DataDog/browser-sdk#284]
Does the browser-sdk support sourcemaps?  I don't see anything about this in the docs and the only mention of it seems to be from another datadog project (https://github.com/DataDog/dd-trace-js/issues/48#issuecomment-383211333).

Thanks in advance, this is a pretty key feature for my team to consider adoption!

**Comment by kokliKo** [comment]
Hey! We don't support source maps today, but we plan to work on it in the next few weeks/months (we don't have an ETA to share yet).
Thanks!

**Comment by ken5scal** [comment]
We are looking forward to this

**Comment by rthreei** [comment]
@kokliKo I want to capture a use case for source maps.

We use `@datadog/browser-logs` to record errors and stack traces.  Unfortunately the stack trace for vendor code is minified, making debugging difficult.  Ideally we can tell Datadog where to pull the source map from, or we could push the source map into Datadog upon deploys.

**Comment by kokliKo** [comment]
@rthreei Ok, thanks for sharing :)
Once we release this feature it should cover this use-case!

**Comment by fc** [comment]
@kokliKo just curious if you have a rough ETA on this? it sounds like you may be in the middle of working on this.

**Comment by kokliKo** [comment]
Hey @fc No precise ETA yet, but yes, we're currently working on it, and it should be available in beta for RUM users in the next few weeks.
We're trying to accelerate this one as fast as we can :)

**Comment by rajington** [comment]
Thanks @kokliKo and @hdelaby, DataDog browser support is very exciting and impressive so far, I completely understand not having a concrete ETA for this.

It is convenient to subscribe to issues and get notified when they're resolved. Is that something you'd want to support in this repo (and re-open this ticket)? Or do we just subscribe to this repo's releases or DataDog's blog?

**Comment by bcaudan** [comment]
Thanks for the feedback @rajington!

I reopen this one to avoid duplicates and allow users to easily follow this topic.
We will ping here if there is any new info on it.

**Comment by JoshEngebretson** [comment]
"We're trying to accelerate this one as fast as we can", great.  It will be very nice to be able to read callstacks :)

**Comment by josh-engebretson** [comment]
"We're trying to accelerate this one as fast as we can", great :)  Really looking forward to being able to read callstacks! 🎈

**Comment by aleksandrlat** [comment]
Really waiting for this!

**Comment by breakingthebuild** [comment]
This is a much needed feature!

**Comment by gowrinathj** [comment]
Looking forward for this!

**Comment by litari** [comment]
I really want this feature as well!

**Comment by delfer** [comment]
@kokliKo hello! We are also interested in it. How to be a beta tester?) Thank you.

**Comment by rajington** [comment]
FYI, Dash 2020 announcement post makes a [direct mention](https://www.datadoghq.com/blog/dash-2020-new-feature-roundup/#error-tracking) about SourceMap support.

> Also, just a reminder, that the best way to show interest without spamming everyone else interested is to emoji react on the parent issue. Currently there's no way to customize notifications beyond when the ticket is opened and closed, so no way to see updates.

**Comment by PinPinIre** [comment]
Are there any plans to also enable this for Browser Logs? It would really help us to identify the cause of errors faster and ultimately reduce our error rate.

**Comment by bcaudan** [comment]
Hi @PinPinIre,

We definitely plan to support source maps for browser logs too, we should make progress on that front in the coming months.

**Comment by KrustyC** [comment]
I am having issues with the sourcemaps. In particular I followed the step on the guide and the sourcemaps seem to be uploaded correctly 
![image](https://user-images.githubusercontent.com/20644593/122239556-eec31a00-ceb8-11eb-87ec-36bdf5243b0b.png)

When I log onto RUM metrics though, I still see only the logs from the minified data. I thought the issue was due to the version not being set properly, but just to test, I have hardocded the version both on the upload command and the `init` function, but still no luck. I am not sure how I can debug this further, but I would really like to solve this, as I think this is a great feature!

Would anyone able to help?

**Comment by bcaudan** [comment]
Hi @KrustyC,

From my understanding, `version` and `service` will be needed to match a RUM error stacktrace to an uploaded sourcemaps.
If everything looks good on your side, [Datadog support](https://www.datadoghq.com/support/) would be able to help you.

**Comment by bcaudan** [comment]
State of this request:
- done on RUM, cf https://github.com/DataDog/browser-sdk/issues/284#issuecomment-672981307
- planned on logs, cf https://github.com/DataDog/browser-sdk/issues/284#issuecomment-788966608

Issues or improvements on this topic will most likely not be handled in this repository.
For:
- sourcemaps upload, see https://github.com/DataDog/datadog-ci
- any other request on sourcemaps, please reach [Datadog support](https://www.datadoghq.com/support/) directly.
