### ISSUE TITLE
🙏 Inflated LCP + load time values

### ISSUE THREAD

**Issue by alexmanzo** [DataDog/browser-sdk#2888]
**What are you trying to achieve and what is your issue? Please describe.**
We have a consistent problem with our data where LCP and load time values become inflated in some cases (15-30s or higher). My best hypothesis is that users are loading our page and then switching to a different tab/window that pushes ours into the background. I know this has been addressed before in this issue: https://github.com/DataDog/browser-sdk/issues/1256

These inflated values make it very difficult to alert on averages and properly monitor LCP across the app.

A few notes from when I query for views with these large LCP values:
* we have our replay rate set to 100%, but many of these sessions don't have a replay attached or the replay fails to load. This leads me to believe the session was too short to actually register
* When loading replays and/or looking at the larger session, we see it start at 0s with `Load page`, then there will be a significant gap before we see `User focus on` (>10s)

**Describe the solution you'd like**
We need the LCP and load times logged to Datadog to accurately represent our user experiences. I'm looking for a solution where we can ensure our events aren't sending inaccurate data.

**Describe alternatives you've considered**
We can do a certain amount of filtering in Datadog and cutting off or clamping the highest values, but even setting that at 10s drastically changes the data we have coming int.

**Comment by BenoitZugmeyer** [comment]
Hello @alexmanzo, and thank you for your feedback. Could you reach to support@datadoghq.com so you can share more information with us? In particular, we would be interested in a link to a session where you are observing those inflated values. Thank you!

**Comment by alexmanzo** [comment]
Sure thing!
