### ISSUE TITLE
Custom view measure and viewReady support

### ISSUE THREAD

**Issue by CNManning** [DataDog/browser-sdk#289]
With SPAs it would be quite handy to be able to add custom view measures, at various points of the view lifecycle, that are relative to the view's startOrigin. 

In addition it would be helpful to have a standard provided measure (taking advantage of the above) to add a viewReady measure that applications could call to indicate that the view has reached an application defined 'ready' state. Such a measure could be used regardless of whether the view was created by initial page load, or via History API.

I'd be willing and able to implement such support and open a PR. I wanted to check first that such a feature would be useful and desired, and that the approach is good?

**Comment by hdelaby** [comment]
Hi @CNManning

This feature is indeed something we are planning for the very short term. It will work exactly as you described it. Let's keep this issue opened and we'll let you know once it's available.

**Comment by CNManning** [comment]
Awesome, thanks. It would be good to have this, so that we can introduce RUM in our application in a useful way. Let me know if I can be of any assistance.

**Comment by BenoitZugmeyer** [comment]
This has been implemented in [`v2.4.0`](https://github.com/DataDog/browser-sdk/blob/master/CHANGELOG.md#v240) (`DD_RUM.addTiming`)
