### ISSUE TITLE
Local context not merged with global context?

### ISSUE THREAD

**Issue by ssalka** [DataDog/browser-sdk#291]
Hey DataDog team 👋 

Recently started using `@datadog/browser-logs` to init a client-side logger like so:

```ts
// logger.ts
import { datadogLogs } from '@datadog/browser-logs';

datadogLogs.init({
  clientToken: DATADOG_CLIENT_TOKEN,
  datacenter: 'us',
});

export default datadogLogs.logger;

// app.ts
import logger from './logger';

logger.setContext({ globalField: true });
// ...
logger.info('Something happened', { localField: true });
```

My expectation here is that, in the DataDog UI, I'd see a combined context of `{ globalField: true, localField: true }`, however I see only the local context that is passed at the `logger.info` call site - global context seems to be discarded.

Am I doing something wrong, or is it expected that any local context would _completely_ overwrite the global context (and thus, global context is only used when no local context is provided)?

In my use case I basically want them to be combined with shallow merge - is there a good way to do this without having to write a wrapper that handles this logic myself?

**Comment by bcaudan** [comment]
Hello @ssalka!

With your example, the emitted log is:

```js
{
 ...
 "message": "Something happened",
 "status": "info",
 "globalField": true,
 "localField": true
}
```

Which seems to match your expectation:
> I'd see a combined context of { globalField: true, localField: true }

You can see how we expect the different context to be merged in this [test](https://github.com/DataDog/browser-sdk/blob/master/packages/logs/test/logger.spec.ts#L136).

Do you have a different behavior or does this example not reflect the issue?

**Comment by ssalka** [comment]
Thanks @bcaudan - what you posted is definitely what I expect, however was seeing only local context in our production logs.

Strangely though, I see both local + global when I log from local env. Maybe is something weird with our particular setup. Seems fine to close this for now, I'll do more investigation on my own.

**Comment by bcaudan** [comment]
OK, don't hesitate to drop another issue if you notice a wrong behavior.
