### ISSUE TITLE
Warnings on import: "SDK is loaded more than once. This is unsupported and might have unexpected behavior"

### ISSUE THREAD

**Issue by SargisPlusPlus** [DataDog/browser-sdk#2919]
### Steps to Reproduce

1. Have a Chrome extension that injects content scripts into a webpage.
2. Import `DatadogLogs` in both the webpage and the Chrome extension's content script.
3. Observe that the warning appears in the console.

On [import](https://github.com/DataDog/browser-sdk/blob/main/packages/logs/src/entries/main.ts#L18), the Datadog SDK calls `defineGlobal` on the `window` object and produces the warning: "SDK is loaded more than once. This is unsupported and might have unexpected behavior."

### Environment

- **Datadog SDK version**: ^5.23.3
- **Node version**: v20.8.1
- **Browser**: Chrome

### Additional Context

This issue occurs because my Chrome extension and the webpage share the same `window` object, resulting in two Datadog loggers being defined on the same `window`.

**Comment by BenoitZugmeyer** [comment]
This is expected, only one instance of the Logs SDK should be loaded at a time. Beside using a global variable (which doesn't cause any issue if you don't use it), the Logs SDK is also ding a few things globally:

* a session is store in a cookie. If two SDK instances are configured differently (ex: with a different sample rate), it can lead to unexpected behavior

* global errors and console.logs are collected by the SDK. If two SDK instances are configured to do so, we'd collect data twice.

That being said, this is not the first time we've had that request, and we probably should do something about it. In the meantime, you could ignore the warning.

**Comment by ChillyBots** [comment]
@BenoitZugmeyer I thought I'd add more context here. 

We load `import { datadogRum } from '@datadog/browser-rum';` in 12 util files across our app, however those util files are used _everywhere_ so we can log RUM actions & errors - this means we're essentially importing a `datadogRum` everywhere. 

Aside from manually adding the package to the global scope myself, I'm not sure how it is intended to be used in a JS module-based app without getting these warnings. 

I'd like to request you reopen this and bump it's prio, as we're getting hundreds (maybe thousands) of errors in our test runs & build pipelines which are nearly impossible to ignore.

**Comment by BenoitZugmeyer** [comment]
> I'm not sure how it is intended to be used in a JS module-based app without getting these warnings.

Importing the library multiple times shouldn't be an issue. It should not evaluate the library multiple times, in the same way React isn't re-evaluated every time you `import React from 'react'.

If it is an issue for you, you might have a problem in your bundler setup and somehow the SDK is included multiple times in your JS assets. This is highly ineficient, and I'd suggest adjusting your configuration.

**Comment by vytautas-vitkus-tg** [comment]
Seeing the same issue in our tests as well bumping from 5.8.0 to 5.26.0 version. Fixed tests by mocking the lib:
```
jest.mock('@datadog/browser-rum-slim', () => ({
    init: jest.fn(),
    setUser: jest.fn(),
    clearUser: jest.fn(),
    addAction: jest.fn(),
    addError: jest.fn(),
}));
```

**Comment by ChillyBots** [comment]
@BenoitZugmeyer sorry, I should have clarified, it just meant our test logs went crazy with the same error. There was no functional impact. 

@vytautas-vitkus-tg - I could kiss you!

**Comment by mkaraula** [comment]
> Seeing the same issue in our tests as well bumping from 5.8.0 to 5.26.0 version. Fixed tests by mocking the lib:
> 
> ```
> jest.mock('@datadog/browser-rum-slim', () => ({
>     init: jest.fn(),
>     setUser: jest.fn(),
>     clearUser: jest.fn(),
>     addAction: jest.fn(),
>     addError: jest.fn(),
> }));
> ```

Your solution fails for me because in some tests I spy for example on `addError`. This here worked for me

```
jest.mock("@datadog/browser-rum", () => ({
  ...jest.requireActual("@datadog/browser-rum"),
  init: jest.fn(),
}));
```
