### ISSUE TITLE
History API is wrapped wrong

### ISSUE THREAD

**Issue by kamtschatka** [DataDog/browser-sdk#2943]
**Describe the bug**
The trackHistory function is calling `instrumentMethod(history, 'pushState')`: [Code](https://github.com/DataDog/browser-sdk/blob/6b3cfefd90ecb05a45b840f3447c4882b1811eba/packages/rum-core/src/browser/locationChangeObservable.ts#L36)
`history` does not actually have the `pushState` function, but `History.prototype` does.
This call causes `history` to get a `pushState` function assigned to it, causing the prototype to be ignored, which is causing issues for other vendors, who are also trying to wrap `pushState`.

Original `history`:
![image](https://github.com/user-attachments/assets/6709869e-40ea-4e9a-a0fa-557c9d8cf1ef)

Wrapped `history`:
![image](https://github.com/user-attachments/assets/ac3df8ef-c6f7-42de-99bc-5ed2102ef070)

**To Reproduce**
I am not 100% sure, as I am unfamiliar with DD, but I guess this happens simply by initializing DD?

**Expected behavior**
I believe the correct code would be `instrumentMethod(History.prototype, 'pushState')`. (same for replaceState)

Disclaimer: I work for Dynatrace and found this during a support case. I know we could work around this issue, but I do believe it is better to be fixed at the source. Let me know what you think.

**Comment by amortemousque** [comment]
Hello @kamtschatka,
Good catch! Thanks for reporting it. I'll let you know when it's fixed.

**Comment by amortemousque** [comment]
Hello @kamtschatka, the fix is available in version v5.24.0

**Comment by kamtschatka** [comment]
awesome, thx a lot.
