### ISSUE TITLE
Client side page views seem to no longer be recognized (script tag version)

### ISSUE THREAD

**Issue by corbin-mosher** [DataDog/browser-sdk#2956]
I am not 100% sure this is the correct place to report this issue, however the JS script version of this package (https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum.js) is now only recording one page view per session for Nextjs React SPA client side routed pages.

This started for us at 7:37 PT, the same time the JS file is marked as last updated. It also seems to correlate with the time this package had a new version release.

Did something occur that broke client side history tracking? I see some commits in the release related to history API?

I can submit a support ticket through our DataDog rep if that is preferable.

**Comment by corbin-mosher** [comment]
It turns out that not EVERY session is 1 page view. But instead just a dramatic drop in recordings of page views.

This shows how the `p70` of page views per session takes a big drop down at 7:37 PT Aug 29th.

![Screenshot 2024-08-30 at 11 12 42 AM](https://github.com/user-attachments/assets/02984e3e-90da-4f30-a469-6d6ed99164f4)

Same with the average:

![Screenshot 2024-08-30 at 11 14 31 AM](https://github.com/user-attachments/assets/578ecc6d-a611-403e-a291-b3bb8d6ffa57)

Where as the median holds stable:

![Screenshot 2024-08-30 at 11 15 09 AM](https://github.com/user-attachments/assets/ef6afe35-2097-4de0-8b38-1472745bdd07)

Was this expected with the changes? Was the information just very inaccurate prior to this update for long tail sessions?

**Comment by thomas-lebeau** [comment]
Hi @corbin-mosher, Thanks for reporting this issue. I'm not able to reproduce, would you mind opening a support ticket through your DataDog rep?

**Comment by corbin-mosher** [comment]
Of course. Thanks for the reply!

**Comment by corbin-mosher** [comment]
This was resolved in version 5.26.0.
