### ISSUE TITLE
Reported error traces at Datadog RUM is truncated than original error traces of browser side.

### ISSUE THREAD

**Issue by oy-elrion018** [DataDog/browser-sdk#2976]
**Describe the bug**

Hello. I use the rum to track browser runtime errors.

I found that reported errors at Datadog have a truncated error trace than the original error trace.

I want to track a same error trace with the original error trace. now I can't track application codes of product. I only can track third party library codes. It is not enough for me to use.

I think that the rum SDK might truncate error traces from the browser side, not at Datadog side.

I found `requestErrorResponseLengthLimit` configuation of log SDK(The default value is 32KB. I think that this value is good euough to indicate our error traces). But I don't set this configuration.

The SDK code use this configuration to truncate. (https://github.com/DataDog/browser-sdk/blob/fe822e0a4568b04ae85c7d4c756939fb8c117651/packages/logs/src/domain/networkError/networkErrorCollection.ts#L106)

I found related codes.(`computeStackTrace` method(https://github.com/DataDog/browser-sdk/blob/8f8f83ad4b1789cb1c601f43c0d641ee49fcc235/packages/core/src/tools/stackTrace/computeStackTrace.ts#L31), `truncateResponseText` method(https://github.com/DataDog/browser-sdk/blob/8f8f83ad4b1789cb1c601f43c0d641ee49fcc235/packages/logs/src/domain/networkError/networkErrorCollection.ts#L171))

But these codes have no problems. Are there solutions that I can take? For example : How  

**To Reproduce**

1. Go to the Next.js pages that have errors
2. See browser errors and related error traces (original errors)
3. Go to the Datadog sessions & replays screen and see error traces(espeically, the truncated raw error traces)

**Expected behavior**
I want to track a same error trace with the original error trace.

1. Error traces at Datadog screen(More short).
<img width="949" alt="스크린샷 2024-09-09 오전 10 11 26" src="https://github.com/user-attachments/assets/1fd374f2-aca3-4710-9ae2-bc5f1e04fd7e">
<img width="946" alt="스크린샷 2024-09-09 오전 10 35 11" src="https://github.com/user-attachments/assets/ec8afc55-ce06-42df-84e2-e5e3f7bba47a">
<img width="946" alt="datadog-raw-error-trace" src="https://github.com/user-attachments/assets/c977b17e-a9e3-40a5-931b-f88b8b5f5a47">

2. Original error traces at broswer side (More long). 
<img width="607" alt="스크린샷 2024-09-09 오전 10 13 03" src="https://github.com/user-attachments/assets/5d98ea77-e324-4ace-aa03-1b3bf6cf9b22">
<img width="613" alt="스크린샷 2024-09-09 오전 10 13 10" src="https://github.com/user-attachments/assets/e3085003-018a-430c-927c-0a46e5829421">
<img width="603" alt="스크린샷 2024-09-09 오전 10 13 24" src="https://github.com/user-attachments/assets/9811ffc5-92ef-4e9c-b0ae-fbb61eb1d46f">

3. SDK objects made to send to the Datadog.
<img width="616" alt="error-object-1" src="https://github.com/user-attachments/assets/4d196a38-2408-41b7-a2fc-641134c8056c">
<img width="618" alt="error-object-2" src="https://github.com/user-attachments/assets/4575e312-0576-4f8d-84fc-e6e29e693368">

**Comment by BenoitZugmeyer** [comment]
Hello @oy-elrion018 and thank you for the detailed report.

I believe the issue you are facing is that the browser is showing you "asynchronous" stack traces (see bold `Promise.then` mentions) in the devtools. Unfortunately, there is no way to collect such stack trace. This is a browser limitation: by design, stack traces accessible via JavaScript (collected by our SDK) stop at async points.

However, to have longer stack traces in your app, you could try to increase `Error.stackTraceLimit`. Example, to have up to 20 lines instead of 10 lines, you just need to put the following somewhere in your app:

```js
Error.stackTraceLimit = 20
```

This is not standard and only available on Chromium-based browsers.

**Comment by oy-elrion018** [comment]
Thank you for your answer.

There is a question. In fact, the Given Error trace has more stack frames positioned in application code of product. this stack frames is about sync points. If I increase `stackTraceLimit`, can I track stack frames of application code with sync points?

**Comment by BenoitZugmeyer** [comment]
Increasing the `stackTraceLimit` will increase the stack frames present in the stack trace. But the stack trace will still stop at the first async frame.
