### ISSUE TITLE
🐛 rum requests pending forever

### ISSUE THREAD

**Issue by renanrodrigueszup** [DataDog/browser-sdk#2982]
**Describe the bug**
Not sure if this is a bug or a misconfiguration, but I'm facing the following scenario:
Some of the RUM requests are never ending and stay stuck with status pending as shown in the picture below. 
I believe this causes XHR requests to be put on a browser's request Queue (because of browsers tcp connection limits),  which ends up giving the users a feeling of dealing with an slow performance application.

![image](https://github.com/user-attachments/assets/d52e784d-39a0-41e6-8d1c-c988e27b4eac)

**To Reproduce**

setup the configuration as follows: 
```
 datadogRum.init({
      applicationId,
      clientToken,
      site: '***.com',
      service,
      env,
      trackViewsManually: true,
      sessionSampleRate: 100,
      sessionReplaySampleRate: 10,
      trackUserInteractions: true,
      trackResources: true,
      trackLongTasks: true,
      defaultPrivacyLevel: 'mask-user-input',
    })
 ```

**Expected behavior**
Requests should never stays pending forever. 
A timeout should be defined for these cases.

**Comment by BenoitZugmeyer** [comment]
It is a display bug in the Chrome devtools. The request is actually never started. You can reproduce this by trying to call `fetch` with `keepalive: true` and a body greater than the 64k limit (on any webpage):

```js
fetch('/', { method: 'post', keepalive: true, body: new Uint8Array(70_000) })
```

**Comment by michalma** [comment]
I'm currently facing a similar issue, but it started happening after switching to a proxy. While everything is being collected properly in the Datadog app, these broken fetch requests are worrying me. When I copy any 'failed' Datadog RUM requests and send them without the keepalive flag, they work. Could this be an issue with RUM trying to send requests that are larger than what the Fetch API can handle? Should I worry about that?

**Comment by BenoitZugmeyer** [comment]
No, this is a bug in the Chrome devtools. See https://issues.chromium.org/issues/40872451

**Comment by michalma** [comment]
I understand the Chrome devtools bug, but shouldn't DD RUM limit the payload size to avoid exceeding the Fetch API's limit? In my case, the problem only occurs when using a proxy. However, making the same datadog request from devtools console without the keepalive flag works fine, and a 202 Accepted status is returned, so it's not an issue with the proxy.

**Comment by josephsw** [comment]
Do those requests being stalled/never being sent have any functional impact, or are they being automatically retried with different hashes?

**Comment by BenoitZugmeyer** [comment]
> Do those requests being stalled/never being sent have any functional impact, or are they being automatically retried with different hashes? 

They are retried using a different method (XHR or fetch without keepalive)

> these "stalled" requests are polluting my Datadog logs

Those errors should not be logged in Datadog logs. Would you mind opening a ticket with more context?

> is there a way to configure Datadog to not use keepalive?

No. We use fetch keepalive to make sure the request is not cancelled on page exit. Not doing so would impact reliability.
