### ISSUE TITLE
Documentation on website for setLevel and setHandler

### ISSUE THREAD

**Issue by donovanclarke** [DataDog/browser-sdk#300]
Hi,

just wanted you to be aware that your documentation on the website vs. npm package slightly differs. The documentation according to the npm package is seemingly correct. I just wanted to give a heads up to anyone else that may run into this issue. Also I have shown an example below. Thanks! 

```
on website:
datadogLogs.setLevel(...);
datadogLogs.setHandler(...);

what works:
datadogLogs.logger.setLevel(...);
datadogLogs.logger.setHandler(...);
```

**Comment by bcaudan** [comment]
Hi @donovanclarke!

Thanks for the feedback, we have fixed the public documentation.
