### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by nirvdrum** [DataDog/browser-sdk#301]
Please consider adding a changelog to the project. I think a file in the repo is friendlier than relying on GitHub's Releases functionality, but I'd even settle for that.  Fortunately, the project is small enough where auditing commits is an option. But reviewing commits in general to piece together the changes is a bit tedious because GitHub renders the commits in the opposite direction you'd normally want to read them.

A changelog would be a good way to communicate API changes to your customers and help them evaluate when and why they should upgrade the module in their projects.

**Comment by bcaudan** [comment]
Hello @nirvdrum,

Thanks for the feedback, we should set up a changelog pretty soon.
I'll keep you updated when it will be  available.

**Comment by bcaudan** [comment]
Changelog is now available here: https://github.com/DataDog/browser-sdk/blob/master/CHANGELOG.md

**Comment by nirvdrum** [comment]
Fantastic. Thank you! Do you happen to have a legend for the emoji? I can't make out what several of them are and there's no alt text giving a hint. I tried using Emojipedia to work them out, but one came back as something having to do with alchemy and I can't imagine that's correct. Thanks again.

**Comment by bcaudan** [comment]
Yes, we are mostly following https://gitmoji.carloscuesta.me/ 😄
