### ISSUE TITLE
🐛 npm browser-logs 5.26.0 not compatible  with v5/datadog-logs.js

### ISSUE THREAD

**Issue by thomhurst** [DataDog/browser-sdk#3011]
When trying to use the npm package with the v5 script, I get an error:

> o.contextManager.get is not a function

Looking at the script contents, it indeed is not defined, but `getContext()` is instead.

I noticed the v4 script had `get()` defined, so after downgrading to that the error went away

**Comment by N-Boutaib** [comment]
Hello @thomhurst,

How do you try to access the context ? Which public API are you using.

In v5, we expose two methods to get context (global & internal):
- `getGlobalContext`: [See documentation](https://docs.datadoghq.com/logs/log_collection/javascript/#overwrite-context)
- `getInternalContext`: [See documentation](https://docs.datadoghq.com/logs/log_collection/javascript/#access-internal-context)
