### ISSUE TITLE
Add ability to configure the https statuses for which error should be logged

### ISSUE THREAD

**Issue by jbojcic1** [DataDog/browser-sdk#308]
Currently only responses with statuses 0 or >= 500 are logged. I'd like to log all responses with 404 status too so it would be great if this would be configurable.

**Comment by hdelaby** [comment]
Hi @jbojcic1 

We added your feature request on our roadmap. We first need to define how exactly we want this option to work. We will let you know whenever it's ready.

**Comment by jbojcic1** [comment]
I guess some function that would take request with response as a param and return the boolean flag (log or not to log) would be the most powerful option.

**Comment by matheo** [comment]
any news about this to filter `404` XHR error?

**Comment by PinPinIre** [comment]
I can't tell from reading the documentation but is it expected that the browser log only includes the correct status code if it is >500 and all other status codes are 0? Or are 0 status codes all the aborted requests? 

I am trying to work out whether the huge number of XHR errors I am seeing are valid or are aborted requests like mentioned here https://github.com/DataDog/browser-sdk/issues/362 .

**Comment by BenoitZugmeyer** [comment]
For now, the SDK considers requests ending with a status 0 or >= 500 to be errors.

A request with status code 0 is not necessarily an aborted request, it can be a request that failed because of a connection failure (loss of connectivity...).

**Comment by bryik** [comment]
Mapbox-gl-js frequently aborts requests if a user quickly zooms around a map (tiles rapidly go in and out of view). Within a few minutes of testing I inadvertently generated over 15,000 network errors. 

It would be really nice if there was a way to tell the browser-sdk to ignore these "errors".

**Comment by BenoitZugmeyer** [comment]
Thank you for your feedback, this looks definitly like a SDK issue. We will look into it to improve the situation.

**Comment by wmaca** [comment]
We are facing a similar situation where aborted requests are still being logged. Is this fixed? 

We are using the CDN version, and we are assuming the CND is delivering the latest version. 
Shouldn't it include this fix?

**Comment by wmaca** [comment]
Thanks, @BenoitZugmeyer. In the meantime, we figured out how to use the experimental flag and, so far, for our use case, it seems to be working fine.

During this process, when we saw that `beforeSend` could return a boolean. We thought that by returning `false` it would avoid sending the log. Maybe this is the way you are considering evolving the `beforeSend` option.

Other problem that we currently face is that some errors, even when handled, are logged on console. This ends up creating two erro logs for us. Not sure how to address this one and uncertain this is the right issue to discuss this.

**Comment by BenoitZugmeyer** [comment]
> During this process, when we saw that beforeSend could return a boolean, we thought that by returning false it would avoid sending the log. Maybe this is the way you are considering evolving the beforeSend option.

Yes, that was the idea. The issue for now is that you don't have enough context to know that the Error event corresponds to a request has been aborted. We want to provide more context when invoking the beforeSend callback, so you will be able to check if the error is an `AbortError` or not.

> Other problem that we currently face is that some errors, even when handled, are logged on console. This ends up creating two erro logs for us. Not sure how to address this one and uncertain this is the right issue to discuss this.

If I understand correctly, you are using both `DD_RUM.addError(error)` and `console.error(error)` when handling the error?

**Comment by wmaca** [comment]
Hey @BenoitZugmeyer, any updates on the `beforeSend`? 

The amount of logs with "Fetch Error: User aborted the requested" is crazy.

**Comment by hdelaby** [comment]
Hi @wmaca, regarding the documentation, you can find the definition of `beforeSend` in the [modifying RUM data section](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#enrich-and-control-rum-data), and real-life examples in the [enrich and control RUM data guide](https://docs.datadoghq.com/real_user_monitoring/guide/enrich-and-control-rum-data/?tab=event#discard-a-frontend-error).

Does that fit your requirements?

**Comment by wmaca** [comment]
When I said documentation, I meant the one here on this repo. Thanks for the links.

@hdelaby Will that also work with `DD_LOGS`? And how about `forwardErrorToLogs`?

**Comment by bcaudan** [comment]
Hello, 

IIUC, you want to filter some logs based on their message.
The PR that you mentioned is indeed allowing this behavior.

The usage is described in the [RUM doc](https://docs.datadoghq.com/real_user_monitoring/guide/enrich-and-control-rum-data/?tab=event#discard-a-frontend-error) but not in the [logs one](https://docs.datadoghq.com/logs/log_collection/javascript/#scrub-sensitive-data-from-your-browser-logs), it behaves the same nonetheless.
We will update the logs doc accordingly.

**Comment by bcaudan** [comment]
Current state on this request:
- RUM: since [v3.0.0](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#v300), network errors are no longer automatically reported, see [upgrade to v3 doc](https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#rum-errors), so no more need for configuration.
- Logs: since [v2.5.5](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#v255), you can dismiss unwanted network errors with beforeSend API, see [usage](https://docs.datadoghq.com/real_user_monitoring/guide/enrich-and-control-rum-data/?tab=event#discard-a-frontend-error). We don't plan to introduce a specific configuration option for now.
