### ISSUE TITLE
Is it possible to change the proxy url after initialization?

### ISSUE THREAD

**Issue by hsn-nxt** [DataDog/browser-sdk#3119]
Hello there!

### Is it possible to change proxy URL after RUM initialization?

**Current setup:**
```javascript
init({
    ...,
    proxy: ({ parameters }) => 'https://proxy1.example.com'
});
```

**Use case:** Need to change proxy URL when users switch between instances during their session. 

Is this currently possible? If not, what would be the recommended approach?

**Comment by BenoitZugmeyer** [comment]
You can always return a different value from the `proxy` function:

```js
init({

  proxy: ({ ... }) => {
    if (someCondition) {
      return 'https://a.com'
    }
    return 'https://b.com'
  }
})
```

Or:


```js
let proxyUrl = 'https://a.com'

init({

  proxy: ({ ... }) => proxyUrl
})


// somewhere else:
proxyUrl = 'https://b.com'
```
