### ISSUE TITLE
`forwardConsoleLogs` option not available in the RUM Browser init method

### ISSUE THREAD

**Issue by lmaze** [DataDog/browser-sdk#3120]
At the init of the `datadogRum` exposed by the `@datadog/browser-rum` package, I do not have access to the `forwardConsoleLogs` option.

I have the following TypeScript error: `TS2353: Object literal may only specify known properties, and forwardConsoleLogs does not exist in type RumInitConfiguration.`

Is it normal not to have this option in the RUM? How to filter the errors reported via the console in this case? For example I don't want to log anything in the RUM that comes from `console.error` calls.

- Package used : `@datadog/browser-rum` in version 5.29.1 (latest)
- To reproduce: simply import `datadogRum` from `@datadog/browser-rum` then try to pass the `forwardConsoleLogs` property to its `init` method.

![Image](https://github.com/user-attachments/assets/50601d80-54e3-46df-955a-8c762bb5f149)

=> Expected : Having the same options as the `init` method of the `datadogLogs` object from the `@datadog/browser-logs` package.

**Comment by BenoitZugmeyer** [comment]
> Is it normal not to have this option in the RUM?

Yes, `forwardConsoleLogs` is specific to the Logs SDK

> How to filter the errors reported via the console in this case?

You can use `beforeSend` ([doc](https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm#discard-a-rum-event)). Ex:

```
init({

  beforeSend(event) {
    if (event.type === 'error' && event.error.source === 'console') { return false }
    return true
  }
})
```
