### ISSUE TITLE
When RUM is used alongside xmldom package: Identifier <obfuscated> has already been declared

### ISSUE THREAD

**Issue by WilHall** [DataDog/browser-sdk#3164]
**Describe the bug**

After building a vite project with `@datadog/browser-logs@5.20.0`, `@datadog/browser-rum@5.20.0`, and `@xmldom/xmldom@0.9.5`, loading the transpiled javascript bundle in the browser yields the following fatal error:

```
index-CSY3qgmv.js:1652 Uncaught SyntaxError: Identifier <obfuscated> has already been declared
```

**Minimal reproduction project here**: [WilHall/datadog_rum_vite_issue_repro](https://github.com/WilHall/datadog_rum_vite_issue_repro)

Switching from `@datadog/browser-rum@5.20.0` to the slim version `@datadog/browser-rum-slim@5.20.0` appears to resolve the issue.

**Relevant Packages**

`@datadog/browser-logs: ^5.20.0`
`@datadog/browser-rum: ^5.20.0`
`@xmldom/xmldom: ^0.9.5`

**To Reproduce**

**Minimal reproduction project here**: [WilHall/datadog_rum_vite_issue_repro](https://github.com/WilHall/datadog_rum_vite_issue_repro)

1. Create a new vite project with the **Relevant Dependencies** listed above
2. Run `vite build` (should be successful)
3. Run `vite preview` (should be successful)
4. View the preview URL in your browser and open the console
5. You should see the error `Uncaught SyntaxError: Identifier <obfuscated> has already been declared`
6. *Note:* In my testing, the un-obfuscated identifier appears to be `getTextContent`

**Expected behavior**

I would expect that the installation of `@datadog/browser-rum@5.20.0` would not cause this issue when used alongside `@xmldom/xmldom@0.9.5`, similar to the behavior of `@datadog/browser-rum-slim@5.20.0`.

Since it only happens with `@datadog/browser-rum@5.20.0` I'm assuming this is somehow related to the inclusion of the session replay feature.

**Comment by amortemousque** [comment]
Hello @WilHall,
Thanks for the detailed report! I managed to reproduce the issue. It appears that both `@datadog/browser-rum` and `@xmldom/xmldom` define a function called `getTextContent`. When Rollup bundles the packages, it assigns the same minified symbol to both and executes them in the same scope, leading to a conflict.

To resolve the issue, you can configure Rollup to isolate the packages by forcing the output format to iife. Here’s the configuration:
```ts
export default defineConfig(() => {
  return {
    plugins: [tsconfigPaths(), react()],
    build: {
      sourcemap: true,
      rollupOptions: { output: { format: 'iife' } }, // force rollup to output packages as iife
    },
  };
});
```

**Comment by WilHall** [comment]
@amortemousque Thank you so much! This worked like a charm 🙂
