### ISSUE TITLE
Is there something similar to Logs Pipelines for RUM?

### ISSUE THREAD

**Issue by CallMeHK** [DataDog/browser-sdk#3199]
DataDog logs have [the pipeline feature](https://docs.datadoghq.com/logs/log_configuration/pipelines/?tab=source) that can be used to overwrite service names. My org has used this in the past to support MFE source maps. Does something similar to this feature exist in DataDog RUM? We tried overwriting service names with just the `beforeSend` but it did not work.

**Comment by amortemousque** [comment]
Hello @CallMeHK,

Unfortunately, we currently don't support [the pipeline feature](https://docs.datadoghq.com/logs/log_configuration/pipelines/?tab=source) for RUM.
Using the `beforeSend` API seems like a reasonable approach. Can you tell me more about what's not working? 
We also have dedicated [documentation](https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm#micro-frontend) for MFE support, which might be of interest to you.

**Comment by CallMeHK** [comment]
I will bump to >5.22 and follow the docs. I didnt know there was a section for MFE support, despite having spent a good chunk of time in there. Thanks!
