### ISSUE TITLE
getGlobalObject causes CSP violations on older browsers

### ISSUE THREAD

**Issue by clhuang** [DataDog/browser-sdk#328]
Due to the use of `Function` in https://github.com/DataDog/browser-sdk/blob/master/packages/core/src/utils.ts#L224, the browser agent causes errors when `unsafe-eval` is disallowed by CSP for older browsers without `globalThis` (e.g. Chrome <71, Firefox <65).

Suggest also checking for the existence of `window` (and possibly `self` for webworkers) in addition to `globalThis` to avoid invoking the Function constructor in the vast majority of cases.

**Comment by bcaudan** [comment]
Hi @clhuang,

Thanks for raising that, we will investigate it and keep you updated.

**Comment by bcaudan** [comment]
Hi @clhuang, it should be fixed with `browser-sdk@1.9.3`.
