### ISSUE TITLE
React-Native support?

### ISSUE THREAD

**Issue by maxkomarychev** [DataDog/browser-sdk#370]
Hi, 

I have set up `@datadog/browser-logs` in react-native app according to the [guide](https://docs.datadoghq.com/logs/log_collection/javascript/?tab=npm)

but whenever I am calling log method I see this warning in console:

```
'logs.logger.info' not yet available, please call '.init()' first.
```

how can this library be used for react-native?

**Comment by kokliKo** [comment]
Hi,
Thanks for pinging us.
Yes, our library is not compatible with React Native. Given the differences between JS and React Native we will most likely have to build a new library from scratch.
We plan to work on it at some point but not in the short term unfortunately.

We'll keep you posted when we start working on React Native support.

Thank you!
Nicolas

**Comment by wmcbain** [comment]
@kokliKo For now is the recommended solution sending logs, trace events, etc manually? https://docs.datadoghq.com/getting_started/logs/?tab=ussite

**Comment by maxkomarychev** [comment]
@kokliKo would you mind sharing what special does this sdk do which can't work in RN?
apart from not having very browser specific things like `window` it's pretty much normal js environment

**Comment by wmcbain** [comment]
@maxkomarychev youd have to do a lot of overrides in the package for certain things. Either through polyfills or patch-package.

**Comment by ncreated** [comment]
> would you mind sharing what special does this sdk do which can't work in RN?
apart from not having very browser specific things like window it's pretty much normal js environment

Hey @maxkomarychev. Speaking on mobile specificities  - we actively work on two native SDKs: [dd-sdk-ios](https://github.com/DataDog/dd-sdk-ios) and [dd-sdk-android](https://github.com/DataDog/dd-sdk-android). In order to deliver best quality on mobile, they incorporate many things that are not browser-related, to name a few:
* Runtime impact optimization - by leveraging multithreading and not performing heavy work on some environment constraints (like low battery not plugged into charger).
* Offline mode support - data can be still collected in offline and uploaded later even if the app was terminated or suspended.
* Data transfer optimization - mobile SDKs do not upload data on "expensive" connections (like cellular with "constrained" mode or when using WIFI routed through "expensive" mobile hotspot).
* Mobile-specific metadata - we enrich our mobile data with things like active radio technology (LTE, 3G, ...) or active network interfaces.
* Deep OS integrations - like uploading data from background jobs on Android when user dismisses the app from the foreground.

We want our answer to RN support to include (ideally all) above concepts.

**Comment by andela-dhaniabelega** [comment]
Having the exact same error as @maxkomarychev 
Does this also apply to regular React? My app is built with NextJS.

cc: @kokliKo

**Comment by maamounapprise** [comment]
@ncreated could we then use https://reactnative.dev/docs/native-modules-ios along side native datadog logging?

**Comment by ncreated** [comment]
@maamounapprise For what I see, this should work fine for you 👌. Following ["Exporting Swift" section](https://reactnative.dev/docs/native-modules-ios#exporting-swift) and given that the native [Datadog iOS SDK](https://github.com/DataDog/dd-sdk-ios) already exposes its Logging interface to Objective-C (through [`Logger+objc.swift`](https://github.com/DataDog/dd-sdk-ios/blob/master/Sources/DatadogObjc/Logger%2Bobjc.swift)), you'd have to `@import DatadogObjc` in Objective-C file and define a set of `RCT_EXTERN_` macros.

As mentioned, RN and wide cross-platform support is on our future list, so we don't focus on it right now. But I'd be very happy to see you trying it out in a RN project through Native Modules and coming back with the feedback 🙏.

**Comment by ryosuke-wakaba** [comment]
My solution of sending logs from React Native App is below.

https://docs.datadoghq.com/api/v1/logs/

```
    const url = "https://browser-http-intake.logs.datadoghq.com/v1/input/<client tokens>";
    fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        "ddsource": "native-app",
        "ddtags": "env:develop",
        "message": "test",
        "service": "xxx-native-app"
      })
    })
```

**Comment by jacob-israel-turner** [comment]
Hey guys!  Is Data Dog in React Native support on the team's roadmap?  We recently implemented Data Dog logging on our server and it's been great - we're needing to implement a client-side logging solution soon, and I'd love to be able to use Data Dog.

**Comment by jacob-israel-turner** [comment]
Pinging @kokliKo - I'm now at a point that I need to implement a logging solution for our client.  Is this issue on your roadmap?  If not, I'll be going with a different solution.

**Comment by ncreated** [comment]
Hello @jacob-israel-turner 👋. We're actively working on the RN SDK, which will use both native SDKs under the hood to bringing best for both Android and iOS. This work was already started, but no precise ETA yet.

**Comment by emilioicai** [comment]
Hey @ncreated even though there is no precise ETA yet, can we get a rough estimation on when the RN SDK will be released? I guess we can live with the REST API for the time being but it would be great to replace it with an official lib :)

**Comment by xgouchet** [comment]
Hello @emilioicai , 
We can't talk about our roadmap here, but please contact the support so that we can track that you're interested in having a dedicated React Native library.

**Comment by WASHSWATDAVID** [comment]
+1

**Comment by chanonroy** [comment]
This would be amazing. It would also be great to see a guide on how to get these working with Expo.

**Comment by rdunkle-nj** [comment]
Their `dd-bridge-ios` package is in active development: https://github.com/DataDog/dd-bridge-ios

I'm still learning the lay of the land here, but it seems like that's a chunk of the solution for this React Native effort.

**Comment by ZeroCho** [comment]
Is it okay to use [https://www.npmjs.com/package/dd-sdk-reactnative](https://www.npmjs.com/package/dd-sdk-reactnative) now?

**Comment by priyanshi-gupta** [comment]
Hey @ZeroCho we're internally testing the module and working on documentation - we'll keep this thread posted on the beta release update very soon.

**Comment by priyanshi-gupta** [comment]
We're reaching out to users now to be a part of **private-beta for react native**. If you're interested drop us an email at support@datadoghq.com (you can mention this issue) and we'll reach out to setup a call with you to walk through the setup and answer any questions.

**Comment by justinsoong** [comment]
@priyanshi-gupta we'd be reaching out :)

**Comment by bcaudan** [comment]
https://www.datadoghq.com/blog/react-native-monitoring/ 🎉
