### ISSUE TITLE
Web vitals RUM

### ISSUE THREAD

**Issue by vytautassugintas** [DataDog/browser-sdk#389]
There is this google [web vitals](https://web.dev/vitals/) initiative.

I've been wondering if you guys have plans to include core web vitals (Largest Contentful Paint, First Input Delay, Cumulative Layout Shift) RUM out of the box in DD sometime in the future?

**Comment by bcaudan** [comment]
Hello @vytautassugintas,

We have also seen this initiative, we don't have plans to integrate these specific metrics in the short term but it is definitely something that we keep in mind to provide additional UX metric to our RUM product.

Thanks for pointing that up!

**Comment by vytautassugintas** [comment]
@bcaudan great! 🎉  

Thanks for the answer.

**Comment by hamstu** [comment]
Can we track these ourselves with Datadog's RUM integration?

**Comment by bcaudan** [comment]
Hi @hamstu, 
yes, you could track these yourself and use [custom user actions](https://docs.datadoghq.com/real_user_monitoring/guide/send-custom-user-actions/) to send the data.

**Comment by hamstu** [comment]
@bcaudan Follow up question - if our RUM config has `{ ..., resourceSampleRate: 5, sampleRate: 5 }` will calls to `addUserAction` also be sampled at that same rate? Or will we track actions for all users where that code runs?

**Comment by BenoitZugmeyer** [comment]
Yes, the sampling applies to the whole session, and `sampleRate` impact all events (`resourceSampleRate` impact only resource events).

Just a headsup, Web Vitals will soon be available out-of-the-box in RUM. Stay tuned.

**Comment by hamstu** [comment]
Exciting news @BenoitZugmeyer! Would love to know as soon as that's ready. 🤩

**Comment by charliepark** [comment]
That's great to hear, @BenoitZugmeyer! You don't happen to have an update on when that'll go live, do you?

**Comment by erickhun** [comment]
Would love seeing some update @BenoitZugmeyer thank you ❤️

**Comment by BenoitZugmeyer** [comment]
We are still working on the UI and documentation, but the release is really close. If I'm not mistaken, you should already be able to see the three facets in the RUM Explorer (near the bottom of the left column) and add corresponding columns ([example](https://app.datadoghq.com/rum/explorer?cols=%40view.url_path_group%2C%40view.loading_type%2C%40view.loading_time%2C%40geo.country%2C%40browser.name%2C%40view.cumulative_layout_shift%2C%40view.largest_contentful_paint%2C%40view.first_input_delay&live=4h&query=%40view.loading_type%3Ainitial_load&tab=view)). Keep in mind that we still have small issues, and the UI is not polished yet!

**Comment by erickhun** [comment]
Really appreciate @BenoitZugmeyer ! it's really time for us, appreciate your awesome work here!

**Comment by jacktator** [comment]
This is AWESOME! Can't wait for this!

**Comment by mhuconcern** [comment]
HYPED!!

**Comment by BenoitZugmeyer** [comment]
Core Web Vitals are [finally released](https://www.datadoghq.com/blog/core-web-vitals-monitoring-datadog-rum-synthetics/) 🎉  Let us know if you have any issue on this!
