### ISSUE TITLE
Expose a way to get session id

### ISSUE THREAD

**Issue by nicgirault** [DataDog/browser-sdk#390]
In my app, there is a "debug" page allowing users to send us a report. I would like to be able to display the session id in this report to help the support team accessing the logs corresponding to the session.

Right now I've to do something like this:

```typescript
(datadogLogs.logger as any).session.getId()
```

It would be convenient to be able to do something like:

```typescript
datadogLogs.getSessionId()
```

or

```typescript
datadogLogs.session.getId()
```

meaning that the session would not be anymore a private attribute here: https://github.com/DataDog/browser-sdk/blob/master/packages/logs/src/logger.ts#L132

**Comment by bcaudan** [comment]
Hi @nicgirault,

Thanks for raising that, it is an interesting use case.
Let us think about how we would want to expose it and we will get back to you.

**Comment by ivanzusko** [comment]
Hi there 👋 
Sorry for the disturbance. May I ask is there any progress on exposing a way to get session-id?

**Comment by bcaudan** [comment]
👋 Not at the moment
I think a consistent way to do that would be to expose a `getInternalContext` API like on the RUM side.
Happy to review a PR about it 😉

**Comment by paulclarkin** [comment]
I came here looking for this information, and with the above hints I put `DD_RUM.getInternalContext()` into the Chrome console and one of the returned values is `session_id`. Is this what you're looking for?

**Comment by sethi-ishmeet** [comment]
Is this also available on iOS SDK?
