### ISSUE TITLE
Confusing terminology: Context vs Content, Attributes

### ISSUE THREAD

**Issue by miketheman** [DataDog/browser-sdk#399]
Hello!

I recently [saw and answered this StackOverflow question](https://stackoverflow.com/q/61900949/244037) about adding context to log entries, and noticed that the docs call out Context as the execution environment, however the browser SDK uses Context differently internally, and since that's the user-facing API (add context here...) I completely understand the confusion on what a user might want to do - it took me a while to re-read both the docs and the code to find the mismatch.

I'd recommend creating consistent naming - either clear up the docs/UI, or the internal namespaces in the SDK - either way the confusion can't be good for clients trying to determine if they can add tags or attributes to specific log entries.

**Comment by kokliKo** [comment]
Hey Mike,

Thanks for posting the issue 👍
Yes, we agree that the distinction tags vs attributes and content vs context gets (even more) confusing when we add the notion of "Global context".
We're currently thinking about how to improve this across all of Datadog's products, hopefully it'll become more clear soon.

Closing this issue in the meantime. Thank you again!
