### ISSUE TITLE
.init() is not working

### ISSUE THREAD

**Issue by tristancaron** [DataDog/browser-sdk#411]
Hello,

I use the library with the following code.

```
import { datadogLogs } from '@datadog/browser-logs';

export function init(): void {
  datadogLogs.init({
    clientToken: '<TOKEN>',
    datacenter: 'us',
    forwardErrorsToLogs: true,
    sampleRate: 100,
  });
}

export function info(message: string, context?: {}): void {
  datadogLogs.logger.info(message, context);
}

export function error(message: string, context?: {}): void {
  datadogLogs.logger.error(message, context);
}
```

My very first call is `init()`,  but when I call `info`, I get a warning that `init()` must be call before.

I am also bundling my app with webpack.

Versions tried are: 1.12.1, 1.12.0, 1.11.1

The code is executed from an iframe.
![image](https://user-images.githubusercontent.com/9624669/83447634-c0de7500-a41e-11ea-81c3-948838002250.png)

Is it an issue you are aware of?

**Comment by bcaudan** [comment]
Hi @tristancaron,

It is not an issue that we are aware of.

1. Can you confirm that you have this warning systematically?

1. We can prevent the init in some cases but a `console.error` should be displayed for those cases, can you confirm that nothing prevent `console.error` to be displayed in your setup?

1. Could you try to reproduce your issue in a setup that you could share with us?

**Comment by bcaudan** [comment]
Hi @tristancaron, no news on this front, so I'm closing it.
Feel free to reopen it if you still facing the issue.

**Comment by tristancaron** [comment]
Hello @bcaudan 

I apologize for the delay, we used Google Analytics as an alternative. 

So to answer your questions.

1. Yes I have. Only when running in the iframe.

2. Nothing prevent console.error from being displayed in my setup.

3. Unfortunately, I cannot share code...
