### ISSUE TITLE
Allow masking PII

### ISSUE THREAD

**Issue by bcaudan** [DataDog/browser-sdk#426]
Currently PII can be sent with some of the collected data:

- url
- error message / stack
- user action name

Add a way to mask them for both logs and rum SDK.

**Comment by csancs** [comment]
Just wanted to add a thumbs up, currently the lack of this feature is blocking us from using rum 😞

**Comment by hdelaby** [comment]
This is now live with [v2.1.0 of the Browser SDK](https://github.com/DataDog/browser-sdk/blob/master/CHANGELOG.md#v210). See how to use it in the [documentation](https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm#scrub-sensitive-data-from-your-rum-data).

Thank you for your patience and let us know what you think about it :)

**Comment by OmarJaroudi** [comment]
Any chance we could have a way to mask more data than the pre-determined set of fields specified in the [docs](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm)?

**Comment by OmarJaroudi** [comment]
Any chance we could have a way to mask more data than the pre-determined set of fields specified in the [docs](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm)?

**Comment by MuthulakshmiRK** [comment]
Hey, I came across your issue about masking PII in logs (URL, error messages, etc.).

I’ve been working on a small API that automatically masks emails/phone numbers in logs and JSON payloads before storing.

Curious how you ended up solving this — would love to get your thoughts or share what I built if you're open.
