### ISSUE TITLE
Cookies does not have SameSite attribute

### ISSUE THREAD

**Issue by KarlKl** [DataDog/browser-sdk#430]
Below is an output from my FF 78 with datadog-logs-eu.js active that is complaining about the missing SameSite attribute in the `_dd_s` and `dd_rum_test` cookies.

`Firefox Developer: v78`
`datadog-logs-eu.js SDK-Version: 1.12.4` 

![image](https://user-images.githubusercontent.com/8360477/85420833-0270c480-b574-11ea-8d35-7241d34a3471.png)

**Comment by bcaudan** [comment]
Hi @KarlKl,

Thanks for raising that!

This warning should not be an issue since we are not using these cookies on the backend side. So no worries if they are not forwarded by browsers.
Anyway, we could declare them accordingly to avoid these warnings.

**Comment by bcaudan** [comment]
A fix is available in 1.12.6
