### ISSUE TITLE
Documented init script is no longer valid

### ISSUE THREAD

**Issue by Bolt54** [DataDog/browser-sdk#434]
It appears that the documentation needs to be updated with the latest release.  The sample init script no longer builds using Typescript.  We are updating from 1.5.0 so not sure when this was introduced.

ERROR in app/app.component.ts:42:9 - error TS2322: Type '"us"' is not assignable to type 'Datacenter'.
42         datacenter: 'us',
           ~~~~~~~~~~

  ../node_modules/@datadog/browser-core/cjs/configuration.d.ts:38:5
    38     datacenter?: Datacenter;
           ~~~~~~~~~~
    The expected type comes from property 'datacenter' which is declared here on type 'RumUserConfiguration'

**Comment by bcaudan** [comment]
Hi @Bolt54,

Thanks for raising that, we'll fix the doc quickly!

**Comment by bcaudan** [comment]
In v1.12.7, you can now retrieve Datacenter enum from browser-logs or browser-rum package:

```ts
import { Datacenter, datadogRum } from '@datadog/browser-rum';
```
