### ISSUE TITLE
Allow execution in third party contexts

### ISSUE THREAD

**Issue by nilols** [DataDog/browser-sdk#446]
We want to use RUM in our plugin, the plugin is loaded into an iframe of another company's application, but the recent `samesite` attribute change, which I understand is needed, prevents us from using RUM, due to that the cookie test fails when `samesite=strict`

I found this [page](https://web.dev/samesite-cookie-recipes/#how-to-implement-samesite-today) that talks about the `samesite` attribute and third party contexts. And as a workaround I created my own RUM sdk version, were I instead of `samesite=strict` use `samesite=none; secure` and that works fine, but it would be better if this was supported out of the box.

![image](https://user-images.githubusercontent.com/1027531/87333436-62d49f80-c53d-11ea-80dd-397f354bd79d.png)

**Comment by javelinco** [comment]
I believe these are related. I am getting the following error (in Chrome only) when we use the @datadog/browser-logs npm package:

`A cookie associated with a cross-site resource at https://datadoghq.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032`

**Comment by bcaudan** [comment]
Hi @nilols, 

In order to better understand your issue:

- How does this prevent you to use RUM? Is there a browser error?

- Is your plugin iFrame has a src attribute?

Thanks

**Comment by nilols** [comment]
`How does this prevent you to use RUM? Is there a browser error?`

The `checkCookiesAuthorized` test fails and `Cookies are not authorized, we will not send any data.` is printed in the console log

`Is your plugin iFrame has a src attribute?`

Yes, and with another domain name then the page currently visited

The changes I did to get it to work was this
![image](https://user-images.githubusercontent.com/1027531/91065439-bfdd6e00-e630-11ea-9295-e506101eadaf.png)

**Comment by nilols** [comment]
Maybe this https://blog.chromium.org/2019/10/developers-get-ready-for-new.html explain the issue with `samesite=strict`, for third party context, better then I do

**Comment by bcaudan** [comment]
OK, I did not realize that execution in an iFrame was considered as a third party context.

We could probably allow this behavior through a dedicated configuration parameter, we'll discuss it internally.

**Comment by bcaudan** [comment]
This is available in `1.19.0` with `useCrossSiteSessionCookie: true` init configuration.
Let us know if there is any trouble.

**Comment by gevalter** [comment]
Hey, I have this issue too with the same use case - my company iframes are in other sites and im getting:
"...Cookies are not authorized, we will not send any data." from checkCookiesAuthorized ... my datadog init is:

`
    datadogRum.init({
      applicationId: 'xxxxxxxxxxxx',
      clientToken: 'xxxxxxxxxxxxx',
      site: 'datadoghq.com',
      env: xxxxx,
      service: 'xxx',
      version: '1.0.0',
      useCrossSiteSessionCookie: true,
      trackSessionAcrossSubdomains: true,
      sampleRate: 100,
      trackInteractions: true
    });
`
 tried with version 1.19.0 - 1.21.0 without any success... 
I don't have any control over the original sites containing our iframes..

**Comment by bcaudan** [comment]
Hi @gevalter,

There is indeed still an issu with this but a fix should be released today, cf https://github.com/DataDog/browser-sdk/pull/555

**Comment by BenoitZugmeyer** [comment]
The fix has been release as part of `v1.23.0`.

**Comment by gevalter** [comment]
tried to upgrade to 1.24.0 but still the same coockies warning and no data on the datadog website...

**Comment by BenoitZugmeyer** [comment]
@gevalter:  By using using `useCrossSiteSessionCookie`, you have to use HTTPS websites. Is the top-level website and iframed website in HTTP or HTTPS?

**Comment by gevalter** [comment]
oh you right, changed to https and all works, thanks!

**Comment by faizan-ali** [comment]
Still seeing this issue:
`Cookies are not authorized, we will not send any data`

I have RUM running inside an iframe, seems like this should work as per https://github.com/DataDog/browser-sdk/pull/555
