### ISSUE TITLE
Support for RUM of Ionic / Cordova apps

### ISSUE THREAD

**Issue by jskrepnek** [DataDog/browser-sdk#480]
Hi,

From my tests, it seems like the only piece holding back full browser-rum support of Ionic / Cordova applications is the use of cookies on iOS.  What I am seeing in iOS 13.4 is that cookies cannot be set and/or read by JavaScript, which browser-rum requires to operate.

I cannot find clear information if this is a bug in iOS or if it's intentional.  I have not found a work around either.

Meanwhile, browser-rum worked great on Android.

If you can shed any light on the iOS cookie issue or a work around, that would be great.

In any case, offering an alternative mechanism than cookies for these scenarios would be a welcome feature!

**Comment by hdelaby** [comment]
Hey @jskrepnek 

Thank you for your interest!

As the browser SDK currently focuses on web applications, it will still have major limitations after fixing this iOS cookie issue:
- No crashes detection
- Undefined behavior for offline app browsing
- Inadequate session mechanism

Would that be helpful still? Please note it's on our roadmap to work on supporting these frameworks once we've successfully released iOS RUM.

**Comment by jskrepnek** [comment]
> Hey @jskrepnek
> 
> Thank you for your interest!
> 
> As the browser SDK currently focuses on web applications, it will still have major limitations after fixing this iOS cookie issue:
> 
> * No crashes detection
> * Undefined behavior for offline app browsing
> * Inadequate session mechanism
> 
> Would that be helpful still? Please note it's on our roadmap to work on supporting these frameworks once we've successfully released iOS RUM.

Yes, it would still be fully helpful.

The reality is that a Cordova / Ionic application is *two* types of applications: a web application and a native application.  So I think that any RUM offering is going to end up being a combination of your web and native sdks.

Based on what I'm seeing so far in the Chrome / Android WebView, RUM is fully functional there.  I'm going to be rolling out RUM in our Ionic app by combining the Browser SDK with the Android SDK.  I can see how there will be overlap there in terms of things like session management so I'll look forward to full support for this from DataDog.

**Comment by gabceb** [comment]
Hi all. We are a pretty big Datadog customer and are also in need of using datadog RUM on our Capacitor app and this is currently a big blocker for adoption. As mentioned by @jskrepnek the move from the DD side would probably be to support localstorage instead of cookies.

You could use a package such as https://www.npmjs.com/package/store to help with picking the correct storage based on the browsers which would use localstorage for more modern browsers

**Comment by ith** [comment]
I would like to bump this request as well.

**Comment by wclark-accela** [comment]
We also need this to enable RUM for our iOS customers.

**Comment by rubencallewaert** [comment]
We would also like this feature.

**Comment by azzab80** [comment]
Also would really like this feature for our Ionic app

**Comment by mlynch** [comment]
Ionic/Capacitor founder here 👋🏻 would love to see DataDog invest in making it possible for web developers to use this SDK and the other Mobile performance/user monitoring tools in mobile apps using [Capacitor](https://capacitorjs.com/). Capacitor is similar to Cordova in that it runs web apps natively on multiple platforms, but quite a bit different and improved in other ways.

Let me know if there's anything we can do to help make this happen! Definitely seems like there's demand here and Ionic as a company is increasingly working with enterprise customers that have need for DataDog's solutions.

**Comment by shaun27stars** [comment]
Caching of offline events would definitely be useful for getting the full picture, but the immediate issue - that it cannot track anything from an ios/capacitor build due to using a cookie, is very simple to fix - swap the cookie for sessionstorage. 

The expiry would be different (session store expires when you close the browser / app) and the other cookie-related settings wouldn't do much, but it would successfully send events.

**Comment by bcaudan** [comment]
👋 Support for web based mobile frameworks is still something that we want to offer, our current plan is to build something with our mobile sdk team, allowing us to leverage device capabilities for session tracking and caching of offline events. We hope to make progress on that soon.

The heavy lifting would then be handled by them and support of web based mobile frameworks should then not be correlated with browser-sdk:

- storing session information outside of cookies, it is something that we have [on our radar](https://github.com/DataDog/browser-sdk/labels/use-case%2FSession%20without%20cookie) but it is not our top priority right now.
- caching of offline events, it has not been requested much so far but it is definitely something that we want to address at some point.

**Comment by shaun27stars** [comment]
Thanks for the update. Writing to localstorage instead of a cookie would trivially solve this problem without breaking anything else.
Caching of offline events isn't just for mobile frameworks - the same applies to progressive web apps.

**Comment by shaun27stars** [comment]
If anyone needs a workaround for iOS/cookies in general in the meantime, I've had success with this:

```
var cookieDesc = Object.getOwnPropertyDescriptor(Document.prototype, 'cookie') ||
                 Object.getOwnPropertyDescriptor(HTMLDocument.prototype, 'cookie');
if (cookieDesc && cookieDesc.configurable) {
  Object.defineProperty(document, 'cookie', {
    get: function () {
      let res = [];
      Object.keys(localStorage).forEach(function(key) {
        if (key.startsWith('cookie-')) {
          const item = JSON.parse(localStorage.getItem(key));
          if (item.expiry && new Date(item.expiry) < new Date()) {
            localStorage.removeItem(key);
          } else {
            res.push(key.replace('cookie-','')+'='+item.value);
          }
        }
      });
      return res.join('; ');
    },
    set: function (val) {
      var regex = new RegExp("([^=;]*)\\s*=\\s*([^;]*);(.*expires=([^;]+);)?");
      var matches = regex.exec(val);
      cookieDesc.set.call(document, val);
      localStorage.setItem('cookie-'+matches[1], JSON.stringify({value: matches[2], expiry: matches[4]}));
    }
  });
}
```

I haven't tested every scenario but it lets datadog read/write "cookies" that work in capacitor/ios (and any other library using document.cookie) while still writing to the actual cookie store for e.g. web requests.

**Comment by shishirshetty0710** [comment]
> If anyone needs a workaround for iOS/cookies in general in the meantime, I've had success with this:
> 
> ```
> var cookieDesc = Object.getOwnPropertyDescriptor(Document.prototype, 'cookie') ||
>                  Object.getOwnPropertyDescriptor(HTMLDocument.prototype, 'cookie');
> if (cookieDesc && cookieDesc.configurable) {
>   Object.defineProperty(document, 'cookie', {
>     get: function () {
>       let res = [];
>       Object.keys(localStorage).forEach(function(key) {
>         if (key.startsWith('cookie-')) {
>           const item = JSON.parse(localStorage.getItem(key));
>           if (item.expiry && new Date(item.expiry) < new Date()) {
>             localStorage.removeItem(key);
>           } else {
>             res.push(key.replace('cookie-','')+'='+item.value);
>           }
>         }
>       });
>       return res.join('; ');
>     },
>     set: function (val) {
>       var regex = new RegExp("([^=;]*)\\s*=\\s*([^;]*);(.*expires=([^;]+);)?");
>       var matches = regex.exec(val);
>       cookieDesc.set.call(document, val);
>       localStorage.setItem('cookie-'+matches[1], JSON.stringify({value: matches[2], expiry: matches[4]}));
>     }
>   });
> }
> ```
> 
> I haven't tested every scenario but it lets datadog read/write "cookies" that work in capacitor/ios (and any other library using document.cookie) while still writing to the actual cookie store for e.g. web requests.

Where do I add this code? Before I initialize Datadog?

**Comment by kormie** [comment]
Any updates on this @bcaudan?

**Comment by webuniverseio** [comment]
@bcaudan, 

> We are a pretty big Datadog customer and are also in need of using datadog RUM on our Capacitor app and this is currently a big blocker for adoption
This is true for my team as well

> storing session information outside of cookies
This is the item which most people here are worried about. You could solve this by allowing external storage by providing an API which allows to implement it. This way you will not need to maintain complex solution, while allow people here to move on.

Here (about a week ago from the time I write this commonet) you say that there is no ETA https://github.com/DataDog/browser-sdk/issues/798#issuecomment-1055167030, I think community will benefit from making progress on this and you will be able to close 3 long lasting tickets. Can this be prioritized by your team please? 🙏

**Comment by priyanshi-gupta** [comment]
Hey folks, I'm the PM for RUM at Datadog. Thank you for responses helping us prioritize this request. As we're exploring possible options, would you be interested in a quick 1-1 to help us understand your architecture and how we can best help? 

Please reach out to support@datadoghq.com with link to this issue and I'll set up time on your calendar.

**Comment by richardkshergold** [comment]
@priyanshi-gupta is there any update for this?  We are a DataDpg customer and I'm trying to find out if we can use it for Error Tracking from our Ionic/Angular/Capactitor app?

**Comment by mlynch** [comment]
Anything we can help with @priyanshi-gupta? This is a common request from our enterprise users

**Comment by caseyscarborough** [comment]
I can confirm that [the workaround provided by @shaun27stars](https://github.com/DataDog/browser-sdk/issues/480#issuecomment-859495280) works as a temporary solution. @priyanshi-gupta

**Comment by reslear** [comment]
hi @priyanshi-gupta any news?

**Comment by yacinehmito** [comment]
@priyanshi-gupta FYI Sentry supports Capacitor, so it might be a good source of inspiration: https://docs.sentry.io/platforms/javascript/guides/capacitor/

We were about to migrate from Sentry to Datadog but the lack of direct support for Capacitor will lead us to wait a bit.

**Comment by sectionDayongtek** [comment]
@priyanshi-gupta 
Hi, is there any news? 
We are DataDog paying customer and try to track error with DataDog RUM in our Ionic/Capacitor app.
Thanks.

**Comment by reslear** [comment]
@priyanshi-gupta could you comment on the status ?

**Comment by mentatxx** [comment]
2 years issue seems have no interest at DataDog :(

**Comment by webuniverseio** [comment]
From my experience, as someone outside of DD team and who worked with Cordova/Capacitor for a couple years, Cordova/Capacitor is a dead end for web applications. You can't expect them to work the same as on web due to various limitations. You can take is somewhere but long term this results in accumulation on hacks on web platform (unless you only have mobile application and no website in parallel, then it is more in line with how Cordova/Capacitor was designed). A much better long term solution is a live webview (where you load live website) + js bridges to communicate with native layer - with that you'll not run into many issues. Of course that is more expensive solution and will not work for everyone, which is why products like Cordova/Capacitor exist.

Having said that and focusing on this specific issue, cookie hack mentioned above works just fine for me. I would also look at latest Ionic release which added cookie support (although some say it is buggy).

At this point I would not expect much from DD team as amount of clients who are building on top of Cordova/Capacitor is likely very small 🤷

**Comment by mlynch** [comment]
The idea that Capacitor is a dead end for web apps is simply false. The reason so many people are asking for a DataDog plugin here is because the stack is very popular and growing. Capacitor is doing very well and we hope DataDog pays more attention to this space especially because the large number of enterprise customers using the platform. There is good money for them to be made here!

**Comment by richardkshergold** [comment]
Agree with Max 100% re Capacitor

**Comment by yagobski** [comment]
Guys, please help to find a solution to this problem. Waiting for 2 years and we use Posthog just because you don't provide this feature for ionic capacitor.

**Comment by sir-captainmorgan21** [comment]
For anyone else running into this, this capacitor plugin seems promising and looks to be targeted towards this exact issue. https://capacitorjs.com/docs/apis/cookies Going to try it out and ping back here if its successful

**Comment by ctaepper** [comment]
> For anyone else running into this, this capacitor plugin seems promising and looks to be targeted towards this exact issue. https://capacitorjs.com/docs/apis/cookies Going to try it out and ping back here if its successful

@sir-captainmorgan21 were you successful? I am trying the same thing, but to be honest, I dont know how/what to evaluate to see if its working? I enabled  the capacitor cookie plugin and am running RUM tracking. how can I see if things are working or not?

**Comment by sir-captainmorgan21** [comment]
@ctaepper I dont think it did the trick. An easy way to know if things are working would be to manually go through a session and see if it shows up in data dog. I just test it out, and Im not seeing my sessions :(

**Comment by bryceb-bggoplan** [comment]
> If anyone needs a workaround for iOS/cookies in general in the meantime, I've had success with this:
> 
> ```
> var cookieDesc = Object.getOwnPropertyDescriptor(Document.prototype, 'cookie') ||
>                  Object.getOwnPropertyDescriptor(HTMLDocument.prototype, 'cookie');
> if (cookieDesc && cookieDesc.configurable) {
>   Object.defineProperty(document, 'cookie', {
>     get: function () {
>       let res = [];
>       Object.keys(localStorage).forEach(function(key) {
>         if (key.startsWith('cookie-')) {
>           const item = JSON.parse(localStorage.getItem(key));
>           if (item.expiry && new Date(item.expiry) < new Date()) {
>             localStorage.removeItem(key);
>           } else {
>             res.push(key.replace('cookie-','')+'='+item.value);
>           }
>         }
>       });
>       return res.join('; ');
>     },
>     set: function (val) {
>       var regex = new RegExp("([^=;]*)\\s*=\\s*([^;]*);(.*expires=([^;]+);)?");
>       var matches = regex.exec(val);
>       cookieDesc.set.call(document, val);
>       localStorage.setItem('cookie-'+matches[1], JSON.stringify({value: matches[2], expiry: matches[4]}));
>     }
>   });
> }
> ```
> 
> I haven't tested every scenario but it lets datadog read/write "cookies" that work in capacitor/ios (and any other library using document.cookie) while still writing to the actual cookie store for e.g. web requests.

Hello. I realize this comment is now 2 years old, but  Datadog is now recommending this workaround to customers on Ionic Capacitor as "A workaround that might work."

That being the case, can anyone provide any elaboration on how exactly it is meant to interact with datadog? I'm not sure what to do with it, and an iOS app running it did not return anything to the datadog logs. 

Thank you.

**Comment by cswagerty** [comment]
For those still looking for a solution, we started seeing metrics for iOS once we enabled the [CapacitorCookies plugin](https://capacitorjs.com/docs/apis/cookies) via the `capacitor.config.json` file:
```
"plugins": {
  "CapacitorCookies": {
    "enabled": true
  }
}
```

**Comment by yannickadam** [comment]
Hi all,

The browser SDK can now be initialised in environments where cookies are not supported by setting the initialization parameter `allowFallbackToLocalStorage: true`. (See [documentation here](https://docs.datadoghq.com/real_user_monitoring/browser/#initialization-parameters))

However, the recommended storage to handle sessions is still cookies. The plugin provided by Capacitor to handle cookies seems to be a solid solution to use the SDK without having to enable the fallback parameter.

**Comment by sir-captainmorgan21** [comment]
@cswagerty Ill have to play with this again. I tried this plugin, and had mentioned up above your comment, but I wasn't having any luck at the time.
