### ISSUE TITLE
Config option or custom hooks for additional Facets on RUM Resources

### ISSUE THREAD

**Issue by robolmos** [DataDog/browser-sdk#482]
This probably isn't possible due to RUM only using the Performance API, but I'll throw out there as a future idea: 

I'd like to add additional facets to individual Resource calls to help with analyzing the data.

The main facet I have in mind would be the CDN's cache result being hit or miss, which is an HTTP response header. Being able to include any CDN IDs would be nice.

The CDNs are a caching proxy style (eg, Cloudflare, CloudFront, StackPath, etc.) that use the same origin/domain as the website, so there shouldn't be an issue with accessing the response headers.

Cloudflare and CloudFront have a simple CF-Cache-Status or X-Cache response header and hit/miss value, but other services like StackPath have a more complicated header value, eg, "1541178655.cds005.da2.hc,1541178655.cds113.da2.c" so would need custom parsing.

**Comment by bcaudan** [comment]
Hi @robolmos,

Nice suggestion but to retrieve resource data, we are using:

1. [resource timing API](https://w3c.github.io/resource-timing/), which does not provide access to response headers

1.  js proxy for XHR and fetch requests, which would not be the most relevant resources for CDN cache data

Did you have an approach in mind?

**Comment by BenoitZugmeyer** [comment]
Hello, sorry for the late follow up :)

We released a new API in `v2.13.0` to allow adding [additional data on events](https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm#enrich-and-control-rum-data), based on a "context" used to generate the event. So, you now have access to the `performanceEntry` exposed by the browser for each resource event, and the possibility to use those to extend the `event.context` property to store additional data.

But, like @bcaudan wrote, the browser does not expose the headers of resources, even if they are served on the same origin. I don't think we can do much more for your use case, sorry!
