### ISSUE TITLE
Does this SDK works with browser extension ?

### ISSUE THREAD

**Issue by bt0r** [DataDog/browser-sdk#487]
Hi there 👋🏻 

In advance, thanks for your work 👏🏻 
I'm actually trying to add your sdk inside a browser extension (in a content_script) but i stuck on `'logs.logger.info' not yet available, please call '.init()' first.`

* Is it supposed to work with browser extension ? if yes, is there is something special to do ?

Thanks

**Comment by bcaudan** [comment]
Hi @bt0r,

We are not actively supporting browser extension so some features could not work.
Could you share a repository where we could have a look at your issue?

**Comment by bt0r** [comment]
Hi @bcaudan Thanks for your reply :) 
Sure, you can check this one https://github.com/bt0r/noteflix , i didn't pushed a draft PR with datadog integration because its just a local test but if you need to go deeper, i can do it

**Comment by bcaudan** [comment]
If it does not bother you, it would be great

**Comment by bt0r** [comment]
I pushed a branch with a litle test https://github.com/bt0r/NoteFlix/tree/draft/datadog-logs
To run the extension : 
* `make install`
* `make watch-firefox` or `make watch-chrome` 
* Add the extension in your browser [firefox](https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/installation_temporaire_dans_Firefox) or [chrome](https://developer.chrome.com/extensions/getstarted)
* Open Netflix (needed to trigger the extension)

[Index.js](https://github.com/bt0r/NoteFlix/blob/draft/datadog-logs/src/index.js) is the extension entrypoint, i simply added https://github.com/bt0r/NoteFlix/blob/draft/datadog-logs/src/index.js#L3-L20 to trigger the error (readable in console)

**Comment by bcaudan** [comment]
I've made a few tests, it works fine on chrome but it fails on firefox.

On firefox, I've got a `TypeError: "fetch" is read-only` which let me think that the extension execution context is stricter than the document one.
We use a fetch proxy to collect request errors, so disabling automatic error collection (`forwardErrorsToLogs: false`) should allow you to use the logger.

**Comment by bt0r** [comment]
You're right ! The error seems out now but i cannot see any logs, maybe i'm wrong but should it be somewhere else than in the Log explorer ? (i tried using 15 minutes and live tail to prevent a blacklist policy)

**Comment by bcaudan** [comment]
Unless the same request works from a different context (curl, browser debug console, integration in regular web page), it seems to me that this is a different issue not directly related to this repository.

If this is the case, you should ask [Datadog support](https://www.datadoghq.com/support/) for help with it.

**Comment by bt0r** [comment]
The bug is related to the "datacenter" attribute chosen in the init section https://github.com/bt0r/NoteFlix/blob/draft/datadog-logs/src/index.js#L11, i chose "eu" and now with "us" it's working fine, i close this issue.

Thanks you for you quick answers and help !
