### ISSUE TITLE
Service sent as tag, rather than as an attribute

### ISSUE THREAD

**Issue by xepps** [DataDog/browser-sdk#505]
Hi

We have been using datadog for a while for our backend services, and recently went to introduce it to one of our new front end projects. We noticed that the service was being sent, but as a tag rather than as an attribute, which means it doesn't show as a service in the dashboard.

I had noticed that there was a recent pull request to fix this issue RUMF-620, but that this has been reverted in the latest release v.1.16.0.

Is this being planned for a separate release, or is actually "working as intended". Hopefully the former!

Thanks!

**Comment by xepps** [comment]
I see there is actually an open PR here
https://github.com/DataDog/browser-sdk/pull/501

Feel free to close this issue when you want. :+1:

**Comment by pmc-a** [comment]
@xepps did you manage to find a solution in the interim? I've tried remapping the tag to the attribute, but I'm not entirely sure if that's possible since `service` is a reserved attribute!

Thanks for highlighting this!

**Comment by pmc-a** [comment]
I think I found a way to remap the `service` tag to a custom attribute, took the following steps in case anyone else comes across this in the future:

- Add a new custom 'Standard Attribute' - e.g. `client.application`
- Created a new 'Pipeline' with a filter targeting `source:browser`
- Created a 'Remapper' processor which remaps the tag `service` to the new custom attribute `client.application`

I was then able to filter by this in the standard log explorer. Hopefully this helps anyone who comes up against the same issue!

**Comment by KarlKl** [comment]
I'm using the `datadog-logs.js v1.18.1` and it **still doesn't work**.
It worked in the NPM package `v1.12.10` if it is specified in the global context, I don't know whether it works in newer npm package versions.

**Comment by bcaudan** [comment]
Hello,

There is in progress work to send service as a tag.
In the mean time, for logs, you can configure a [remapper](https://docs.datadoghq.com/logs/processing/processors/?tab=ui#remapper) to set a service tag from the service attribute.

We'll ping here when it will be sent out of the box.

**Comment by xepps** [comment]
Thanks @bcaudan. Looking forward to the update 👍

**Comment by xepps** [comment]
Looks to be resolved in v1.21.0 https://github.com/DataDog/browser-sdk/pull/543

Thanks all.
