### ISSUE TITLE
'getInternalContext' not yet available warning when using logger & rum

### ISSUE THREAD

**Issue by matthewdavidson** [DataDog/browser-sdk#514]
If both `browser-logs` and `browser-rum` are included on the page but only `browser-logs` is initialised, unhandled exception that occur on the page result in shared code in the core module firing the following warning:
```
'getInternalContext' not yet available, please call '.init()' first. 
```

It's desirable to be able to conditionally initialise one module over the other depending on the environment context (in my case, I don't want RUM metrics firing in development, but I do wan't logs going to the console). If it helps the fix, setting `forwardErrorsToLogs` to `false` fixed the issue.

Repro: https://codesandbox.io/s/polished-field-xjyxz?file=/src/index.js
(View the console to see the warning)

<img width="2032" alt="Screenshot 2020-09-03 at 15 12 15" src="https://user-images.githubusercontent.com/1440090/92126373-ffa61180-edf7-11ea-94c6-0f4263ca25a8.png">

SDK Versions:
- `@datadog/browser-logs`: 1.17.0
- `@datadog/browser-rum`: 1.17.0

**Comment by bcaudan** [comment]
Hello @matthewdavidson,

We have updated the way our API works before the SDK is initialized, so this issue should not happen since v1.23.0.
Let us know otherwise.
