### ISSUE TITLE
Check browser protocol used

### ISSUE THREAD

**Issue by christianguevara** [DataDog/browser-sdk#536]
Hey!

I am using the browser-sdk for logs in our hybrid mobile app built with Ionic. Currently, we are using the `file` protocol to handle internal files and some specific features.

I noticed this [check](https://github.com/DataDog/browser-sdk/blob/d1693494e997d723e9e372fc01a4720f472004d4/packages/core/src/init.ts#L79) related to the file protocol and is blocking us from using the library :(

I would like to know if there's any specific reason I'm not aware of to have that check. We can do a fork and remove it, just wanted to double-check if that check is useful.

Thank you for your work :)

**Comment by bcaudan** [comment]
Hi @christianguevara,

Some browser APIs are restricted on `file` protocol, as far as I remember, we have introduced this check when we were requiring to use cookies for browser logs. It is not the case anymore.
If browser logs works correctly on file protocol, we could remove this check.

Don't hesitate to drop a PR for it ;)

**Comment by bcaudan** [comment]
Solved by #709 and available in 2.5.0 version.
