### ISSUE TITLE
SDK override existing installed `onunhandledrejection` handler

### ISSUE THREAD

**Issue by michaelmcchen** [DataDog/browser-sdk#541]
Hi, 

I have a project where I've installed both Datadog RUM and Sentry (https://sentry.io) and when Sentry is initialized _before_ RUM, RUM will override the `onunhandledrejection` handler (see the [code](https://github.com/DataDog/browser-sdk/blob/8f86472688dbb3cf117ad422c11cd5ba7fa5aab8/packages/core/src/tracekit.ts#L312-L331)) 

The fix for this project was to initialize Datadog before Sentry, so Sentry calls both its handler & the previously installed handler (RUM). I'm wondering if the RUM team will be receptive of a PR changing the installation behavior to respect previously installed handlers. Thanks!

**Comment by bcaudan** [comment]
Hi @michaelmcchen,

Thanks for raising that, it is indeed an issue on our side.
We'd be happy to review a PR for it.
