### ISSUE TITLE
@datadog/browser-rum Masking URL

### ISSUE THREAD

**Issue by obartra** [DataDog/browser-sdk#552]
I haven't been able to find in the docs a way to hide or mask the URL.

For my use case, part of the URL may contain sensitive information (ok to share internally but not externally) I was wondering if there's a way to mask part of the URL or omit it entirely from reporting when using the `@datadog/browser-rum` package.

**Comment by bcaudan** [comment]
Hi @obartra,

There is no way to do that for now but we are planning to work on it soon.
You can follow #426 for updates on this topic.
