### ISSUE TITLE
Support for path groups in subdirectories

### ISSUE THREAD

**Issue by walkafwalka** [DataDog/browser-sdk#556]
We currently have a hybrid frontend as we are deprecating the legacy frontend. The legacy frontend uses the root directory so different products are accessed at /productA/, /productB/, etc. However, our new frontend is accessed at /spa/productA/, /spa/ProductB/, etc. so Datadog RUM always reports the path group at /spa/.

Is it possible to specify an expected subdirectory or specify a depth level in the RUM configuration?

**Comment by hdelaby** [comment]
Hi @walkafwalka 

I was able to access your account and check that some pages use hash navigation. If you look into the attributes of your RUM View events, you will find the `view.url_details.hash` attribute which extracts everything after the `#` in the URL of the current page. Is it what you are looking for?

For instance, with `mydomain.com/spa/#/foobar`, hash would be `/foobar`

<img width="467" alt="Image 2020-10-12 at 10 52 13 AM" src="https://user-images.githubusercontent.com/21019740/95726470-44378f00-0c79-11eb-8578-0e517500cf12.png">


We'll definitely make that clearer in the documentation 👍

**Comment by walkafwalka** [comment]
Hey @hdelaby, thanks for the workaround.

That solution works for using Explorer/Analytics and custom dashboards, but not for the default dashboards and error tracking.

**Comment by walkafwalka** [comment]
Also, the hash contains the query parameters. We are looking for something like `path`, but for hashes, like a `hash_path`.

**Comment by hdelaby** [comment]
It's not planned for the short term, but it is definitely something we will improve. I will let you know whenever we make progress on this. Thank you!

**Comment by bcaudan** [comment]
Hello!

Since browser-sdk@2.17.0, you can now track views manually and define your own view names.
More info on the [documentation](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#override-default-rum-view-names).
