### ISSUE TITLE
Feature request: print log context to console when the handler is "console"

### ISSUE THREAD

**Issue by dantheman39** [DataDog/browser-sdk#589]
Hello! When developing locally I set the log handler to "console", to not spam the live site.

```typescript
datadogLogs.logger.setHandler(
  process.env.DD_ENABLED === "true"
    ? HandlerType.http
    : HandlerType.console
);
```

The downside to this is that I can't see the context values of the log, which makes this much less useful. This call to the logger:

```typescript
datadogLogs.logger.info("Switching viewed account", {
  from: oldAccount,
  to: newAccount,
});
```

Results in this log to the console:

<img width="253" alt="Screen Shot 2020-10-23 at 11 20 47 AM" src="https://user-images.githubusercontent.com/10103957/97022396-0f052980-1522-11eb-88f0-621f1ae09ab2.png">

I can't see the "from" and "to" values I'm sending along, which makes these logs much less useful for debugging (if the handler were "http", I could see these values in the network tab). I end up having to go into the code and setting a `console.log` if I want to debug things, whereas I would hope that datadog's logger would make that unnecessary.

Either way I hope you all are well, thank you!

**Comment by bcaudan** [comment]
This is available in browser-sdk@1.25.4
