### ISSUE TITLE
_dd_s without HttpOnly attribute

### ISSUE THREAD

**Issue by randomhash** [DataDog/browser-sdk#590]
Hello, is it possible to set HttpOnly attribute for the _dd_s cookie?

_Automated output:_ Secure flag must be set for Session Cookies for Application served over SSL. For all Session cookies, HTTPOnly flag would limit session access in cases of Cross-Site Scripting issues. Proper Caching headers should be set for responses carrying the cookie.

**Comment by bcaudan** [comment]
Hello @randomhash,

It is not possible:

- `HttpOnly` attribute is for cookies sent by a server ([MDN http cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Restrict_access_to_cookies)).

- `_dd_s` cookie is created and used only in javascript (to maintain the session state during the navigation).

**Comment by randomhash** [comment]
As I thought, thank you for the answer
