### ISSUE TITLE
Don't initialize mutation observer if `trackInteractions == false`

### ISSUE THREAD

**Issue by eligrey** [DataDog/browser-sdk#601]
From the look of the following source snippets, it appears that the mutation observer is always registered and its events are simply ignored when `trackInteractions` is `false`.

This mutation observer still has significant overhead, so it would be much more efficient to only register the mutation observer when `trackInteractions` is `true`.

- https://github.com/DataDog/browser-sdk/blob/e39eb3b18b98512e27cb9264c4f2cd1c9e1c9582/packages/rum/src/boot/rum.ts#L49
- https://github.com/DataDog/browser-sdk/blob/701a0f81b303fad50d9f16e724af8143ab0fffe7/packages/rum/src/browser/domMutationCollection.ts#L40-L65
- https://github.com/DataDog/browser-sdk/blob/595a2382b6b820d3c81f455a82bc4c27efef22d4/packages/rum/src/domain/trackPageActivities.ts#L59-L65

**Comment by BenoitZugmeyer** [comment]
Hi Eli, thank you for your suggestion.

`trackPageActivities` is used when collecting user interactions when `trackInteractions` is `true`, but also to compute views `loadingTime`. We'll discuss about it internally to see if we can improve the situation.

**Comment by bcaudan** [comment]
fixed by #858
