### ISSUE TITLE
Type ContextValue does not have object on its type

### ISSUE THREAD

**Issue by code-mattclaffey** [DataDog/browser-sdk#603]
When we upgraded to the latest version we got an error with our current log setup:

```
const loggerExample = datadogLogs.getLogger('loggerExample')

// item = {some stuff in an object}
loggerExample.error('Logger | Returned null image reference', { item })
```

In context.d.ts we have the ContextValue set as:

```
export declare type ContextValue = string | number | boolean | Context | ContextArray | undefined | null;
```

When I add object in the ContextValue the ts errors went away. Just wondering if this is a bug or is that by design of the new version?

**Comment by bcaudan** [comment]
Hello @code-mattclaffey,

Thanks for raising this.
To be sure to understand the issue, could you provide these details:

- what was your version before the update?
- what is the error returned by the compiler?

Could you also provide a simple example that trigger this issue?

Thanks!

**Comment by code-mattclaffey** [comment]
Hi @bcaudan  I realised the issue was on our side not matching up the types correctly. The issue we had was:

```
AxiosResponse<SomeType> was not compatible with type ContextValue
```

We upgraded ... there was no error prior to this so I assume ContextValue did not exist in that version?

"@datadog/browser-logs": "1.11.4",	    "@datadog/browser-logs": "^1.25.1",
   "@datadog/browser-rum": "^1.12.7",	    "@datadog/browser-rum": "^1.25.1",

**Comment by bcaudan** [comment]
In 1.11.4, logger method signatures were [the same](https://github.com/DataDog/browser-sdk/blob/df2a96f53ff2aeca08861037ce44604652afa667/packages/logs/src/logs.entry.ts#L29) and [ContextValue](https://github.com/DataDog/browser-sdk/blob/df2a96f53ff2aeca08861037ce44604652afa667/packages/core/src/utils.ts#L106) already existed.

If you want to go to the bottom of this, you could try to reproduce the issue with a simpler setup.
