### ISSUE TITLE
Request buffer system is incompatible with requests that are larger than available memory

### ISSUE THREAD

**Issue by eligrey** [DataDog/browser-sdk#606]
I haven't tested to confirm this, but it appears that you buffer all `fetch` and `XMLHttpRequest` requests. This will likely cause memory issues for sites that use streaming requests for resources that are larger than available memory.

I suggest that you switch to a streaming chunked solution. You should refactor all of your `FetchCompleteContext` (and `XhrCompleteContext `?) code to either have a maximum bufferable size (at which point, the Datadog SDK should stop processing & revoke the buffer) or use `ReadableStream` & `TransformStream` with polyfills as needed.

- https://github.com/DataDog/browser-sdk/blob/master/packages/core/src/browser/fetchProxy.ts#L96

**Comment by BenoitZugmeyer** [comment]
Better late than never, this issue has been fixed :) Thank you for your feedback! Let us know if you still see anything weird.
