### ISSUE TITLE
Handle logs via console AND http simultaneously

### ISSUE THREAD

**Issue by trestletech** [DataDog/browser-sdk#622]
I'd like to have log entries routed both to the console AND submitted via HTTP.

https://docs.datadoghq.com/logs/log_collection/javascript/#change-the-destination documents how to handle the logs either via HTTP, console, or silent. But it doesn't appear that there's a way to have logs both printed to the console and reported to DataDog.

I have two  use cases where I'd like this:

1. In a staging environment, it'd be nice to allow our QA folks to be able to pull up the JS Console and take screenshots that show any logs that we emitted alongside whatever they're seeing in the browser.
2. We have a "debug mode" that we can enable in production. With our previous logger, when you switched in to debug mode the logs would be emitted to the console so that you could inspect them. I'd like to be able to do that while still having the logs forwarded to DataDog.

**Comment by yaplusplus** [comment]
I have the exact same case

**Comment by brunor97** [comment]
It's hard to believe that this is not already implemented. It seems like such a basic feature to have...

**Comment by bcaudan** [comment]
👋 Sorry that we don't make progress on some of the requested improvements, unfortunately this feature is not on our top priorities for now 😕 
Don't hesitate to drop a PR if you have a chance, we'd be happy to review it and add it to our feature set.

**Comment by brunor97** [comment]
Thanks for the answer! Sorry if that sounded a bit harsh, I understand that priorities have to be managed. If I have the time I might look into it :)

**Comment by amortemousque** [comment]
This has been released in version 2.9.0.
You can now set a table of handler like so `datadogLogs.logger.setHandler(['http', 'console'])`
