### ISSUE TITLE
Custom view load tracking

### ISSUE THREAD

**Issue by pcreux** [DataDog/browser-sdk#623]
Hello,

We're trying out RUM on an application using Turbolinks.

Since Turbolinks changes the route (`window.location`) once the HTTP request completed and RUM tracks page views when the route changes, `route_change` views don't contain the HTTP request initiated by Turbolinks.

<img width="1307" alt="Screen_Shot_2020-11-18_at_12_30_10_PM" src="https://user-images.githubusercontent.com/45299/99595646-f0237700-29a9-11eb-8fb0-2343fe1704fa.png">

Is there a way to trigger a page view on `DD_RUM` when the `turbolinks:visit` [event](https://github.com/turbolinks/turbolinks#full-list-of-events) fires?

**Comment by bcaudan** [comment]
Hello @pcreux,

For now, new view creation is tied to url route change.
We plan to support this kind of use cases at some point.

We will ping here when we will have something ready.

**Comment by pcreux** [comment]
Merci Bastien ! 💚

**Comment by bcaudan** [comment]
Hello!

Since browser-sdk@2.17.0, you can now track views manually.
More info on the [documentation](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#override-default-rum-view-names).
