### ISSUE TITLE
cookie_test in v1.26.1

### ISSUE THREAD

**Issue by fredbi** [DataDog/browser-sdk#636]
Hello

I have installed rum on our typescript react app (not logs).
I noticed there is a `dd_cookie_test` created with content `test`.
I am running sessions again and again from the same browser tab, new such cookies will be created.

I assume this is a left over from debug code and this cookie is not actually meaningful

**Comment by bcaudan** [comment]
Hi @fredbi,

We are using it to test if [cookies are authorized ](https://github.com/DataDog/browser-sdk/blob/f8c339b28dcaf150dd588d906831072ff18b5990/packages/core/src/browser/cookie.ts#L60), the lifetime should only be one second though.

Do you end up with multiple `dd_cookie_test_xxx` cookies while navigating?
Can you reproduce this behavior on different browsers or only on a specific one?

**Comment by bcaudan** [comment]
Feel free to reopen if needed

**Comment by Gadotti** [comment]
I'm facing this problem... 
I'm getting a huge list of this cookies but only using the FireFox Developer Edition... 
I tried on Chrome and seems OK.
![abb4c247-5703-4939-8940-0b8a34c0521d](https://user-images.githubusercontent.com/23037445/108519886-d8a9a200-72a8-11eb-9b0b-1608efee81e7.png)
