### ISSUE TITLE
Support for Capacitor App stack traces

### ISSUE THREAD

**Issue by stripathix** [DataDog/browser-sdk#645]
I am moving from sentry to datadog for error logging. I have an Ionic + Capacitor application. So this application runs as a Hybrid Application. Same source code is used for both Web Application, iOS, and Android. 

The problem that I am getting when running as an iOS app is that stacktrace does not contain the proper file name and line number where the error occurred. 

JS code that is throwing the error is:
```
// newTestVariableis not declared ever.
var a = newTestVariable;
```

Log created is:
<img width="643" alt="Screenshot 2020-12-13 at 8 34 47 PM" src="https://user-images.githubusercontent.com/8480351/102015609-a8162b00-3d82-11eb-891d-7bbc21ca5922.png">

A similar issue was earlier in Sentry also which was reported here https://github.com/getsentry/sentry-javascript/issues/1863 and they resolved it by modifying their gecko here https://github.com/mrlowe/sentry-javascript/commit/3a09f918e0cbadfdbc1c11d6d779d4718d597fb0.  So it might be helpful to understand what I mean.

Maybe something similar needs to be done by datadog also.

**Comment by bcaudan** [comment]
Hello @stripathix,

Thanks for all the context, it should indeed be something similar.
We'll look into it and get back to you.

**Comment by bcaudan** [comment]
👋 @stripathix, we've added the support with 2.3.0 version, let us know how it goes.
