### ISSUE TITLE
Circular dependencies warning when bundling the @datadog/browser-logs

### ISSUE THREAD

**Issue by coolgod** [DataDog/browser-sdk#701]
I was using rollup to bundle my package that consumes `@datadog/browser-logs` and get following error.
```
node_modules/@datadog/browser-core/esm/tools/utils.js -> node_modules/@datadog/browser-core/esm/domain/internalMonitoring.js -> node_modules/@datadog/browser-core/esm/tools/error.js -> node_modules/@datadog/browser-core/esm/tools/utils.js
```

**Comment by BenoitZugmeyer** [comment]
Thank you for your report. I did investigate the issue a bit, and while we definitly have circular dependencies in our source code, `rollup` prints a warning but the build still succeeds. We will see what we can do to improve the situation, but in the meantime, could you confirm that it doesn't block you from building your project?

**Comment by coolgod** [comment]
Thanks for looking into this. Yeah, it doesn't block me for producing the build. 

I just noticed this when I was investigating some issues we run into, but it turn out it has nothing to do with this circular dependencies warning. It would just be nice if we can get rid of this bu to just clarify again it does not block me.

**Comment by petermize2077** [comment]
Are there any updates or solution to prevent this warning? I'm seeing this as of today

`(!) Circular dependencies
node_modules/@datadog/browser-core/esm/domain/internalMonitoring.js -> node_modules/@datadog/browser-core/esm/tools/error.js -> node_modules/@datadog/browser-core/esm/domain/internalMonitoring.js
node_modules/@datadog/browser-core/esm/domain/internalMonitoring.js -> node_modules/@datadog/browser-core/esm/tools/error.js -> node_modules/@datadog/browser-core/esm/domain/tracekit/index.js -> node_modules/@datadog/browser-core/esm/domain/tracekit/computeStackTrace.js -> node_modules/@datadog/browser-core/esm/domain/tracekit/report.js -> node_modules/@datadog/browser-core/esm/domain/internalMonitoring.js
node_modules/@datadog/browser-core/esm/domain/tracekit/computeStackTrace.js -> node_modules/@datadog/browser-core/esm/domain/tracekit/report.js -> node_modules/@datadog/browser-core/esm/domain/tracekit/computeStackTrace.js
...and 6 more`

**Comment by mininao** [comment]
Hi @BenoitZugmeyer 👋 

We have the same issue as @coolgod at @alan-eu, except with react-native's Metro bundler.
Unfortunately it makes for a bit of an annoying developer experience as it opens 7 warnings everytime the app is reloaded in development mode :
|Closed warning|Open warning|
|-|-|
|![image](https://user-images.githubusercontent.com/5511564/155010125-25b3eac3-6c32-4834-9471-86f00e99e193.png)|![image](https://user-images.githubusercontent.com/5511564/155010304-b33071b6-6765-41dd-a907-2b7f80a1b2d1.png)|

Are you considering removing the circular dependencies, or do you have workarounds in mind 🙂?

**Comment by BenoitZugmeyer** [comment]
Thanks for your feedback. We will experiment with shiping bundled NPM packages, so it should resolve the issue of circular dependencies. We'll keep you up to date on this topic!

**Comment by mininao** [comment]
Thanks a lot Benoît!

**Comment by yedidyas** [comment]
I have the same warning, waiting for an update. thanks

**Comment by BenoitZugmeyer** [comment]
👋  Following the last release v4.11.3, the Browser SDK is circular-dependency free 🎉 
Let us know if you still have an issue.
