### ISSUE TITLE
how to decode the trace id on _datadog_xhr

### ISSUE THREAD

**Issue by ilovett** [DataDog/browser-sdk#729]
I am not sure how to decode the traceId buffer on the `res.request._datadog_xhr.trace.buffer` -- can anyone enlighten me?

**Comment by bcaudan** [comment]
Hi @ilovett,

`_datadog_xhr` is an internal context to save data across xhr lifecycle but you should not require to interact with it.
What are you trying to achieve?

**Comment by ilovett** [comment]
@bcaudan I'd like to surface the trace id to the UI so debuggers/testers can pass me the id of a failing request

**Comment by aethr** [comment]
We also find this useful to be able to correlate log lines, for example when a back-end request fails:
```js
        const traceId = response.request?._datadog_xhr?.traceId?.toDecimalString();
        logger.error('service request failure', {
          http: {
            url: `${this._apiClient.defaults.baseURL}${urlPath}`,
            method,
            referrer: window.location.href,
          },
          error: { kind },
          ...(traceId && { dd: { trace_id: traceId } }),
        });
```
If there was a better ay for us to get the traceId or correlate log lines I'd be interested!

**Comment by bcaudan** [comment]
Your two use cases are interesting.

I would not recommend to go with @aethr approach since `_datadog_xhr` is an internal API.

I think that for both of your use cases, something could be done with [beforeSend API](https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm#scrub-sensitive-data-from-your-rum-data):

```ts
datadogRum.init({
  ...,
  beforeSend: (event) => {
    if (event.type === "resource" && event._dd.trace_id) {
      // handle trace id
    }
  }
})  
```

This way you don't have to decode the trace id yourself and it would also work with fetch request.

**Comment by aethr** [comment]
Thanks @bcaudan I'll give your solution a try.

**Comment by ilovett** [comment]
Thanks @aethr  -- `res.request._datadog_xhr.traceId.toDecimalString()` is what I was looking for

@bcaudan Unfortunately I'm not sure how to use that unless I add a header or something to the XHR config which I'd rather not do

**Comment by aethr** [comment]
Hi @bcaudan I took a look at your suggestion but unfortunately I can't see any way to do what we need from the `beforeSend` hook.

Basically, we use an `APIClient` wrapper in our project that all back-end requests go through, the code is roughly like:
```
let request;
try {
  request = client.post(params); // some axios client here
} catch (error) {
  logger.error('service request failed', {
    // some request params
    trace_id: <TRACE ID HERE>,
  });
} finally {
  logger.info('service request', {
    // some request params
    trace_id: <TRACE ID HERE>,
  });
} 
```

This gives us log lines from the front-end app where we can see the context leading up to the error, and we can correlate the log line with back-end logs using the trace.

Unfortunately there isn't enough context during the `beforeSend` hook for me to correlate the trace id to the request as it's happening. Perhaps if `beforeSend` included a reference to the actual XHR I could make it work by reading / attaching a header, but for now I can't see any way to get the data I need. Do you have any other ideas? Otherwise I think we're forced to use your internal API until I can find a suitable alternative.

**Comment by bcaudan** [comment]
Hi @aethr, I get your point.

We are starting a reflexion to have other hooks API with more context related to the event.  
Having an API where you can access the actual XHR to dismiss a request, add extra infos to the event or execute some custom code is definitely a use case that we have in mind. 

I'll get back to you when we will have more progress on this front.

**Comment by philippeLepage** [comment]
> Hi @bcaudan I took a look at your suggestion but unfortunately I can't see any way to do what we need from the `beforeSend` hook.
> 
> Basically, we use an `APIClient` wrapper in our project that all back-end requests go through, the code is roughly like:
> 
> ```js
> let request;
> try {
>   request = client.post(params); // some axios client here
> } catch (error) {
>   logger.error('service request failed', {
>     // some request params
>     trace_id: <TRACE ID HERE>,
>   });
> } finally {
>   logger.info('service request', {
>     // some request params
>     trace_id: <TRACE ID HERE>,
>   });
> } 
> ```
> 
> This gives us log lines from the front-end app where we can see the context leading up to the error, and we can correlate the log line with back-end logs using the trace.
> 
> Unfortunately there isn't enough context during the `beforeSend` hook for me to correlate the trace id to the request as it's happening. Perhaps if `beforeSend` included a reference to the actual XHR I could make it work by reading / attaching a header, but for now I can't see any way to get the data I need. Do you have any other ideas? Otherwise I think we're forced to use your internal API until I can find a suitable alternative.

Hello!

This is also something I am trying to do.  Correlate logs with traces.  Unfortunately we are not using Datadog Logs so we need to stitch both logs and traces together.  I've been trying to clone the x-datadog-trace-id value into another header that is known in the other system.

I saw that in beforeSend we have access to more than just an event.  In fact it's more like (requestInput , requestInit) where requestInput is the event (containing the _dd.trace_id).  If you look into both of these parameters, you can add "headers" in theory.  

But fiddling with both of them gave no result.  It seems that the XHR tracer will ignore any header added into them. 

Did I read this correctly?
And is there any other way to achieve what I am trying to do?

**Comment by bcaudan** [comment]
Hi @philippeLepage,

I am not sure to well understand what you are trying to achieve.
This ticket is more about retrieving the trace id from a traced request which can be done with RUM by:
- intercepting resource event with beforeSend, cf https://github.com/DataDog/browser-sdk/issues/729#issuecomment-781180096
- (not recommended) accessing `xhr._datadog_xhr.traceId`, cf  https://github.com/DataDog/browser-sdk/issues/729#issuecomment-780302094

If that does not help you, would you mind open a dedicated issue for what you are trying to do?

**Comment by philippeLepage** [comment]
@bcaudan 
Yes, sorry I was not clear.

What I am trying to do is to duplicate the traceId in another header before sending my request.

1. creating a request with axios
2. go through my beforeSend call back from datadog rum sdk
3. retrieve event._dd.trace_id 
4. add trace_id as a new header to the request 

The step 4 I cannot see how to do it.  I've tried adding it in headers in the event of the beforeSend callback but it seems to be ignored later on by the sdk.  While browsing through your code, I've seen that the beforeSend receives a requestInput (this is the event) and requestInit.  

`function beforeSend(input: RequestInfo, init?: RequestInit) {
  const method = (init && init.method) || (typeof input === 'object' && input.method) || 'GET'
  const url = normalizeUrl((typeof input === 'object' && input.url) || (input as string))
  const startClocks = clocksNow()

  const context: FetchStartContext = {
    init,
    input,
    method,
    startClocks,
    url,
  }

  beforeSendCallbacks.forEach((callback) => callback(context))

  return context
}`

Seeing that, I figured out that I should be able to add my new header to either one of them and it would be added to my request by datadog rum sdk.  But anything I put there gets ignored and only the "x-datadog-xyz" headers get added.

**Comment by bcaudan** [comment]
@philippeLepage in order to not spam other participants, I've moved this discussion to https://github.com/DataDog/browser-sdk/issues/894

**Comment by bcaudan** [comment]
Hi @aethr,

Since browser-sdk@2.13.0, you can have access to more context inside beforeSend, notably a reference to the xhr for resource event.
Check the [documentation](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#enrich-and-control-rum-data) for more information.

**Comment by aethr** [comment]
Thanks for the heads up @bcaudan , I'll create an issue in our project to replace the `_datadog_xhr` usage with something in `beforeSend`. I'll try to report back here if it works!

**Comment by luisabtrace** [comment]
Hi, did you ever figure out how to do this? `_datadog_xhr` doesn't seem to exist anymore and I wasn't able to figure out how to do this in `beforeSend`.

**Comment by aethr** [comment]
@luisabtrace sadly it's no longer possible and we're just having to live without trace/log correlation at this point.

The `beforeSend` API isn't suitable for us because it happens before an event is sent **to Datadog** which is too late for us to be useful because all our error handling and monitoring code has already run.

**Comment by dtothefp** [comment]
also very interested in this use case, specifically for sending trace id info to Sentry if a request has failed / receives a bad response. @aethr did you every figure anything out?

**Comment by aethr** [comment]
@dtothefp it seems like the most straightforward way to get this information is to do something quite similar to what DataDog themselves do in https://github.com/DataDog/browser-sdk/blob/d4c60b83bf09e890966383cca1b6c01336d9bb56/packages/core/src/browser/xhrObservable.ts#L41-L64

Wrap the `XMLHttpRequest.prototype.send` method so you can observe what values DataDog is setting in the headers, and then save this somewhere (maybe on the xhr object itself) where you can retrieve it later for your Sentry events.

We haven't gone down this road as we have other priorities in our project, but it should be possible.

For context, here is the RUM code that generates and attaches the trace id to xhrs: https://github.com/DataDog/browser-sdk/blob/d659e2c4a74987d9e4816381bd85ce440adc408a/packages/rum-core/src/domain/requestCollection.ts#L73-L75
