### ISSUE TITLE
Disable `Error Management`

### ISSUE THREAD

**Issue by alesso-x** [DataDog/browser-sdk#739]
Is there a way to disable `Error Management` portion of the package?

**Comment by bcaudan** [comment]
Hi @alesso-x,

Do you mean automatic collection of console.error, network errors and uncaught exceptions?
There is an option for `browser-logs`: `forwardErrorsToLogs`, cf [configuration options](https://docs.datadoghq.com/logs/log_collection/javascript/#initialization-parameters)
It is not configurable for `browser-rum` for now.

**Comment by alesso-x** [comment]
By error management I mean this [rum/error-tracking](https://app.datadoghq.com/rum/error-tracking). We are using sentry to monitor errors and would like to disable rum error tracking. 

<img width="760" alt="Screen Shot 2021-02-22 at 11 04 43 AM" src="https://user-images.githubusercontent.com/8059120/108734805-d3916080-74fd-11eb-81ce-f872b8c11e3f.png">

**Comment by bcaudan** [comment]
Thanks for the clarification!

Do you have some kind of issue by having both sentry and rum error tracking?
What motivates you to disable this feature?

**Comment by bcaudan** [comment]
Feel free to reopen this issue if needed.
