### ISSUE TITLE
@resource.url_path_group is insufficient to separate resource metrics by HTTP verb

### ISSUE THREAD

**Issue by aethr** [DataDog/browser-sdk#770]
We're trying to get the most out of RUM in terms of implementing monitors/dashboards and not re-invent the wheel. One monitor we would like to use is tracking average response times of API requests, and setting thresholds for when we might get alerted. Since we've already implemented RUM to take advantage of back-end request tracing, we'd like to set up a monitor against a query like:
```
rum("@resource.type:xhr").rollup("avg", "@resource.duration").by("@resource.url_path_group").last("5m") > some average here
```
This would give us average response times against requests like:
```
GET /resource/1
GET /resource/2
```
and group them together as `/resource/?`. So far so good!

Where it gets complicated for us is that we have different lambdas and response types sometimes at the same endpoint, using different HTTP verbs, like:

```
GET /resource/1 - fetch a single resource, avg < 200ms
PUT /resource/1 - update resource, avg > 1000ms
DELETE /resource/1 - soft delete resource, avg < 50ms
```
Each of these has a different profile with a different expected average response time, but by grouping with `@resource.url_path_group` they are all bucketed together, with an avg between 1000ms and 2000ms. We will never get an alert if `DELETE /resource/1` exceeds 500ms, for example.

Our use case would benefit from a resource facet like `@resource.request_group` with a format like `GET /resource/?`.

**Comment by BenoitZugmeyer** [comment]
Hi @aethr. Since different verbs have different thresholds, would it make sense to create a monitor for each verb? Like:

```
rum("@resource.type:xhr @resource.method:GET").rollup("avg", "@resource.duration").by("@resource.url_path_group").last("5m") > 200ms
rum("@resource.type:xhr @resource.method:PUT").rollup("avg", "@resource.duration").by("@resource.url_path_group").last("5m") > 1000ms
etc.
```

**Comment by aethr** [comment]
Hi @BenoitZugmeyer we've taken this approach for now, but it's a lot of manual creation of almost-duplicate monitors.

It does make the thresholds slightly easier to tune since the performance profile for POSTs and DELETEs is very different from GETs, for example. However, having to set static thresholds isn't great in general. That would probably be a separate issue, though. :smiley: 

Thanks for your suggestion. Happy to close this as an issue although I still think it might be a useful feature suggestion for the future.

**Comment by BenoitZugmeyer** [comment]
I'm glad the solution works for you, and I agree that it can be a bit cumbersome to manually create those kind of monitors.

We are currently working on a way to allow users to customize events sent globally. This could allow you to add the `request_group` you mentioned via something like:

```ts
DD_RUM.init({
  ...
  beforeSend(event) {
    if (event.type === 'resource') {
      const urlPathGroup = new URL(event.url).pathname.replace(/\/[^/]*[0-9]+[^/]*/g, '/?')
      event.context.request_group = `${event.resource.method} ${urlPathGroup}`
    }
  }
})
```

Please note: this may not be the definitive API. Also, you might want to adjust the path group computation (but it's basically what is done by our backend).

Then, you'll be able to use `@context.request_group` in your monitors. Does it look fine for you?

**Comment by BenoitZugmeyer** [comment]
Starting with `@datadog/browser-rum v2.13.0`, the above example should now work! Note that you also have access to the `xhr` object or fetch input/init/response values in the `beforeSend` second argument (see [documentation](https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm#enrich-and-control-rum-data)).

Let us know how it works for you.
