### ISSUE TITLE
Clear a previously set user object

### ISSUE THREAD

**Issue by igrayson** [DataDog/browser-sdk#774]
When a user logs out (and becomes an anonymous user), we'd like RUM data to reflect this.

`datadogRum.setUser()` currently does nothing when passed `null`, keeping any previously set value.

**Comment by BenoitZugmeyer** [comment]
Hello @igrayson. You can reset individual user properties by setting them to `undefined`. Would it be fine for you? Exemple: `datadogRum.setUser({ id: undefined, email: undefined })`

**Comment by igrayson** [comment]
Thanks! That might have the outcome we're after (need to read through the code), but it sounds like that would be accidental and likely to break in the future (say, after more attributes are added to the user).

Maybe a better outcome would be a change the datadog RUM SDK API to capture our actual intention: not to clear out specific user attributes, but clear out the entire user.

**Comment by amortemousque** [comment]
This has been released in version 2.9.0.
You can now remove a previously set user like so `datadogRum.removeUser()`
