### ISSUE TITLE
Customize Path Groups

### ISSUE THREAD

**Issue by mwisner** [DataDog/browser-sdk#782]
Hi DataDog team!

First, I just wanted to give a shoutout to all your hard work, this tool has really improved over the past year, and it has become an important part of my team's toolbelt. 

Our site's (an SPA) URL structure is fairly complex. We have both locale-based URL prefixes and complex URL patterns with a few different types of pages with similar (non-prefixed) URLs.  

While this URL structure works well for users and SEO, it makes using RUM challenging because we can't aggregate pages together in logical groups. 

Is there any documentation around how to customize or manually define a given page's path group, using other app-specific information? 

Any help on this would be much appreciated!

Thanks,
Matt.

**Comment by bcaudan** [comment]
Hi @mwisner,

For now, we don't have any capabilities to customize the path group.
However, we are currently working on having the possibility to manually track views and provide custom names for them that would be use instead of the path group.

How would that sound for your case?

**Comment by mwisner** [comment]
Hi @bcaudan,

Yes that would work for our case. We would be willing to go through and manually track all our views in order to accomplish this, as long as it works with our react SPA and NextJS.

**Comment by bcaudan** [comment]
Hello!

Since browser-sdk@2.17.0, you can now track views manually and define your own view names.
More info on the [documentation](https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#override-default-rum-view-names).
