### ISSUE TITLE
Include request duration in "network" errors

### ISSUE THREAD

**Issue by dtinth** [DataDog/browser-sdk#799]
Hello, we occasionally get an error reported in our RUM console with `@error.resource.status_code:0`. This can be caused by many different reasons:

- Request is aborted (timeout)
- Server or internet is down (cannot connect)
- Request blocked by extension
- Request does not satisfy CORS

We don’t know which caused it. I think having the request duration present in the error might give us some more clue though. Thank you for the consideration.

**Comment by BenoitZugmeyer** [comment]
Hi @dtinth,

We are in the process to redesign network errors. We will deprecate "network" error events, and instead provide a new way to track network errors based on resource events, which include the duration you are looking for.

At the same time, we definitely want to improve the "status code 0" situation by providing the reason why the request failed on resource events. Stay tuned!

**Comment by bcaudan** [comment]
RUM network errors removed with v3, cf https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#rum-network-errors-no-longer-monitored
