### ISSUE TITLE
Improve beforeSend typing

### ISSUE THREAD

**Issue by nmbro** [DataDog/browser-sdk#822]
Currently:

https://github.com/DataDog/browser-sdk/blob/270cff1aa97aa1202a88e63fc20d429289b33ee4/packages/core/src/domain/configuration.ts#L54

`beforesend(event)` is of type any, is it possible to get a better type here instead of any?

**Comment by bcaudan** [comment]
Hello @nmbro,

It is actually but from Logs and RUM configuration interfaces:

https://github.com/DataDog/browser-sdk/blob/270cff1aa97aa1202a88e63fc20d429289b33ee4/packages/logs/src/boot/logs.ts#L25

https://github.com/DataDog/browser-sdk/blob/270cff1aa97aa1202a88e63fc20d429289b33ee4/packages/rum-core/src/boot/rumPublicApi.ts#L25

How are you using it?
There is probably something for us to improve here.

**Comment by nmbro** [comment]
It did autocomplete it in my IDE.

I was using it for the RUM part

**Comment by bcaudan** [comment]
Hum, not sure why your IDE tried to pick the one from core 😕 
We should probably get rid of it anyway.

Have you managed to make it work with the right types?

**Comment by nmbro** [comment]
It probably didn't, I was just browsing the source code, so I was probably just oblivious to the actual correct implementations / interfaces

**Comment by bcaudan** [comment]
Things should have been improved in v4, feel free to reopen otherwise.
