### ISSUE TITLE
Major difference rum-eu for only rum

### ISSUE THREAD

**Issue by mario-silva-maersk** [DataDog/browser-sdk#826]
Please, I saw that this message in the script:
datadog-rum-eu.js IS DEPRECATED, USE datadog-rum.js WITH { site: 'datadoghq.eu' } INIT CONFIGURATION INSTEAD
However, I could not find the major difference or what impact  I can have if I dont change the way to call. 
current script:
https://www.datadoghq-browser-agent.com/datadog-rum-eu.js
the new way of call:
https://www.datadoghq-browser-agent.com/datadog-rum.js
Please, there is any place where I can see the features or what was deprecated.
Thanks.

**Comment by bcaudan** [comment]
Hi @mario-silva-maersk,

You should not have differences between the two but since this approach is not documented anymore, we advise to use the new one.

**Comment by mario-silva-maersk** [comment]
Thanks for the prompt reply @bcaudan , I will notify my colleagues and change this.
