### ISSUE TITLE
@wdio/cli security issue

### ISSUE THREAD

**Issue by giuseppe-tagomi** [DataDog/browser-sdk#831]
Hello Datadog Team,
I am evaluating using datadog library on the frontend but when running Salus I found out one of your nested library dependency (@wdio/cli) is using a a compromised version of y18n (4.0.0) [npm advisory](https://www.npmjs.com/advisories/1654).

Would you be able to upgrade your @wdio/cli dependency to the latest version?

thank you so much

**Comment by bcaudan** [comment]
Hello @giuseppe-tagomi,

Thanks for reporting that, we'll look into it shortly!

**Comment by bcaudan** [comment]
Hey @giuseppe-tagomi, sorry for the late answer, this one slipped through the cracks... 

This issue has been fixed.
