### ISSUE TITLE
How to access the trace id / (session | view) id 

### ISSUE THREAD

**Issue by jippi** [DataDog/browser-sdk#839]
Hey,

We've just started implementing DD RUM in our admin system (client-facing) and we love it so far.

As part of providing a better and more effective support experience, we would love to be able to provide a Trace ID or Session ID in the footer of our pages that customers can provide to our support team when something goes bad, however, I can't find a way to extract these properties from `window.DD_RUM` 

Is there an accessible way to extract both (or one) of the two identifiers at runtime? 

Alternatively, if you have a better idea of how to do it, I'm all ears. We do provide User context and a custom context for the back office organization of the user, but it would require a couple of manual steps to map that back to a particular page view

Thank you,

**Comment by bcaudan** [comment]
Hello @jippi,

I think you could either:

1. generate this id yourself and attach it to RUM events using [global context](https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm#global-context) 
2. retrieve a relevant id from RUM internal context with [getInternalContext API](https://docs.datadoghq.com/real_user_monitoring/browser/troubleshooting/#check-that-the-browser-rum-sdk-is-initialized)

**Comment by jippi** [comment]
Hi @bcaudan,

Thanks for your fast response and suggestions - I'm going to give them a try and reopen the ticket if it doesn't solve my problem 

Thank you! :)
