### ISSUE TITLE
Infinite looping when blocked by CSP

### ISSUE THREAD

**Issue by sean-roberts** [DataDog/browser-sdk#874]
When CSP blocks the RUM library's connection to DD intake endpoint, the library goes into an infinite loop.

Note, we have datadog's endpoints in our CSP however there are several reasons why this could still be an issue - such as extensions changing CSP or privacy blockers preventing it. But when this happens, it triggers hundreds to thousands of requests/viloations which can cause issues with the app and quota/billing issues with vendors like report-uri.

video demonstrating the issue: https://share.getcloudapp.com/9ZudrvP4

Reproduce by setting a `connect-src` CSP directive that doesn't include DD

The expectation is that it should fail but not continue to make retries indefinitely.

We are on browser npm module 2.7.4 - and I see 2.11.1 is out. I'm going to see if upgrading solves the issue but let's assume it won't for now as I didn't see any tickets related to this issue closed.

**Comment by bcaudan** [comment]
Hi @sean-roberts,

Thanks for reporting that, we will look into it shortly!

**Comment by amortemousque** [comment]
Hi @sean-roberts,

I tried to recreate the issue and I do get a CSP error "Refused to connect" when the library calls the intake, but no infinite loop.
Do you have more information about your configuration that can help me?

You can find the code sample I used [here](https://github.com/amortemousque/RUM-infinite-looping-csp/blob/master/index.html).

**Comment by sean-roberts** [comment]
OK so I looked into it more and guess what, it was our issue! :) What happens is we were monitoring CSP violations and send them to DD. If DD causes the violations.. well it loops.

Thanks for looking into it! Apologies for the distraction

**Comment by amortemousque** [comment]
No problem,

**Comment by amortemousque** [comment]
No problem,
If it helped to fix the issue on your side, this is a good news!
