### ISSUE TITLE
beforeSend ignores non-blessed property modifications?

### ISSUE THREAD

**Issue by Munter** [DataDog/browser-sdk#877]
I want to log my users identity as part of each log entry, so I can better track user interactions based on the user identity over time.

I do this with `usr.id`, aligning with [DD USER RELATED ATTRIBUTES](https://docs.datadoghq.com/logs/processing/attributes_naming_convention/#user-related-attributes).

I have a single-page app, and the user can go from anonymous to logged in during a single page's lifecycle. This means I can't set `usr.id` by adding it as global context when initializing my logger.

I've attempted to use `beforeSend` to augment my `usr` object by adding `usr.id` at this point if it exists, but this change to the event doesn't seem to propagate all the way to datadog.

Is this the correct way of doing it?

I've considered calling `loggerInstance.setLoggerGlobalContext` with my  newly acquired `usr.id` when the user logs in. But `removeLoggerGlobalContext` seems to only take a string as argument, so it is unclear to me how I can remove `usr.id` from the global context again when the user logs out.

**Comment by bcaudan** [comment]
👋 @Munter,

beforeSend is only usable for scrubbing sensitive info on some specific fields, more info on the [doc](https://docs.datadoghq.com/logs/log_collection/javascript/#scrub-sensitive-data-from-your-browser-logs). 

In order to remove `usr.id`, you can set it to `undefined`.

**Comment by Munter** [comment]
I'll try thah. Thanks
