### ISSUE TITLE
Send traceId in another header

### ISSUE THREAD

**Issue by bcaudan** [DataDog/browser-sdk#894]
spin off from https://github.com/DataDog/browser-sdk/issues/729#issuecomment-861464930, cc @philippeLepage

What I am trying to do is to duplicate the traceId in another header before sending my request.

1. creating a request with axios
2. go through my beforeSend call back from datadog rum sdk
3. retrieve event._dd.trace_id 
4. add trace_id as a new header to the request 

The step 4 I cannot see how to do it.  I've tried adding it in headers in the event of the beforeSend callback but it seems to be ignored later on by the sdk.  

While browsing through your code, I've seen that the beforeSend receives  (context: StartContext, xhr: XMLHttpRequest) as parameters instead of just an event.  

```
interface BrowserXHR<T extends XhrOpenContext> extends XMLHttpRequest {
  _datadog_xhr?: T
}

export interface XhrProxy<
  StartContext extends XhrStartContext = XhrStartContext,
  CompleteContext extends XhrCompleteContext = XhrCompleteContext
> {
  beforeSend: (callback: (context: StartContext, xhr: XMLHttpRequest) => void) => void
  onRequestComplete: (callback: (context: CompleteContext) => void) => void
}

export interface XhrOpenContext {
  method: string
  url: string
}

export interface XhrStartContext extends XhrOpenContext {
  startTime: RelativeTime // deprecated
  startClocks: ClocksState
  isAborted: boolean
  /**
   * allow clients to enhance the context
   */
  [key: string]: unknown
}
```

Seeing that, I figured out that I should be able to add my new header to either one of them and it would be added to my request by datadog rum sdk.  But anything I put there gets ignored and only the "x-datadog-xyz" headers get added.

**Comment by bcaudan** [comment]
> What I am trying to do is to duplicate the traceId in another header before sending my request.

Why do you want to do that?

> go through my beforeSend call back from datadog rum sdk

beforeSend callback is called before sending the event to datadog, not before sending your request.
So at this time your request is already completed, so it is too late to update its headers.

**Comment by philippeLepage** [comment]
> > What I am trying to do is to duplicate the traceId in another header before sending my request.
> 
> Why do you want to do that?
> 

I want to use the value of the x-datadog-trace-id as the same trace id for my logging system.   This is why I want to duplicate it in another header that my logging system is aware of.  Life would be simpler if we were using the datadog logs too, but such is not the case unfortunately.  

> > go through my beforeSend call back from datadog rum sdk
> 
> beforeSend callback is called before sending the event to datadog, not before sending your request.
> So at this time your request is already completed, so it is too late to update its headers.

Ah!  Then it all makes sense!  Then, beforeSend is not the way to achieve what I am trying to do.

Any idea?

Thank you again for your explanations.

**Comment by bcaudan** [comment]
> I want to use the value of the x-datadog-trace-id as the same trace id for my logging system. This is why I want to duplicate it in another header that my logging system is aware of. Life would be simpler if we were using the datadog logs too, but such is not the case unfortunately.

OK, got it.

I don't see a way to do that with our current APIs.
However, you could probably intercept requests yourself to duplicate the trace id header before sending the request.
You can have a look at how we do it for [XHR](https://github.com/DataDog/browser-sdk/blob/main/packages/core/src/browser/xhrProxy.ts) and [fetch](https://github.com/DataDog/browser-sdk/blob/main/packages/core/src/browser/fetchProxy.ts).

**Comment by philippeLepage** [comment]
Thank you very much @bcaudan for all the clarifications.
Much appreciated!
And I'll check into it the XHR/Fetch proxy to see how you do it...

**Comment by amortemousque** [comment]
Hi @philippeLepage,

Since we haven't heard back, we'll close this issue for now. Please reopen it if you have more details to add.

Thanks!
