### ISSUE TITLE
Page group catching urls with any numeric characters

### ISSUE THREAD

**Issue by sean6bucks** [DataDog/browser-sdk#904]
I recently implemented the RUM monitoring into our website project, and have been noticing some strange results when viewing the "Most viewed pages" section in the RUM - Performance Overview dashboard. It seems like a bit of mix of full URL's and many `/?` group paths, which after looking into the docs found that this was the pattern used to group similar urls, such as `/product/123` and `product/456`.  However we do not have any URLs following exactly that pattern, and yet a lot of pages, that are not necessarily similar in content, get bundled into these `?` groups.

I found that whatever regex or matching the library does to determine these path groups, is simply looking for any numeric values, which causes a problem with many of our pages, not only because occasionally a number will appear in the title of a page (say based on an article name), but also because our company contains a digit, which will also appear in some url paths.

For example:  
`company10.com/help-100-customers` => `/?`
`company10.com/about-company10` => `/?`

Is this expected behaviour for path groups? As I mentioned I think this could cause many unsimilar pages in structure (visual elements affecting core vitals), resources, xhr calls, etc. to be grouped together in metrics.

**Comment by bcaudan** [comment]
Hi @sean6bucks,

Page grouping is not handled in this repository so we won't be able to provide much help on that front.
I'd suggest you to reach out to [Datadog support](https://www.datadoghq.com/support/) directly.
