### ISSUE TITLE
Scrub sensitive data included in error stack

### ISSUE THREAD

**Issue by simonschwartz** [DataDog/browser-sdk#917]
We have found that some error stacks are including the page URL which may include personal data that such as email. We would like to redact this error.stack data in the same way we redact that data from the URL property. While it seems possible according to the documentation, the types seem to indicate otherwise.

I am hoping to achieve something along these lines:

```
datadogLogs.init({
  clientToken: DATADOG_CLIENT_TOKEN,
  datacenter: 'us',
  forwardErrorsToLogs: true,
  sampleRate: 100,
  beforeSend: event => {
    const redactedURL = redactURL(event.view.url);
    const redactedErrorStack = redactErrorStack(event.error.stack);

    event.view.url = redactedURL;
    event.error.stack = redactedErrorStack;
  }
});
```

While we can [use beforeSend](https://docs.datadoghq.com/logs/log_collection/javascript/#scrub-sensitive-data-from-your-browser-logs) to scrub this data from the URL(event.view.url), we get a TypeScript error when attempting to do the same with the error stack(event.error.stack) as it is [ReadOnly](https://github.com/DataDog/browser-sdk/blob/main/packages/logs/src/logsEvent.types.ts#L71). The docs seem to suggest that we should be able to modify any attribute listed in the [event properties table](https://docs.datadoghq.com/logs/log_collection/javascript/#scrub-sensitive-data-from-your-browser-logs).

Is it possible to scrub data from the event.error.stack property?

**Comment by BenoitZugmeyer** [comment]
You are right, `error.stack` should be writable. Thank you for your report! I adjusted the types in #918.
