### ISSUE TITLE
dd_cookie_test_{uuid} not manually deleted which makes it just stick around in firefox.

### ISSUE THREAD

**Issue by oneeyedziggy** [DataDog/browser-sdk#926]
dd_cookie_test_{uuid} cookies produced in packages/core/src/browser/cookie.ts rely on the expiry time to delete the cookie, which firefox doesn't do. Combined w/ the uuid in the cookie name, this makes for a noisy cookie source producing one extra cookie per page load until you clear cookies. 

Would love for this to either be manually deleted (probably the simplest fix) or to be a session cookie to better signal the transient intent of this cookie ( though that doesn't work to confirm non-session cookies can be used )

**Comment by bcaudan** [comment]
Hello @oneeyedziggy,

Thanks for reporting this, we'll look into it quickly.

**Comment by amortemousque** [comment]
Hello @oneeyedziggy,

The fix has been released in version 2.18.0.
