### ISSUE TITLE
Feature request: Provide more context for DOM manipulation errors

### ISSUE THREAD

**Issue by dtinth** [DataDog/browser-sdk#928]
We have quite a complex React application with multiple features. Sometimes it would send out an error like this.

> Failed to execute 'removeChild' on 'Node': The **node to be removed** is not a child of **this node**.

![image](https://user-images.githubusercontent.com/193136/124888836-ab178800-e000-11eb-9b35-5f1159462323.png)

All stack trace points into React’s source code, with no mention of our own app code.

![image](https://user-images.githubusercontent.com/193136/124889356-37c24600-e001-11eb-89b8-cb2b8022ac4a.png)

My assumption is that some third-party library or Chrome extension is interfering with the DOM element, causing React to mulfunction, resulting in the above error. But without any more information on what is meant by “node to be removed” and “this node”, it becomes very hard for us to find out what went wrong.

It would be great if Datadog’s SDK would attach some more context, e.g. selectors to the DOM node — so we can know where the problem lies.

**Comment by NesChaiyapon** [comment]
+1

**Comment by bcaudan** [comment]
Hello @dtinth,

if the DOM element is somehow provided with the React error, you could probably do something with it yourself with the [beforeSend API](https://docs.datadoghq.com/real_user_monitoring/guide/enrich-and-control-rum-data).
Otherwise, it will probably require a more deeper react integration which is something that we plan to work on soon.

**Comment by amortemousque** [comment]
Hello,
We have a documentation to explain how to [instrument React Error boundaries](https://docs.datadoghq.com/real_user_monitoring/browser/collecting_browser_errors/?tab=npm#react-error-boundaries-instrumentation) allowing to collect the component Stack. That should help you get context around React Errors.
If you have any updates or further information, please feel free to reopen the issue.
