### ISSUE TITLE
Stack traces are not formated correctly for chrome extensions

### ISSUE THREAD

**Issue by dickfickling** [DataDog/browser-sdk#957]
In computeStackTrace.ts, the regex for matching a Chrome stack line marks the open parenthesis as required, when it shouldn't be. This causes my stack traces to be mangled on upload to RUM. This is making RUM unusable for me as the uploaded stack traces don't correspond to the actual code.

I created a PR (#954) which updates a test that was "working", but actually silently parsing certain lines as winjs stack lines, to add a line for a chrome extension stack trace example. By making the open parenthesis in the regex optional, that specific test starts to pass again, but it causes other tests to fail.

See #954 for more details.

**Comment by liywjl** [comment]
Hello @dickfickling, 

Thank you for reporting this issue. We have resolved it as of v4.16.0.

It appears that our regex struggled to handle cases where anonymous functions are swallowed by the stack trace. I was not able to reproduce the stack trace myself but using the examples provided in your [PR](https://github.com/DataDog/browser-sdk/pull/954) I added some new [unit test](https://github.com/DataDog/browser-sdk/pull/1647/files#diff-ff9c61c635cc727f4558a106898fe5f24808fca1b1a5f748305d36929a7e0f45R516-R522) to cover this new case.

I hope this solves your issue. Don't hesitate to open another ticket if you have a specific issue related to the SDK or contact [datadog support](https://www.datadoghq.com/support/) directly.
