### ISSUE TITLE
Cannot import Datacenter

### ISSUE THREAD

**Issue by strowk** [DataDog/browser-sdk#982]
I am trying to use datadog RUM like this:

`import { Datacenter, datadogRum } from '@datadog/browser-rum'`
, but it does not work. Cannot import Datacenter. I found where this was added: 

https://github.com/DataDog/browser-sdk/pull/436

, but there is no information in changelog about removal. Is it moved somewhere? Where do I take the url now?

**Comment by BenoitZugmeyer** [comment]
We removed it as part of the RUM v3 release. The `datacenter` option has been removed [as mentioned in the changelog](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#rum-and-logs-removed-init-options). You should now use the `site` option (ex: `site: "datadoghq.com"`)

**Comment by strowk** [comment]
Ah, I did not realize that Datadog enum is documented as 'option'. Maybe could be more clearly named enum, since this is how it was named when it was added in earlier entry `export Datacenter enum`

**Comment by BenoitZugmeyer** [comment]
The `Datacenter` enum is not documented as 'option'. What we call "`datacenter` option" is the init option passed as `DD_RUM.init`:

```ts
DD_RUM.init({
  // ...
  datacenter: Datacenter.US
})
```

The sole purpose of the `Datacenter` enum was to be used with this option. This is why the enum has been removed as well.
