### ISSUE TITLE
Cannot use datadogRum.addError

### ISSUE THREAD

**Issue by strowk** [DataDog/browser-sdk#983]
I followed this documentation - https://docs.datadoghq.com/real_user_monitoring/browser/collecting_browser_errors/?tab=npm

and used this part 
```
fetch('<SOME_URL>').catch(function(error) {
    datadogRum.addError(error, undefined, 'network');
})
```
, but it does not work anymore, I get `Expected 1-2 arguments, but got 3` from Typescript. 
Please update those docs if API changed

**Comment by BenoitZugmeyer** [comment]
The third argument ('network' in your case) have been removed [as part of the v3 release](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#rum-source-attribute-of-adderror-has-been-removed). The documentation is being updated right now. Sorry for the inconvenience.
