### ISSUE TITLE
Document how to log fetch errors

### ISSUE THREAD

**Issue by strowk** [DataDog/browser-sdk#984]
Currently documentation here 
https://docs.datadoghq.com/real_user_monitoring/browser/data_collected/#error-attributes
mentions `error.resource.status_code`. 
And documentation here https://docs.datadoghq.com/real_user_monitoring/browser/collecting_browser_errors/?tab=npm
explains how we can use fetch API and report errors 
```
fetch('<SOME_URL>').catch(function(error) {
    datadogRum.addError(error, undefined, 'network');
})
```
, but these things do not seem to be compatible, since fetch does not fail on http status code error, hence it seems to impossible to actually receive  `error.resource.status_code` from `fetch` following this documentation (correct me if I am wrong). 
So the question is - how to get errors from fetch with all that is documented for network errors in a situation when we have got f.e. 504 from backend? Is this even possible? If not - please document so it would be clear, that `fetch` is not supported.

**Comment by BenoitZugmeyer** [comment]
The documentation is being updated. Network errors have been removed as part of the v3 release. Please follow [this guide](https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#rum-errors) to restore sending failed requests as RUM errors.
