### ISSUE TITLE
is there a lazy loading strategy for datadog?

### ISSUE THREAD

**Issue by jantimon** [DataDog/browser-sdk#985]
The data-dog package is larger than jQuery which was kind of surprising for me..

Is it possible to lazy load data-dog or is it important to load data-dog asap?

Is there a smart lazy loading version of data dog which loads parts like stack trace analysation only once needed?

What is the difference between `browser-rum-slim` and `browser-rum`?

**Comment by BenoitZugmeyer** [comment]
For now, there is no way to lazily load parts of the RUM SDK. We have to provide support for multiple setups (NPM, CDN  bundles), making such optimization hard  to execute, but we are considering it and it should happen sooner or later.

If you worry that it may affect your application start time, you can use the ["async setup"](https://docs.datadoghq.com/real_user_monitoring/browser/#cdn-async) so it is loaded asynchronously.

Like mentioned in [the README](https://github.com/DataDog/browser-sdk/tree/main/packages/rum-slim#overview), the difference between `rum-slim` and `rum` is that it doesn't contain code for session recording, so if you don't use it (ex: you don't call `DD_RUM.startSessionReplayRecording()` anywhere) you can use the smaller package `rum-slim`.
