### ISSUE TITLE
Plus sign from version is changed to underscore

### ISSUE THREAD

**Issue by strowk** [DataDog/browser-sdk#988]
We are trying to configure Datadog RUM source maps to see stack traces. Both source maps upload functionality and Datadog RUM SDK ask to provide version to match reported data with source maps.
I configured version to be sent as a semantic version with normal version X.Y.Z and metadata (follows after `+`) with git hash. So our versions looks like this `0.0.1+<git_hash>`. The reason why git hash should be in metadata is that metadata is not considered in precedence, which is what makes sense, since git hashes are not sorted ( see https://semver.org/#spec-item-10 ). 

However, what I can see is that source maps do not work. Also I can see that `datadog-ci` logs version with a plus sign when it reports uploaded source maps. But in Datadog UI I can see that instead of `+` sign in version - there is underscore and instead of proper stack traces - I see chunks produced by CRA. 
Now I am not sure if this `+` changed to `_` is the reason behind source maps not working or I have broken something else. 

Is there anywhere documented which symbols are allowed in version? Also what is changing plus to underscore? Is it done in SDK or on Datadog service side? What are best practices here? I thought that following semver is the right way to go, but maybe Datadog is not good with semver, I am confused right now.

**Comment by bcaudan** [comment]
Hello,

There is a known issue on the backend about the plus sign changed to underscore.
Not sure if it can bother source maps integration as it is not related to this repository.

You should go through [Datadog support](https://www.datadoghq.com/support/) to get more help on this topic.

**Comment by strowk** [comment]
So this is not changed by SDK? Should I maybe create issue to https://github.com/DataDog/datadog-ci ? 

I think issues in Github more effective than ticket to support, which nobody can see. 
Currently I found workaround to simply use prerelease versions - with `-` dash instead of plus, but this wrong use of semantic versioning unfortunately.

**Comment by bcaudan** [comment]
> So this is not changed by SDK? 

No, it is sent correctly by the SDK

> I think issues in Github more effective than ticket to support, which nobody can see.

I would agree if the issue was clearly related to the repository

> I think specific mention that semantic versions are not supported would be nice

agree, but I think it has not been raised before, so it would be better to fix it
