### ISSUE TITLE
Request for trackViewsManually SPA Example

### ISSUE THREAD

**Issue by mwisner** [DataDog/browser-sdk#998]
Hi Team, 

I am eagerly trying to implement the new trackViewsManually functionality into our React-based application(s). Unfortunately, no matter what I try, the initial page view id carries to the next page view and gets the URL for the new page, but with the previous view name. 

Are there any hello-world level examples of the proper usage of trackViewsManually? I'd love to get a better of the recommended implementation of this functionality. 

Thanks!

**Comment by masad-frost** [comment]
I'm pretty sure it's bugged. It's supposed to work by updating the view context by calling `startView`, but it just doesn't.

**Comment by bcaudan** [comment]
Hello @mwisner,

We have identified and fixed [a wrong behavior](https://github.com/DataDog/browser-sdk/pull/1063) related to `trackViewsManually` which look similar to what you are describing. 
The fix has been release in version `3.6.1`.

Let us know if you still encounter an issue with it.

**Comment by mwisner** [comment]
Hi @bcaudan,

We've had `6.3.1` with manual view tracking enabled throughout our application for a few days now and everything seems to be working wonderfully. 

Thank you so much for resolving this issue, I **really** appreciate being able to use this functionality in our application.

**Comment by bcaudan** [comment]
Great!

Thanks for the feedback.
